import crypto from 'node:crypto';
import {aiPool,platformPool} from './ai-database.js';
import {hash,uuid,quantity} from './ai-policy.js';
const fail=m=>{const e=new Error(m);e.status=400;throw e};
const checkId=x=>{if(!uuid.test(String(x)))fail('Ungültige ID');return x};
const clean=x=>String(x||'').trim().slice(0,150);
export async function migrateAiRecipes(){await aiPool().query(`
ALTER TABLE ai_stock DROP CONSTRAINT IF EXISTS ai_stock_quantity_check;
CREATE TABLE IF NOT EXISTS ai_recipes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),account_id uuid NOT NULL REFERENCES ai_accounts(id),location_id uuid NOT NULL REFERENCES ai_locations(id),name text NOT NULL,external_code text NOT NULL,active boolean NOT NULL DEFAULT true,UNIQUE(account_id,location_id,external_code));
CREATE TABLE IF NOT EXISTS ai_recipe_items(recipe_id uuid NOT NULL REFERENCES ai_recipes(id) ON DELETE CASCADE,stock_id uuid NOT NULL REFERENCES ai_stock(id),quantity numeric(15,3) NOT NULL CHECK(quantity>0),PRIMARY KEY(recipe_id,stock_id));
CREATE TABLE IF NOT EXISTS ai_connectors(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),account_id uuid NOT NULL REFERENCES ai_accounts(id),location_id uuid NOT NULL REFERENCES ai_locations(id),name text NOT NULL,kind text NOT NULL CHECK(kind IN ('api','pos')),token_hash text UNIQUE,active boolean NOT NULL DEFAULT false,pos_restaurant_id uuid,pos_user_id uuid,pos_company_id uuid,cursor_time timestamptz NOT NULL DEFAULT now(),cursor_id uuid,last_error text,last_sync timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS ai_pos_active_connector ON ai_connectors(pos_restaurant_id) WHERE kind='pos' AND active;
CREATE TABLE IF NOT EXISTS ai_sale_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),connector_id uuid NOT NULL REFERENCES ai_connectors(id),account_id uuid NOT NULL REFERENCES ai_accounts(id),external_id text NOT NULL,event_type text NOT NULL CHECK(event_type IN ('sale','reversal')),fingerprint text NOT NULL,reverses_id uuid UNIQUE REFERENCES ai_sale_events(id),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(connector_id,external_id));
CREATE TABLE IF NOT EXISTS ai_sale_effects(event_id uuid NOT NULL REFERENCES ai_sale_events(id),stock_id uuid NOT NULL REFERENCES ai_stock(id),delta numeric(15,3) NOT NULL,PRIMARY KEY(event_id,stock_id));
`)}
export async function ingestSale(connector,event){
 const externalId=clean(event.eventId),type=event.type||'sale';if(!externalId||!['sale','reversal'].includes(type))fail('Eindeutige eventId und gültiger Typ erforderlich');
 let normalized;if(type==='sale'){if(!Array.isArray(event.items)||!event.items.length||event.items.length>100)fail('1 bis 100 Verkaufspositionen erforderlich');normalized=event.items.map(x=>({productCode:clean(x.productCode),quantity:quantity(x.quantity)})).sort((a,b)=>a.productCode.localeCompare(b.productCode));if(normalized.some(x=>!x.productCode||x.quantity<=0))fail('Artikelcode und positive Verkaufsmenge erforderlich')}else{if(!clean(event.reversesEventId))fail('Originalereignis erforderlich');normalized=clean(event.reversesEventId)}
 const fingerprint=hash(JSON.stringify({type,items:normalized})),c=await aiPool().connect();try{
  await c.query('BEGIN');const link=(await c.query("SELECT c.* FROM ai_connectors c JOIN ai_accounts a ON a.id=c.account_id WHERE c.id=$1 AND c.active AND a.status='active' FOR UPDATE OF c",[connector.id])).rows[0];if(!link){const e=new Error('Anbindung nicht aktiv');e.status=403;throw e}
  const old=(await c.query('SELECT * FROM ai_sale_events WHERE connector_id=$1 AND external_id=$2',[link.id,externalId])).rows[0];if(old){if(old.fingerprint!==fingerprint){const e=new Error('Ereignis-ID bereits mit anderen Daten verwendet');e.status=409;throw e}await c.query('UPDATE ai_connectors SET last_sync=now(),last_error=NULL WHERE id=$1',[link.id]);await c.query('COMMIT');return {eventId:old.id,duplicate:true}}
  let effects=new Map(),reverses=null;
  if(type==='sale'){
   for(const item of normalized){const recipe=(await c.query('SELECT id FROM ai_recipes WHERE account_id=$1 AND location_id=$2 AND external_code=$3 AND active',[link.account_id,link.location_id,item.productCode])).rows[0];if(!recipe)fail('Rezept fehlt für Artikelcode '+item.productCode);const ingredients=(await c.query('SELECT stock_id,quantity FROM ai_recipe_items WHERE recipe_id=$1',[recipe.id])).rows;if(!ingredients.length)fail('Rezept ohne Zutaten: '+item.productCode);for(const ingredient of ingredients)effects.set(ingredient.stock_id,(effects.get(ingredient.stock_id)||0)-Number(ingredient.quantity)*item.quantity)}
  }else{
   const original=(await c.query("SELECT id FROM ai_sale_events WHERE connector_id=$1 AND external_id=$2 AND event_type='sale' FOR UPDATE",[link.id,normalized])).rows[0];if(!original)fail('Originalverkauf nicht gefunden');if((await c.query('SELECT 1 FROM ai_sale_events WHERE reverses_id=$1',[original.id])).rowCount){const e=new Error('Dieser Verkauf wurde bereits zurückgebucht');e.status=409;throw e}reverses=original.id;for(const effect of (await c.query('SELECT * FROM ai_sale_effects WHERE event_id=$1',[original.id])).rows)effects.set(effect.stock_id,-Number(effect.delta));
  }
  const record=(await c.query('INSERT INTO ai_sale_events(connector_id,account_id,external_id,event_type,fingerprint,reverses_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[link.id,link.account_id,externalId,type,fingerprint,reverses])).rows[0];
  for(const [stockId,amount] of [...effects].sort(([a],[b])=>a.localeCompare(b))){const delta=Math.round(amount*1000)/1000;if(Math.abs(delta)>1000000000)fail('Verbrauchsmenge zu hoch');const row=(await c.query('SELECT id FROM ai_stock WHERE id=$1 AND account_id=$2 AND location_id=$3 FOR UPDATE',[stockId,link.account_id,link.location_id])).rows[0];if(!row)fail('Zutat gehört nicht zum Standort');await c.query('UPDATE ai_stock SET quantity=quantity+$2 WHERE id=$1',[stockId,delta]);await c.query('INSERT INTO ai_sale_effects VALUES($1,$2,$3)',[record.id,stockId,delta]);await c.query('INSERT INTO ai_stock_moves(stock_id,actor_id,delta,reason) VALUES($1,$2,$3,$4)',[stockId,link.account_id,delta,(type==='sale'?'Rezeptverbrauch: ':'Verbrauch zurückgebucht: ')+externalId])}
  await c.query('UPDATE ai_connectors SET last_sync=now(),last_error=NULL WHERE id=$1',[link.id]);await c.query('COMMIT');return {eventId:record.id,duplicate:false};
 }catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}
}
export async function apiSalesToken(token){return (await aiPool().query("SELECT c.* FROM ai_connectors c JOIN ai_accounts a ON a.id=c.account_id WHERE c.token_hash=$1 AND c.kind='api' AND c.active AND a.status='active'",[hash(token)])).rows[0]}
export async function recipeRoutes(p,method,b,u){
 if(!['/api/ai/recipes','/api/ai/connectors','/api/ai/pos-link','/api/ai/connector-status','/api/ai/recipe-events'].includes(p))return null;
 if(u.role!=='restaurant'){const e=new Error('Nur Restaurantbesitzer haben Zugriff');e.status=403;throw e}
 const pool=aiPool();
 if(p==='/api/ai/recipes'&&method==='GET'){const recipes=(await pool.query('SELECT r.*,l.name location_name FROM ai_recipes r JOIN ai_locations l ON l.id=r.location_id WHERE r.account_id=$1 ORDER BY r.name',[u.id])).rows;for(const r of recipes)r.items=(await pool.query('SELECT i.*,s.name,s.unit FROM ai_recipe_items i JOIN ai_stock s ON s.id=i.stock_id WHERE recipe_id=$1',[r.id])).rows;return {recipes}}
 if(p==='/api/ai/recipes'&&method==='POST'){
  checkId(b.locationId);const name=clean(b.name),code=clean(b.productCode);if(!name||!code||!Array.isArray(b.items)||!b.items.length||b.items.length>100)fail('Rezeptname, Artikelcode und Zutaten erforderlich');if(b.id)checkId(b.id);
  const c=await pool.connect();try{await c.query('BEGIN');if(!(await c.query('SELECT id FROM ai_locations WHERE id=$1 AND account_id=$2',[b.locationId,u.id])).rowCount)fail('Standort nicht gefunden');let recipeId;if(b.id){const r=await c.query('UPDATE ai_recipes SET name=$3,external_code=$4,active=$5 WHERE id=$1 AND account_id=$2 AND location_id=$6 RETURNING id',[b.id,u.id,name,code,b.active!==false,b.locationId]);if(!r.rowCount)fail('Rezept nicht gefunden');recipeId=b.id;await c.query('DELETE FROM ai_recipe_items WHERE recipe_id=$1',[recipeId])}else recipeId=(await c.query('INSERT INTO ai_recipes(account_id,location_id,name,external_code) VALUES($1,$2,$3,$4) RETURNING id',[u.id,b.locationId,name,code])).rows[0].id;
   const seen=new Set();for(const item of b.items){checkId(item.stockId);const qty=quantity(item.quantity);if(qty<=0||seen.has(item.stockId))fail('Positive, eindeutige Zutatenmengen erforderlich');seen.add(item.stockId);if(!(await c.query('SELECT id FROM ai_stock WHERE id=$1 AND account_id=$2 AND location_id=$3',[item.stockId,u.id,b.locationId])).rowCount)fail('Zutat gehört nicht zum Rezeptstandort');await c.query('INSERT INTO ai_recipe_items VALUES($1,$2,$3)',[recipeId,item.stockId,qty])}await c.query('COMMIT');return {ok:true};
  }catch(e){await c.query('ROLLBACK');if(e.code==='23505')fail('Artikelcode ist für diesen Standort bereits vergeben');throw e}finally{c.release()}
 }
 if(p==='/api/ai/connectors'&&method==='GET')return {connectors:(await pool.query('SELECT id,name,kind,location_id,active,last_error,last_sync,cursor_time FROM ai_connectors WHERE account_id=$1 ORDER BY created_at DESC',[u.id])).rows};
 if(p==='/api/ai/connectors'&&method==='POST'){checkId(b.locationId);if(!(await pool.query('SELECT id FROM ai_locations WHERE id=$1 AND account_id=$2',[b.locationId,u.id])).rowCount)fail('Standort nicht gefunden');const name=clean(b.name);if(!name)fail('Name erforderlich');const token=crypto.randomBytes(32).toString('hex');await pool.query("INSERT INTO ai_connectors(account_id,location_id,name,kind,token_hash) VALUES($1,$2,$3,'api',$4)",[u.id,b.locationId,name,hash(token)]);return {token,message:'API-Schlüssel nur einmal sichtbar. Sicher speichern und Anbindung nach der Rezeptzuordnung aktivieren.'}}
 if(p==='/api/ai/connector-status'&&method==='POST'){checkId(b.id);if(typeof b.active!=='boolean')fail('Status erforderlich');let r;try{r=await pool.query('UPDATE ai_connectors SET active=$3 WHERE id=$1 AND account_id=$2 RETURNING id',[b.id,u.id,b.active])}catch(e){if(e.code==='23505')fail('Diese Kasse hat bereits eine aktive Anbindung');throw e}if(!r.rowCount)fail('Anbindung nicht gefunden');return {ok:true}}
 if(p==='/api/ai/pos-link'&&method==='POST'){
  const owner=(await platformPool.query("SELECT u.id,u.company_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now() AND u.status='active' AND u.role IN ('owner','admin') AND NOT COALESCE(u.must_change_password,false)",[hash(b.posToken||'')])).rows[0];if(!owner){const e=new Error('Gültige Inhaber-Anmeldung der Kasse erforderlich');e.status=403;throw e}
  if(!b.restaurantId)return {restaurants:(await platformPool.query('SELECT id,name FROM restaurants WHERE company_id=$1',[owner.company_id])).rows};
  checkId(b.restaurantId);checkId(b.locationId);if(!(await platformPool.query('SELECT id FROM restaurants WHERE id=$1 AND company_id=$2',[b.restaurantId,owner.company_id])).rowCount)fail('Kassenbetrieb gehört nicht zu deinem Konto');if(!(await pool.query('SELECT id FROM ai_locations WHERE id=$1 AND account_id=$2',[b.locationId,u.id])).rowCount)fail('AI-Standort nicht gefunden');
  const exists=await pool.query("SELECT id FROM ai_connectors WHERE kind='pos' AND pos_restaurant_id=$1 AND active",[b.restaurantId]);if(exists.rowCount)fail('Kassenbetrieb ist bereits aktiv angebunden');
  await pool.query("INSERT INTO ai_connectors(account_id,location_id,name,kind,pos_restaurant_id,pos_user_id,pos_company_id) VALUES($1,$2,$3,'pos',$4,$5,$6)",[u.id,b.locationId,clean(b.name)||'Kassenanbindung',b.restaurantId,owner.id,owner.company_id]);return {ok:true,products:(await platformPool.query('SELECT id,name FROM products WHERE restaurant_id=$1 AND active',[b.restaurantId])).rows};
 }
 if(p==='/api/ai/recipe-events'&&method==='GET')return {events:(await pool.query('SELECT e.*,c.name connector_name FROM ai_sale_events e JOIN ai_connectors c ON c.id=e.connector_id WHERE e.account_id=$1 ORDER BY e.created_at DESC LIMIT 100',[u.id])).rows};
 return null;
}
let running=false;
export async function syncPosSales(){if(running)return;running=true;try{
 const links=(await aiPool().query("SELECT c.* FROM ai_connectors c JOIN ai_accounts a ON a.id=c.account_id WHERE c.kind='pos' AND c.active AND a.status='active'")).rows;
 for(const link of links){try{
  const valid=await platformPool.query("SELECT 1 FROM users u JOIN restaurants r ON r.company_id=u.company_id WHERE u.id=$1 AND r.id=$2 AND u.company_id=$3 AND u.status='active' AND u.role IN ('owner','admin')",[link.pos_user_id,link.pos_restaurant_id,link.pos_company_id]);if(!valid.rowCount)throw Error('Inhaberfreigabe der Kasse nicht mehr gültig');
  const orders=(await platformPool.query("SELECT id,COALESCE(closed_at,created_at) paid_time FROM orders WHERE restaurant_id=$1 AND status='paid' AND (COALESCE(closed_at,created_at)>$2 OR (COALESCE(closed_at,created_at)=$2 AND id>COALESCE($3::uuid,'00000000-0000-0000-0000-000000000000'::uuid))) ORDER BY COALESCE(closed_at,created_at),id LIMIT 200",[link.pos_restaurant_id,link.cursor_time,link.cursor_id])).rows;
  for(const o of orders){const items=(await platformPool.query('SELECT product_id,quantity FROM order_items WHERE order_id=$1',[o.id])).rows;await ingestSale(link,{eventId:'pos:'+o.id,type:'sale',items:items.map(i=>({productCode:String(i.product_id||''),quantity:Number(i.quantity)}))});await aiPool().query('UPDATE ai_connectors SET cursor_time=$2,cursor_id=$3 WHERE id=$1',[link.id,o.paid_time,o.id])}
 }catch(e){await aiPool().query('UPDATE ai_connectors SET last_error=$2 WHERE id=$1',[link.id,clean(e.message)])}}
 }catch(e){console.error('AI sales sync failed:',e.code||e.name)}finally{running=false}}
