import {aiPool} from './ai-database.js';
export const initialTariffs=[{code:'restaurant_premium',name:'AI Premium',role:'restaurant',monthlyCents:4900,unit:'Standort',trialDays:30},{code:'supplier_basic',name:'Lieferanten-Basis',role:'supplier',monthlyCents:5900,unit:'Konto',trialDays:0},{code:'supplier_pro',name:'Lieferanten-Profi',role:'supplier',monthlyCents:9900,unit:'Konto',trialDays:0}];
export async function migrateAiTariffs(){await aiPool().query(`CREATE TABLE IF NOT EXISTS ai_tariffs(code text PRIMARY KEY,name text NOT NULL,role text NOT NULL,monthly_cents int NOT NULL CHECK(monthly_cents>=0),unit text NOT NULL,trial_days int NOT NULL,version int NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT now());`);for(const tariff of initialTariffs)await aiPool().query('INSERT INTO ai_tariffs(code,name,role,monthly_cents,unit,trial_days) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING',[tariff.code,tariff.name,tariff.role,tariff.monthlyCents,tariff.unit,tariff.trialDays]);}
export async function readAiTariffs(){return {currency:'EUR',net:true,supplierCommissionBps:200,plans:(await aiPool().query('SELECT * FROM ai_tariffs ORDER BY monthly_cents,code')).rows};}
export async function tariffSetupStatus(){
 const cfg=(await aiPool().query("SELECT value FROM ai_settings WHERE key='collection'")).rows[0]?.value||{},issuer=cfg.issuer||{};
 const missing=[];if(!process.env.AI_MOLLIE_API_KEY?.startsWith('live_'))missing.push('Separater AI-Mollie-Livezugang');
 if(!['name','address','postalCode','city','taxId','creditorId'].every(key=>typeof issuer[key]==='string'&&issuer[key].trim())||issuer.confirmed!==true||issuer.taxConfirmed!==true||issuer.country!=='DE'||!['standard','small'].includes(issuer.taxMode))missing.push('Geprüfte Rechnungssteller- und Steuerdaten');
 if(!['SMTP_HOST','SMTP_USER','SMTP_PASSWORD','SMTP_FROM'].every(key=>process.env[key]))missing.push('Mailkonfiguration für Rechnungen und Vorankündigungen');
 if(!cfg.enabled)missing.push('Freischaltung der Zahlungsautomatik');
 return {monthlyCollectionEnabled:false,commissionCollectionConfigured:missing.length===0,missing,monthlyStatus:'prepared',message:'Monatstarife sind hinterlegt. Monatlicher Abo-Einzug ist noch nicht aktiviert; Kundenannahme, Mandat und Monatsabrechnung müssen vor der Aktivierung verknüpft werden.'};
}
export async function updateAiTariff(input,actor){const fail=message=>{throw Object.assign(Error(message),{status:400})};if(!initialTariffs.some(plan=>plan.code===input.code)||!Number.isSafeInteger(input.monthlyCents)||input.monthlyCents<0||input.monthlyCents>10000000||!Number.isInteger(input.version)||input.version<1)fail('Gültiger Tarif, Nettopreis und Versionsstand erforderlich');const c=await aiPool().connect();try{await c.query('BEGIN');const previous=(await c.query('SELECT * FROM ai_tariffs WHERE code=$1 FOR UPDATE',[input.code])).rows[0];if(previous.version!==input.version)throw Object.assign(Error('Tarif inzwischen geändert. Bitte neu laden.'),{status:409});await c.query('UPDATE ai_tariffs SET monthly_cents=$2,version=version+1,updated_at=now() WHERE code=$1',[input.code,input.monthlyCents]);await c.query("INSERT INTO ai_audit(actor_id,action,detail) VALUES($1,'tariff_price_changed',$2)",[actor.id,JSON.stringify({code:input.code,before:{monthlyCents:previous.monthly_cents,version:previous.version},after:{monthlyCents:input.monthlyCents,version:previous.version+1}})]);await c.query('COMMIT');return {ok:true}}catch(error){await c.query('ROLLBACK');throw error}finally{c.release()}}
