import test from 'node:test';
import assert from 'node:assert/strict';
import {eurCents,normalizeMolliePayment,verifyAndReleaseMolliePayment} from './center-mollie-payment.js';
const credential={profile_id:'pfl_restaurant',organization_id:'org_restaurant',verified_at:'now'};
const payment={id:'tr_123',profileId:'pfl_restaurant',amount:{value:'12.50',currency:'EUR'},status:'paid',paidAt:'2026-10-06T12:00:00Z',metadata:{bringnessOrderId:'order'}};
test('verified merchant payment is normalized using exact cents',()=>{const p=normalizeMolliePayment(payment,credential);assert.equal(p.amountCents,1250);assert.equal(p.merchantReference,'org_restaurant');assert.equal(p.orderId,'order');});
test('other profile and unverified credentials are rejected',()=>{assert.throws(()=>normalizeMolliePayment({...payment,profileId:'pfl_other'},credential));assert.throws(()=>normalizeMolliePayment(payment,{...credential,verified_at:null}));});
test('malformed or non-EUR amount fails closed',()=>{for(const a of [{value:'12.5',currency:'EUR'},{value:'-1.00',currency:'EUR'},{value:'12.50',currency:'USD'}])assert.throws(()=>eurCents(a));});
test('refund and chargeback are retained for release validation',()=>{const p=normalizeMolliePayment({...payment,amountRefunded:{value:'1.00',currency:'EUR'},amountChargedBack:{value:'0.50',currency:'EUR'}},credential);assert.equal(p.refundedCents,100);assert.equal(p.chargedBackCents,50);});
test('unknown payment never accesses merchant API',async()=>assert.equal((await verifyAndReleaseMolliePayment({query:async()=>({rows:[]})},'tr_unknown',{},()=>{throw Error('no provider access')})).reason,'unknown_payment'));
