import {test} from 'node:test';import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {createDisplays,validateDisplay} from './displays.js';
const rid='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222';
async function request(pool,url,{method='GET',headers={},body=''}={}){const req=Readable.from(body?[Buffer.from(body)]:[]);Object.assign(req,{url,method,headers});const res={writeHead(status){this.status=status},end(body){this.body=body}};await createDisplays(pool)(req,res);return {status:res.status,body:JSON.parse(res.body)}}
test('reject malformed content, durations and orientations',()=>{const base={name:'Theke',orientation:'landscape',fit:'contain',playlist:[{type:'menu',seconds:12}]};assert.equal(validateDisplay(base).name,'Theke');for(const patch of [{orientation:'sideways'},{playlist:[{type:'video',seconds:0,mediaId:id}]},{playlist:[{type:'html',seconds:12}]}])assert.throws(()=>validateDisplay({...base,...patch}));});
test('administration rejects absent session and locked PIN',async()=>{let r=await request({query:async()=>({rows:[],rowCount:0})},'/api/v1/displays?restaurantId='+rid);assert.equal(r.status,401);r=await request({query:async()=>({rows:[{id,role:'owner'}],rowCount:1})},'/api/v1/displays?restaurantId='+rid,{headers:{authorization:'Bearer abc'}});assert.equal(r.status,403)});
test('restaurant outside company is unavailable',async()=>{let i=0;const p={query:async()=>++i===1?{rows:[{id,role:'owner',company_id:id,token_hash:'a'}],rowCount:1}:i===2?{rows:[],rowCount:1}:{rows:[],rowCount:0}};const r=await request(p,'/api/v1/displays?restaurantId='+rid,{headers:{authorization:'Bearer abc','x-personnel-unlock':'unlock'}});assert.equal(r.status,404)});
test('display token never grants unassigned media',async()=>{const p={query:async()=>({rows:[{restaurant_id:rid,playlist:[]}],rowCount:1})};const r=await request(p,'/api/v1/display-player/'+'a'.repeat(48)+'/media/'+id);assert.equal(r.status,404)});
test('public display response exposes only display content and live menu',async()=>{let i=0;const p={query:async()=>({rows:++i===1?[{restaurant_id:rid,token:'secret',name:'Theke',restaurant_name:'Cafe',orientation:'portrait',fit:'contain',playlist:[],updated_at:'now'}]:[{name:'Kaffee',price_cents:250}],rowCount:1})};const r=await request(p,'/api/v1/display-player/'+'a'.repeat(48));assert.equal(r.status,200);assert.equal(r.body.products[0].price_cents,250);assert.equal(r.body.orientation,'portrait');assert.equal(r.body.token,undefined);assert.equal(r.body.restaurant_id,undefined)});
test('video byte ranges serve Safari partial reads without exposing other assets',async()=>{let i=0;const pool={query:async()=>({rows:++i%2===1?[{restaurant_id:rid,playlist:[{mediaId:id}]}]:[{mime:'video/mp4',content:Buffer.from('abcdefghij')}],rowCount:1})};const req=Readable.from([]);Object.assign(req,{url:'/api/v1/display-player/'+'a'.repeat(48)+'/media/'+id,method:'GET',headers:{range:'bytes=2-5'}});const res={writeHead(status,headers){this.status=status;this.headers=headers},end(body){this.body=body}};await createDisplays(pool)(req,res);assert.equal(res.status,206);assert.equal(res.headers['content-range'],'bytes 2-5/10');assert.equal(res.body.toString(),'cdef')});

test('category selection is retained, deduplicated and validated',()=>{const base={name:'Getränke',orientation:'landscape',fit:'contain',playlist:[{type:'menu',seconds:12,categoryIds:[rid,rid]}]};assert.deepEqual(validateDisplay(base).playlist[0].categoryIds,[rid]);for(const categoryIds of ['all',['invalid'],Array(101).fill(rid)])assert.throws(()=>validateDisplay({...base,playlist:[{type:'menu',seconds:12,categoryIds}]}));assert.equal(validateDisplay({...base,playlist:[{type:'menu',seconds:12,categoryIds:[]}]}).playlist[0].categoryIds,undefined)});
test('categories from another restaurant cannot be assigned',async()=>{const pool={query:async sql=>sql.includes('FROM sessions')?{rows:[{id,role:'owner',company_id:id,token_hash:'a'}],rowCount:1}:sql.includes('personnel_unlocks')||sql.includes('FROM restaurants')?{rows:[{id:rid}],rowCount:1}:{rows:[],rowCount:0}};pool.connect=async()=>({query:pool.query,release(){}});const r=await request(pool,'/api/v1/displays?restaurantId='+rid,{method:'POST',headers:{authorization:'Bearer abc','x-personnel-unlock':'unlock'},body:JSON.stringify({name:'Theke',orientation:'portrait',fit:'contain',playlist:[{type:'menu',seconds:12,categoryIds:[id]}]})});assert.equal(r.status,400);assert.match(r.body.error,/Kategorie/)});
