import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('../apps/web/public/tisch/app.js',import.meta.url),'utf8');
test('menu groups products into collapsed categories',()=>{const c=vm.createContext({esc:s=>String(s).replaceAll('<','&lt;'),euro:String,productVisual:()=>''});vm.runInContext(source.slice(source.indexOf('function renderGuestMenu('),source.indexOf('function createGuestRequestId(')),c);const html=c.renderGuestMenu([{id:'1',name:'Pizza',category:'Speisen',price_cents:100},{id:'2',name:'Wasser',category:'Getränke',price_cents:200}]);assert.equal((html.match(/<details/g)||[]).length,2);assert.doesNotMatch(html,/<details[^>]* open/);assert.match(html,/Speisen/);assert.match(html,/Getränke/)});
function setup(){let calls=0,release;const nodes={send:{disabled:false},status:{textContent:''}},events=[];const c=vm.createContext({orderSending:false,orderLocked:false,cart:new Map([['product',1]]),notes:new Map(),pendingRequestId:null,code:'table',crypto:{randomUUID:()=> 'request-id'},$:id=>nodes[id],lockGuestOrder:()=>events.push('locked'),window:{dispatchEvent(){}},CustomEvent:class{},fetch:async()=>{calls++;await new Promise(r=>release=r);return {ok:true,json:async()=>({orderId:'order'})}}});vm.runInContext(source.slice(source.indexOf('async function sendGuestOrder('),source.indexOf(';$("send").onclick=sendGuestOrder')),c);vm.runInContext(source.slice(source.indexOf('function createGuestRequestId(')),c);return {c,nodes,events,calls:()=>calls,release:()=>release()}}
test('first activation transmits and a following click cannot duplicate it',async()=>{const f=setup();const pending=f.c.sendGuestOrder();assert.equal(f.calls(),1);assert.equal(f.nodes.send.disabled,true);await f.c.sendGuestOrder();assert.equal(f.calls(),1);f.release();await pending;assert.deepEqual(f.events,['locked'])});
test('request-id errors are shown and release the send lock',async()=>{const f=setup();f.c.crypto.randomUUID=()=>{throw Error('Request-id failed')};await f.c.sendGuestOrder();assert.equal(f.nodes.status.textContent,'Request-id failed');assert.equal(f.nodes.send.disabled,false);assert.equal(f.c.orderSending,false);assert.equal(f.calls(),0)});
