import http from "node:http";import fs from "node:fs";import path from "node:path";import crypto from "node:crypto";import {fileURLToPath} from "node:url";import pg from "pg";
const {Pool}=pg, pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:false});
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../apps/web/public"),port=process.env.PORT||3000;
const type={".html":"text/html; charset=utf-8",".css":"text/css",".js":"text/javascript",".json":"application/json",".png":"image/png",".svg":"image/svg+xml"};
const json=(res,n,data)=>{res.writeHead(n,{"content-type":"application/json","cache-control":"no-store"});res.end(JSON.stringify(data))}, body=req=>new Promise((ok,bad)=>{let d="";req.on("data",c=>d+=c);req.on("end",()=>{try{ok(d?JSON.parse(d):{})}catch(e){bad(e)}})});
const hash=p=>crypto.scryptSync(p,process.env.PASSWORD_PEPPER||"bringness-pos",64).toString("hex"), token=req=>(req.headers.authorization||"").replace(/^Bearer /,"");
async function init(){await pool.query(`CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS companies(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,email text NOT NULL UNIQUE,password_hash text NOT NULL,display_name text NOT NULL,status text DEFAULT 'active',created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions(token_hash text PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS restaurants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,name text NOT NULL,mode text DEFAULT 'counter',created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS categories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),restaurant_id uuid NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,name text NOT NULL,sort_order int DEFAULT 0,active boolean DEFAULT true);
CREATE TABLE IF NOT EXISTS products(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),restaurant_id uuid NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,category_id uuid REFERENCES categories(id) ON DELETE SET NULL,name text NOT NULL,description text,price_cents int NOT NULL,tax_rate numeric(5,2) NOT NULL,image_url text,active boolean DEFAULT true,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),restaurant_id uuid NOT NULL REFERENCES restaurants(id) ON DELETE RESTRICT,source text DEFAULT 'pos',status text DEFAULT 'paid',total_cents int DEFAULT 0,created_at timestamptz DEFAULT now(),closed_at timestamptz);
CREATE TABLE IF NOT EXISTS order_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,product_id uuid REFERENCES products(id) ON DELETE SET NULL,product_name_snapshot text NOT NULL,unit_price_cents int NOT NULL,tax_rate_snapshot numeric(5,2) NOT NULL,quantity numeric(10,3) DEFAULT 1);
CREATE TABLE IF NOT EXISTS payments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,method text NOT NULL,amount_cents int NOT NULL,created_at timestamptz DEFAULT now());`)}
async function currentUser(req){const t=token(req);if(!t)return null;const th=crypto.createHash("sha256").update(t).digest("hex"),q=await pool.query("SELECT u.id,u.company_id,u.email,u.display_name FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now()",[th]);return q.rows[0]||null}
async function auth(req,res){const u=await currentUser(req);if(!u)json(res,401,{error:"Nicht angemeldet"});return u}
async function session(userId){const t=crypto.randomBytes(32).toString("hex"),th=crypto.createHash("sha256").update(t).digest("hex");await pool.query("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,now()+interval '30 days')",[th,userId]);return t}
function routeFile(url){let p=url.split("?")[0];if(p==="/")p="/index.html";if(p==="/datenschutz")p="/datenschutz/index.html";if(p==="/impressum")p="/impressum/index.html";if(p==="/ueber-uns")p="/ueber-uns/index.html";if(p==="/pos"||p==="/pos/")p="/pos/index.html";return path.join(root,p)}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,"http://local"),p=u.pathname;try{
if(p==="/health"){await pool.query("SELECT 1");return json(res,200,{status:"ok",service:"bringness-pos",version:"0.4.0",database:"ok"})}
if(p==="/api/v1/auth/register"&&req.method==="POST"){const b=await body(req),email=String(b.email||"").trim().toLowerCase();if(!b.name||!email||String(b.password||"").length<6)return json(res,400,{error:"Name, E-Mail und Passwort (mind. 6 Zeichen) erforderlich"});const c=await pool.connect();try{await c.query("BEGIN");const co=(await c.query("INSERT INTO companies(name) VALUES($1) RETURNING id",[b.name])).rows[0],x=(await c.query("INSERT INTO users(company_id,email,password_hash,display_name) VALUES($1,$2,$3,$4) RETURNING id,email,display_name",[co.id,email,hash(b.password),b.name])).rows[0];await c.query("COMMIT");const t=await session(x.id);return json(res,201,{token:t,user:{id:x.id,name:x.display_name,email:x.email}})}catch(e){await c.query("ROLLBACK");if(e.code==="23505")return json(res,409,{error:"E-Mail bereits vorhanden"});throw e}finally{c.release()}}
if(p==="/api/v1/auth/login"&&req.method==="POST"){const b=await body(req),q=await pool.query("SELECT id,email,display_name FROM users WHERE email=$1 AND password_hash=$2 AND status='active'",[String(b.email||"").trim().toLowerCase(),hash(String(b.password||""))]);if(!q.rows[0])return json(res,401,{error:"Anmeldedaten stimmen nicht"});const x=q.rows[0],t=await session(x.id);return json(res,200,{token:t,user:{id:x.id,name:x.display_name,email:x.email}})}
if(p==="/api/v1/bootstrap"&&req.method==="GET"){const x=await auth(req,res);if(!x)return;const [r,c,pr,o]=await Promise.all([pool.query("SELECT id,name,mode FROM restaurants WHERE company_id=$1 ORDER BY created_at",[x.company_id]),pool.query("SELECT c.id,c.restaurant_id,c.name FROM categories c JOIN restaurants r ON r.id=c.restaurant_id WHERE r.company_id=$1 AND c.active=true ORDER BY c.sort_order,c.name",[x.company_id]),pool.query("SELECT p.id,p.restaurant_id,p.category_id,p.name,p.price_cents,p.tax_rate,p.image_url FROM products p JOIN restaurants r ON r.id=p.restaurant_id WHERE r.company_id=$1 AND p.active=true ORDER BY p.name",[x.company_id]),pool.query("SELECT o.id,o.restaurant_id,o.total_cents,o.status,o.created_at FROM orders o JOIN restaurants r ON r.id=o.restaurant_id WHERE r.company_id=$1 ORDER BY o.created_at DESC LIMIT 100",[x.company_id])]);return json(res,200,{user:{id:x.id,name:x.display_name,email:x.email},restaurants:r.rows.map(z=>({id:z.id,name:z.name,mode:z.mode})),categories:c.rows.map(z=>({id:z.id,restaurantId:z.restaurant_id,name:z.name})),products:pr.rows.map(z=>({id:z.id,restaurantId:z.restaurant_id,categoryId:z.category_id,name:z.name,price:z.price_cents/100,tax:Number(z.tax_rate),emoji:z.image_url||"🍽️"})),orders:o.rows.map(z=>({id:z.id,restaurantId:z.restaurant_id,total:z.total_cents/100,status:z.status,createdAt:z.created_at}))})}
if(p==="/api/v1/restaurants"&&req.method==="POST"){const x=await auth(req,res);if(!x)return;const b=await body(req),q=await pool.query("INSERT INTO restaurants(company_id,name,mode) VALUES($1,$2,$3) RETURNING id,name,mode",[x.company_id,String(b.name||"Mein Betrieb").trim(),b.mode||"counter"]);return json(res,201,q.rows[0])}
if(p==="/api/v1/categories"&&req.method==="POST"){const x=await auth(req,res);if(!x)return;const b=await body(req),q=await pool.query("INSERT INTO categories(restaurant_id,name) SELECT id,$2 FROM restaurants WHERE id=$1 AND company_id=$3 RETURNING id,restaurant_id,name",[b.restaurantId,String(b.name||"Neue Kategorie").trim(),x.company_id]);if(!q.rows[0])return json(res,403,{error:"Betrieb nicht erlaubt"});return json(res,201,{id:q.rows[0].id,restaurantId:q.rows[0].restaurant_id,name:q.rows[0].name})}
if(p==="/api/v1/products"&&req.method==="POST"){const x=await auth(req,res);if(!x)return;const b=await body(req),q=await pool.query("INSERT INTO products(restaurant_id,category_id,name,price_cents,tax_rate,image_url) SELECT r.id,$2,$3,$4,$5,$6 FROM restaurants r WHERE r.id=$1 AND r.company_id=$7 RETURNING id,restaurant_id,category_id,name,price_cents,tax_rate,image_url",[b.restaurantId,b.categoryId||null,String(b.name||"Produkt").trim(),Math.round(Number(b.price||0)*100),Number(b.tax)||19,b.emoji||"🍽️",x.company_id]);if(!q.rows[0])return json(res,403,{error:"Betrieb nicht erlaubt"});const z=q.rows[0];return json(res,201,{id:z.id,restaurantId:z.restaurant_id,categoryId:z.category_id,name:z.name,price:z.price_cents/100,tax:Number(z.tax_rate),emoji:z.image_url})}
if(p==="/api/v1/orders"&&req.method==="POST"){const x=await auth(req,res);if(!x)return;const b=await body(req),check=await pool.query("SELECT 1 FROM restaurants WHERE id=$1 AND company_id=$2",[b.restaurantId,x.company_id]);if(!check.rows[0])return json(res,403,{error:"Betrieb nicht erlaubt"});const c=await pool.connect();try{await c.query("BEGIN");const total=Math.round(Number(b.total||0)*100),o=(await c.query("INSERT INTO orders(restaurant_id,status,total_cents,closed_at) VALUES($1,'paid',$2,now()) RETURNING id,created_at",[b.restaurantId,total])).rows[0];for(const i of b.items||[])await c.query("INSERT INTO order_items(order_id,product_id,product_name_snapshot,unit_price_cents,tax_rate_snapshot,quantity) VALUES($1,$2,$3,$4,$5,$6)",[o.id,i.productId||null,i.name,Math.round(Number(i.price)*100),Number(i.tax)||19,Number(i.qty)||1]);await c.query("INSERT INTO payments(order_id,method,amount_cents) VALUES($1,'cash',$2)",[o.id,total]);await c.query("COMMIT");return json(res,201,{id:o.id,restaurantId:b.restaurantId,total:total/100,status:"paid",createdAt:o.created_at})}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
if(p.startsWith("/api/"))return json(res,404,{error:"Route nicht gefunden"});const f=routeFile(req.url);if(!f.startsWith(root)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end("Not found")}res.writeHead(200,{"content-type":type[path.extname(f)]||"application/octet-stream","x-content-type-options":"nosniff","referrer-policy":"strict-origin-when-cross-origin","x-frame-options":"SAMEORIGIN"});fs.createReadStream(f).pipe(res)}catch(e){console.error(e);json(res,500,{error:"Serverfehler"})}});
init().then(()=>server.listen(port,()=>console.log("Bringness POS + PostgreSQL listening on",port))).catch(e=>{console.error("DB init failed",e);process.exit(1)});