import crypto from 'node:crypto';
const digest=s=>crypto.createHash('sha256').update(s).digest('hex');
const legacyHash=s=>crypto.scryptSync(s,process.env.PASSWORD_PEPPER||'bringness-pos',64).toString('hex');
export const pinHash=pin=>{const salt=crypto.randomBytes(16).toString('hex');return salt+':'+crypto.scryptSync(pin,salt,64).toString('hex')};
export function pinMatches(pin,stored){if(!stored)return false;const [salt,value]=stored.split(':');const expected=value?crypto.scryptSync(pin,salt,64).toString('hex'):legacyHash(pin),actual=value||salt;return actual.length===expected.length&&crypto.timingSafeEqual(Buffer.from(actual),Buffer.from(expected))}
const uuid=s=>/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(String(s||''));
const send=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(data));return true};
async function body(req){let text='';for await(const chunk of req){text+=chunk;if(text.length>20000)throw Object.assign(Error('Anfrage zu groß'),{status:413})}try{return JSON.parse(text||'{}')}catch{throw Object.assign(Error('Ungültige Anfrage'),{status:400})}}
const fail=(text,status=400)=>{throw Object.assign(Error(text),{status})};
export function nextClockState(state,action){const next={off:{start:'working'},working:{pause:'paused',end:'off'},paused:{resume:'working',end:'off'}}[state]?.[action];if(!next)fail('Diese Buchung passt nicht zum aktuellen Status.',409);return next}
export async function migratePersonnel(pool){await pool.query(`
CREATE TABLE IF NOT EXISTS personnel_admin_pins(user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,pin_hash text NOT NULL);
CREATE TABLE IF NOT EXISTS personnel_unlocks(token_hash text PRIMARY KEY,session_hash text NOT NULL REFERENCES sessions(token_hash) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS personnel_attempts(key text PRIMARY KEY,count int NOT NULL,until_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS personnel_time_entries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),employee_id uuid NOT NULL REFERENCES employees(id),restaurant_id uuid NOT NULL REFERENCES restaurants(id),action text NOT NULL CHECK(action IN ('start','pause','resume','end')),recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),effective_at timestamptz NOT NULL DEFAULT clock_timestamp(),request_id uuid NOT NULL UNIQUE,corrected_by uuid REFERENCES users(id),correction_reason text);
CREATE INDEX IF NOT EXISTS personnel_time_employee_idx ON personnel_time_entries(employee_id,recorded_at,id);
`)}
export function createPersonnel(pool){
 async function actor(req){const raw=String(req.headers.authorization||'').replace(/^Bearer /,'');if(!raw)return null;return (await pool.query("SELECT u.id,u.company_id,u.role,u.password_hash,s.token_hash session_hash FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now() AND u.status='active' AND NOT coalesce(u.must_change_password,false)",[digest(raw)])).rows[0]||null}
 async function unlock(req,u){if(!['owner','admin'].includes(u.role))return false;const raw=String(req.headers['x-personnel-unlock']||'');if(!raw)return false;return !!(await pool.query("UPDATE personnel_unlocks SET expires_at=now()+interval '3 minutes' WHERE token_hash=$1 AND session_hash=$2 AND user_id=$3 AND expires_at>now() RETURNING token_hash",[digest(raw),u.session_hash,u.id])).rowCount}
 async function audit(c,u,type,id,payload){await c.query('INSERT INTO audit_log(company_id,actor_user_id,event_type,entity_type,entity_id,payload) VALUES($1,$2,$3,$4,$5,$6)',[u.company_id,u.id,type,'personnel',id,JSON.stringify(payload)])}
 async function attempt(key){const q=await pool.query("INSERT INTO personnel_attempts VALUES($1,1,now()+interval '15 minutes') ON CONFLICT(key) DO UPDATE SET count=CASE WHEN personnel_attempts.until_at<now() THEN 1 ELSE personnel_attempts.count+1 END,until_at=CASE WHEN personnel_attempts.until_at<now() THEN now()+interval '15 minutes' ELSE personnel_attempts.until_at END RETURNING count",[key]);if(q.rows[0].count>5)fail('Zu viele PIN-Versuche. Bitte in 15 Minuten erneut versuchen.',429)}
 async function allowedRestaurant(rid,u,c=pool){if(!uuid(rid)||!(await c.query('SELECT id FROM restaurants WHERE id=$1 AND company_id=$2',[rid,u.company_id])).rowCount)fail('Betrieb nicht gefunden',404)}
 const sensitive=(p,m)=>p.startsWith('/api/v1/owner/')||p.startsWith('/api/v1/waiters')||p==='/api/v1/employees'||/^\/api\/v1\/restaurants\/[^/]+\/(branding|mode|qr-service)$/.test(p)||p==='/api/v1/billing/profile'&&m!=='GET';
 return async function handle(req,res){const url=new URL(req.url,'http://local'),p=url.pathname,base='/api/v1/personnel',own=p.startsWith(base+'/');if(!own&&!sensitive(p,req.method))return false;
 try{const u=await actor(req);if(!u)return send(res,401,{error:'Nicht angemeldet'});
 if(!own){if(!await unlock(req,u))return send(res,403,{error:'Verwaltungs-PIN erforderlich',code:'PERSONNEL_LOCKED'});return false}
 const route=p.slice(base.length),b=req.method==='GET'?Object.fromEntries(url.searchParams):await body(req);
 if(route==='/access'&&req.method==='GET'){const configured=!!(await pool.query('SELECT user_id FROM personnel_admin_pins WHERE user_id=$1',[u.id])).rowCount;return send(res,200,{configured,canManage:['owner','admin'].includes(u.role)})}
 if(route==='/lock'&&req.method==='POST'){await pool.query('DELETE FROM personnel_unlocks WHERE session_hash=$1',[u.session_hash]);return send(res,200,{ok:true})}
 if((route==='/setup'||route==='/unlock')&&req.method==='POST'){
  if(!['owner','admin'].includes(u.role))fail('Keine Verwaltungsberechtigung',403);const key='admin:'+u.id;await attempt(key);
  if(route==='/setup'){if(!/^\d{6,8}$/.test(String(b.pin||'')))fail('Die Verwaltungs-PIN muss 6 bis 8 Ziffern enthalten.');if(!pinMatches(String(b.password||''),u.password_hash))fail('Kontokennwort stimmt nicht',403);await pool.query('INSERT INTO personnel_admin_pins VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET pin_hash=excluded.pin_hash',[u.id,pinHash(String(b.pin))]);await pool.query('DELETE FROM personnel_unlocks WHERE user_id=$1',[u.id]);await audit(pool,u,'personnel.pin.changed',u.id,{})}
  else{const stored=(await pool.query('SELECT pin_hash FROM personnel_admin_pins WHERE user_id=$1',[u.id])).rows[0];if(!pinMatches(String(b.pin||''),stored?.pin_hash))fail('PIN stimmt nicht',403)}
  await pool.query('DELETE FROM personnel_attempts WHERE key=$1',[key]);const raw=crypto.randomBytes(32).toString('hex');await pool.query("INSERT INTO personnel_unlocks VALUES($1,$2,$3,now()+interval '3 minutes')",[digest(raw),u.session_hash,u.id]);return send(res,200,{unlockToken:raw})
 }
 if(route==='/people'&&req.method==='GET'){await allowedRestaurant(b.restaurantId,u);return send(res,200,{people:(await pool.query('SELECT id,display_name FROM employees WHERE restaurant_id=$1 AND active=true ORDER BY display_name',[b.restaurantId])).rows})}
 if(route==='/clock'&&req.method==='POST'){
  await allowedRestaurant(b.restaurantId,u);if(!uuid(b.employeeId))fail('Mitarbeiter wählen');const key='employee:'+b.employeeId;await attempt(key);
  const c=await pool.connect();try{await c.query('BEGIN');const e=(await c.query('SELECT id,pin_hash FROM employees WHERE id=$1 AND restaurant_id=$2 AND active=true FOR UPDATE',[b.employeeId,b.restaurantId])).rows[0];if(!e||!pinMatches(String(b.pin||''),e.pin_hash))fail('PIN oder Mitarbeiter stimmt nicht',403);await pool.query('DELETE FROM personnel_attempts WHERE key=$1',[key]);
   const latest=(await c.query('SELECT action,effective_at FROM personnel_time_entries WHERE employee_id=$1 ORDER BY recorded_at DESC,id DESC LIMIT 1',[e.id])).rows[0];let state=latest?({start:'working',resume:'working',pause:'paused',end:'off'}[latest.action]):'off';
   if(b.action){if(!uuid(b.requestId))fail('Buchungskennung erforderlich');const prior=(await c.query('SELECT employee_id,action FROM personnel_time_entries WHERE request_id=$1',[b.requestId])).rows[0];if(prior){if(prior.employee_id!==e.id||prior.action!==b.action)fail('Buchungskennung bereits verwendet',409)}else{state=nextClockState(state,b.action);const entry=(await c.query('INSERT INTO personnel_time_entries(employee_id,restaurant_id,action,request_id) VALUES($1,$2,$3,$4) RETURNING id',[e.id,b.restaurantId,b.action,b.requestId])).rows[0];await audit(c,u,'personnel.clock',entry.id,{employeeId:e.id,action:b.action})}}
   await c.query('COMMIT');return send(res,200,{state,confirmed:!!b.action})
  }catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}
 }
 if(!await unlock(req,u))fail('Verwaltungs-PIN erforderlich',403);
 if(route==='/touch'&&req.method==='POST')return send(res,200,{ok:true});
 await allowedRestaurant(b.restaurantId,u);
 if(route==='/employees'&&req.method==='GET')return send(res,200,{employees:(await pool.query('SELECT id,display_name,role,active,(pin_hash IS NOT NULL) pin_configured FROM employees WHERE restaurant_id=$1 ORDER BY display_name',[b.restaurantId])).rows});
 if(route==='/employees'&&req.method==='POST'){const name=String(b.name||'').trim(),role=String(b.role||'cashier');if(name.length<2||name.length>100||!['cashier','kitchen','manager','waiter'].includes(role)||!/^\d{6,8}$/.test(String(b.pin||'')))fail('Name, Rolle und persönliche PIN mit 6 bis 8 Ziffern erforderlich');const e=(await pool.query('INSERT INTO employees(restaurant_id,display_name,role,pin_hash) VALUES($1,$2,$3,$4) RETURNING id',[b.restaurantId,name,role,pinHash(String(b.pin))])).rows[0];await audit(pool,u,'personnel.employee.created',e.id,{name,role});return send(res,201,{id:e.id})}
 if(route==='/pin'&&req.method==='POST'){if(!uuid(b.employeeId)||!/^\d{6,8}$/.test(String(b.pin||'')))fail('PIN mit 6 bis 8 Ziffern erforderlich');const q=await pool.query('UPDATE employees SET pin_hash=$1 WHERE id=$2 AND restaurant_id=$3 RETURNING id',[pinHash(String(b.pin)),b.employeeId,b.restaurantId]);if(!q.rowCount)fail('Mitarbeiter nicht gefunden',404);await audit(pool,u,'personnel.employee.pin',b.employeeId,{});return send(res,200,{ok:true})}
 if(route==='/schedules'&&req.method==='GET')return send(res,200,{schedules:(await pool.query('SELECT employee_id,starts_at,ends_at FROM waiter_schedules WHERE restaurant_id=$1 AND ends_at>now()-interval \'90 days\' AND ends_at<=now()',[b.restaurantId])).rows});
 if(route==='/entries'&&req.method==='GET'){const entries=(await pool.query('SELECT t.id,t.employee_id,e.display_name,t.action,t.recorded_at,t.effective_at,t.correction_reason FROM personnel_time_entries t JOIN employees e ON e.id=t.employee_id WHERE t.restaurant_id=$1 AND (t.effective_at>now()-interval \'90 days\' OR t.id IN (SELECT DISTINCT ON(employee_id) id FROM personnel_time_entries WHERE restaurant_id=$1 ORDER BY employee_id,recorded_at DESC,id DESC)) ORDER BY t.recorded_at,t.id',[b.restaurantId])).rows;return send(res,200,{entries})}
 if(route==='/correct'&&req.method==='POST'){if(!uuid(b.entryId)||String(b.reason||'').trim().length<3||String(b.reason||'').length>300||!Number.isFinite(Date.parse(b.effectiveAt))||Date.parse(b.effectiveAt)>Date.now())fail('Zeitpunkt und Korrekturgrund erforderlich');const c=await pool.connect();try{await c.query('BEGIN');const prior=(await c.query('SELECT * FROM personnel_time_entries WHERE id=$1 AND restaurant_id=$2',[b.entryId,b.restaurantId])).rows[0];if(!prior)fail('Buchung nicht gefunden',404);await c.query('SELECT id FROM employees WHERE id=$1 FOR UPDATE',[prior.employee_id]);const all=(await c.query('SELECT id,effective_at FROM personnel_time_entries WHERE employee_id=$1 ORDER BY recorded_at,id',[prior.employee_id])).rows;const at=all.findIndex(x=>x.id===prior.id),next=Date.parse(b.effectiveAt);if(at>0&&next<=Date.parse(all[at-1].effective_at)||at<all.length-1&&next>=Date.parse(all[at+1].effective_at))fail('Korrektur muss zwischen den benachbarten Buchungen liegen');await c.query('UPDATE personnel_time_entries SET effective_at=$1,corrected_by=$2,correction_reason=$3 WHERE id=$4',[b.effectiveAt,u.id,b.reason.trim(),prior.id]);await audit(c,u,'personnel.time.corrected',prior.id,{previous:prior.effective_at,next:b.effectiveAt,reason:b.reason.trim()});await c.query('COMMIT');return send(res,200,{ok:true})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 return send(res,404,{error:'Personal-Funktion nicht gefunden'});
 }catch(e){if(e.status)return send(res,e.status,{error:e.message});throw e}
 }
}
