import {systemActor} from './system-access.js';
import {createMailProbe} from './ai-mail-health.js';
import crypto from 'node:crypto';
import {connectSmtp} from './smtp-mail.js';
export const cleanMailAddress=value=>{const email=String(value||'').trim().toLowerCase();if(email.length>254||! /^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(email))throw Object.assign(Error('Gültige E-Mail-Adresse erforderlich'),{status:400});return email};
const key=()=>crypto.createHash('sha256').update(process.env.PASSWORD_PEPPER||process.env.DATABASE_URL||'bringness-development-mail').digest();
function seal(value){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key(),iv);return Buffer.concat([iv,cipher.update(JSON.stringify(value)),cipher.final(),cipher.getAuthTag()]).toString('base64')}
function open(value){const b=Buffer.from(value,'base64'),cipher=crypto.createDecipheriv('aes-256-gcm',key(),b.subarray(0,12));cipher.setAuthTag(b.subarray(-16));return JSON.parse(Buffer.concat([cipher.update(b.subarray(12,-16)),cipher.final()]).toString())}
export async function migrateTransactionalMail(pool){await pool.query(`CREATE TABLE IF NOT EXISTS transactional_mail(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),dedupe_key text NOT NULL UNIQUE,recipient text NOT NULL,payload text NOT NULL,status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','sending','sent','review','failed')),attempts int NOT NULL DEFAULT 0,next_attempt_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now(),sent_at timestamptz,last_error text);CREATE INDEX IF NOT EXISTS transactional_mail_due_idx ON transactional_mail(next_attempt_at) WHERE status='pending';`)}
export async function enqueueMail(c,dedupe,to,message){await c.query('INSERT INTO transactional_mail(dedupe_key,recipient,payload) VALUES($1,$2,$3) ON CONFLICT(dedupe_key) DO NOTHING',[dedupe,cleanMailAddress(to),seal(message)])}
export async function enqueuePaidReceipt(c,orderId,email){if(!email)return;const q=await c.query(`SELECT rc.id,rc.receipt_number FROM receipts rc JOIN orders o ON o.id=rc.order_id WHERE o.id=$1 AND (o.status='paid' OR EXISTS(SELECT 1 FROM center_order_payments cp WHERE cp.order_id=o.id AND cp.released_at IS NOT NULL)) AND (SELECT coalesce(sum(amount_cents),0) FROM payments WHERE order_id=o.id)=o.total_cents`,[orderId]);if(!q.rows[0])throw Error('PAID_RECEIPT_REQUIRED');await enqueueMail(c,'receipt:'+q.rows[0].id,email,{kind:'receipt',receiptId:q.rows[0].id,subject:'Bringness – Beleg '+q.rows[0].receipt_number})}
export async function queueRequestedReceipts(pool){const q=await pool.query(`SELECT o.id,o.guest_email FROM receipts rc JOIN orders o ON o.id=rc.order_id WHERE o.guest_email IS NOT NULL AND (o.status='paid' OR EXISTS(SELECT 1 FROM center_order_payments cp WHERE cp.order_id=o.id AND cp.released_at IS NOT NULL)) AND (SELECT coalesce(sum(amount_cents),0) FROM payments WHERE order_id=o.id)=o.total_cents AND NOT EXISTS(SELECT 1 FROM transactional_mail m WHERE m.dedupe_key='receipt:'||rc.id::text) ORDER BY rc.issued_at LIMIT 25`);for(const row of q.rows){try{await enqueuePaidReceipt(pool,row.id,cleanMailAddress(row.guest_email));}catch(e){if(e.status!==400)throw e;}}}
export function createMailStatus(pool){const probe=createMailProbe();return async(req,res)=>{const path=new URL(req.url,'http://local').pathname;if(path==='/api/v1/mail/availability'&&req.method==='GET'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(await probe()));return true;}if(path!=='/api/v1/platform/mail/status')return false;if(!await systemActor(pool,req,res))return true;if(req.method!=='GET'){res.writeHead(405);res.end();return true;}const smtp=await probe();const counts=(await pool.query('SELECT status,count(*)::int count FROM transactional_mail GROUP BY status')).rows;res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify({smtp,queue:counts}));return true;}}
export function createMailWorker(pool,{connect=connectSmtp,renderReceipt,env=process.env}={}){let running=false;return async()=>{if(running)return;running=true;try{if(!['SMTP_HOST','SMTP_USER','SMTP_PASSWORD','SMTP_FROM'].every(k=>env[k]))return;
 await queueRequestedReceipts(pool);
 // An interrupted submission is ambiguous: never automatically send it again.
 await pool.query("UPDATE transactional_mail SET status='review',last_error='submission_interrupted' WHERE status='sending' AND next_attempt_at<now()-interval '15 minutes'");
 for(let i=0;i<10;i++){const row=(await pool.query(`UPDATE transactional_mail SET status='sending',attempts=attempts+1,next_attempt_at=now() WHERE id=(SELECT id FROM transactional_mail WHERE status='pending' AND next_attempt_at<=now() ORDER BY created_at LIMIT 1 FOR UPDATE SKIP LOCKED) RETURNING *`)).rows[0];if(!row)break;let transport,submitted=false;try{const message=open(row.payload);if(message.expiresAt&&Date.parse(message.expiresAt)<=Date.now()){await pool.query("UPDATE transactional_mail SET status='failed',last_error='invitation_expired',payload='' WHERE id=$1",[row.id]);continue;}let attachments,html,text=message.text;if(message.kind==='receipt'){const r=await renderReceipt(message.receiptId);attachments=[{filename:r.filename,content:r.pdf}];text=`Guten Tag,\n\nvielen Dank für Ihren Besuch bei ${r.restaurantName||'uns'}! Schön, dass Sie bei uns waren.\n\nIhren bezahlten Beleg finden Sie als PDF im Anhang.\n\nWir freuen uns auf Ihren nächsten Besuch!\n\nHerzliche Grüße\nIhr Team von ${r.restaurantName||'Ihrem Restaurant'}`;
 const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 html='<div lang="de" style="font-family:Arial,sans-serif;font-size:16px;line-height:1.6;color:#243746;max-width:600px;margin:0 auto">'+text.split('\n\n').map(p=>'<p style="margin:0 0 20px">'+esc(p).replaceAll('\n','<br>')+'</p>').join('')+'<p style="margin:32px 0 0;text-align:right;font-size:11px;color:#7b8794">Sponsored by <a href="https://bringness.de" style="color:#7b8794;text-decoration:none">Bringness.de</a></p></div>';
 text+='\n\nSponsored by Bringness.de' ;}
 transport=await connect({env});submitted=true;const result=await transport.sendMail({from:env.SMTP_FROM,to:row.recipient,subject:message.subject,text,html,attachments,messageId:'<'+row.id+'@bringness.de>'});if(result.rejected?.length)throw Object.assign(Error('REJECTED'),{code:'EENVELOPE'});
 await pool.query("UPDATE transactional_mail SET status='sent',sent_at=now(),last_error=NULL,payload='' WHERE id=$1",[row.id]);
 }catch(e){const definite=!submitted||['EAUTH','EENVELOPE','EMESSAGE'].includes(e.code);await pool.query("UPDATE transactional_mail SET status=$2,next_attempt_at=now()+interval '5 minutes'*least(attempts,12),last_error=$3 WHERE id=$1",[row.id,definite?(row.attempts>=12?'failed':'pending'):'review',definite?'delivery_failed':'submission_uncertain']);}finally{transport?.close();}}
 }finally{running=false}}}
