import assert from 'node:assert/strict';import crypto from 'node:crypto';import fs from 'node:fs';import {Readable} from 'node:stream';import {PGlite} from '@electric-sql/pglite';import {JSDOM} from 'jsdom';import {createDisplays,migrateDisplays} from '../displays.js';
const db=new PGlite();await db.waitReady;
const query=async(sql,args)=>{if(args===undefined&&sql.includes(';')){await db.exec(sql);return {rows:[],rowCount:0}}const r=await db.query(sql,args);return {...r,rowCount:r.affectedRows||r.rows.length}};
const pool={query,connect:async()=>({query,release(){}})},id=()=>crypto.randomUUID(),company=id(),owner=id(),rid=id(),hash=s=>crypto.createHash('sha256').update(s).digest('hex');
await db.exec(`CREATE TABLE restaurants(id uuid PRIMARY KEY,company_id uuid,name text);CREATE TABLE users(id uuid PRIMARY KEY,company_id uuid,role text,status text,must_change_password boolean DEFAULT false);CREATE TABLE sessions(user_id uuid,token_hash text,expires_at timestamptz);CREATE TABLE personnel_unlocks(token_hash text,session_hash text,user_id uuid,expires_at timestamptz);CREATE TABLE categories(id uuid PRIMARY KEY,restaurant_id uuid,name text,sort_order int);CREATE TABLE products(id uuid PRIMARY KEY,restaurant_id uuid,name text,price_cents int,category_id uuid,active boolean,ai_stock_available boolean);`);
await query("INSERT INTO restaurants VALUES($1,$2,'Testbetrieb')",[rid,company]);await query("INSERT INTO users(id,company_id,role,status) VALUES($1,$2,'owner','active')",[owner,company]);await query("INSERT INTO sessions VALUES($1,$2,now()+interval '1 hour')",[owner,hash('owner')]);await query("INSERT INTO personnel_unlocks VALUES($1,$2,$3,now()+interval '1 hour')",[hash('unlock'),hash('owner'),owner]);
await migrateDisplays(pool);let handler=createDisplays(pool);
const png=Buffer.from('89504e470d0a1a0a00000000','hex');
async function call(path,{method='GET',body=null,mime='application/json',publicCall=false}={}){
 const req=Readable.from(body===null?[]:[Buffer.isBuffer(body)?body:Buffer.from(JSON.stringify(body))]);Object.assign(req,{url:path,method,headers:publicCall?{}:{authorization:'Bearer owner','x-personnel-unlock':'unlock','content-type':mime}});let status,headers,result;assert(await handler(req,{writeHead(s,h){status=s;headers=h},end(raw){result=headers?.['content-type']==='application/json'?JSON.parse(raw):raw}}));return {status,headers,result};
}
const base='/api/v1/displays',q='?restaurantId='+rid;
const upload=async()=>{const r=await call(base+'/media'+q,{method:'POST',mime:'image/png',body:png});assert.equal(r.status,201);return r.result};
const original=await upload(),payload={name:'A Theke',orientation:'landscape',fit:'contain',playlist:[{type:'image',mediaId:original.id,seconds:15}]};
const first=(await call(base+q,{method:'POST',body:payload})).result,second=(await call(base+q,{method:'POST',body:{...payload,name:'B Eingang'}})).result;assert.notEqual(first.token,second.token);
// Restart handlers/migrations: server content and distinct screen links survive without client storage.
await migrateDisplays(pool);handler=createDisplays(pool);
const screens=(await call(base+q)).result.displays;assert.equal(screens.find(d=>d.id===first.id).token,first.token);assert.equal(screens.find(d=>d.id===first.id).playlist[0].mediaId,original.id);
let library=(await call(base+'/media'+q)).result.media;assert.equal(library[0].id,original.id);assert.equal(library[0].content,undefined);
assert.deepEqual(Buffer.from((await call('/api/v1/display-player/'+first.token+'/media/'+original.id,{publicCall:true})).result),png);
// Browser upload saves its assignment immediately; reopening never asks for an upload.
const source=fs.readFileSync(new URL('../../apps/web/public/pos/displays.js',import.meta.url),'utf8');
async function browser(){const w=new JSDOM('<select id="restaurant"><option value="'+rid+'" selected>Betrieb</option></select><div id="moreMenu"></div><div id="kasseView"><button id="testSale">Artikel buchen</button></div><div id="moduleView" class="show"><div id="moduleBody"></div></div>',{url:'https://bringness.de/pos/',runScripts:'outside-only'}).window;w.URL.revokeObjectURL=()=>{};w.localStorage.setItem('bringness-pos-token','owner');w.fetch=async(path,options={})=>{if(path==='/api/v1/bootstrap')return {ok:true,json:async()=>({restaurants:[{id:rid,name:'Betrieb'}],categories:[],products:[]})};const r=await call(path,{method:options.method||'GET',mime:options.headers?.['content-type']||'application/json',body:options.body?(typeof options.body==='string'?JSON.parse(options.body):png):null});return {ok:r.status<400,json:async()=>r.result}};w.eval(source);await w.renderDisplaySettings();assert(w.document.querySelector('#displaySelect'),w.document.getElementById('moduleBody').textContent);return w}
let w=await browser();assert.equal(w.document.querySelector('#displaySelect').value,first.id);const input=w.document.querySelector('#displayReplaceUpload');input.dataset.index='0';Object.defineProperty(input,'files',{value:[new w.File([png],'replacement.png',{type:'image/png'})]});await input.onchange({target:input});assert.match(w.document.querySelector('#displayStatus').textContent,/Dauerhaft auf dem Server gespeichert/);w.close();
const saved=(await call(base+q)).result.displays.find(d=>d.id===first.id);assert.equal(saved.token,first.token);assert.equal(saved.playlist.length,1);assert.notEqual(saved.playlist[0].mediaId,original.id);
w=await browser();assert.equal(w.document.querySelector('#displaySelect').value,first.id);assert.equal(w.document.querySelector('#displayLink a').hash,'#'+first.token);assert.equal(w.document.querySelector('#displayMedia').options.length,3);assert.equal(w.document.querySelectorAll('[data-replace]').length,1);w.close();
assert.equal((await call('/api/v1/display-player/'+first.token+'/media/'+original.id,{publicCall:true})).status,404);
assert.equal((await call('/api/v1/display-player/'+second.token+'/media/'+original.id,{publicCall:true})).status,200);
// Actual POS module switching destroys editor previews, while live players stay independent.
w=await browser();w.focus=()=>{};const viewers=[];let openCalls=0,focusCalls=0;
w.open=(url,name)=>{openCalls++;const viewer=new JSDOM('<div id="screen"></div><div id="connection"></div><button id="fullscreen"></button>',{url,runScripts:'outside-only'}).window;viewer.closed=false;viewer.focus=()=>{focusCalls++};viewer.setTimeout=()=>0;viewer.setInterval=fn=>{viewer.refreshOutput=fn;return 0};viewer.fetch=async path=>{viewer.requestCount=(viewer.requestCount||0)+1;const r=await call(path,{publicCall:true});return {ok:r.status<400,status:r.status,json:async()=>r.result}};viewer.eval(fs.readFileSync(new URL('../../apps/web/public/display/player.js',import.meta.url),'utf8'));viewers.push({viewer,name});return viewer};
const showModuleSource=fs.readFileSync(new URL('../../apps/web/public/pos/app.js',import.meta.url),'utf8').split('\n').find(line=>line.startsWith('async function showModule('));
w.eval("const $=id=>document.getElementById(id);const moduleInfo={belege:['Belege','','']};function isRestaurantMode(){return false}async function renderReceipts(){document.getElementById('moduleBody').textContent='Belege geöffnet'};"+showModuleSource);
w.document.getElementById('displayStartAndRegister').click();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(openCalls,1);assert.equal(viewers[0].viewer.opener,null);assert.equal(w.document.getElementById('kasseView').style.display,'block');
await w.showModule('belege');assert.equal(w.document.querySelector('#displayPreviews'),null);assert(viewers[0].viewer.document.querySelector('#screen img'));await w.showModule('kasse');
const count=viewers[0].viewer.requestCount;await viewers[0].viewer.refreshOutput();assert.equal(viewers[0].viewer.requestCount,count+1);assert(viewers[0].viewer.document.querySelector('#screen img').src.includes(saved.playlist[0].mediaId));
w.document.getElementById('bringnessDisplayOutputsToggle').click();w.document.querySelector('#bringnessOutputList button').click();assert.equal(openCalls,1);assert.equal(focusCalls,1);
w.document.querySelectorAll('#bringnessOutputList button')[1].click();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(openCalls,2);assert.notEqual(viewers[0].name,viewers[1].name);
w.document.getElementById('testSale').onclick=()=>w.document.getElementById('testSale').textContent='Artikel gebucht';w.document.getElementById('testSale').click();assert.equal(w.document.getElementById('testSale').textContent,'Artikel gebucht');assert(viewers[0].viewer.document.querySelector('#screen img'));
w.close();for(const {viewer}of viewers)viewer.close();
w=await browser();w.open=()=>null;let switched=false;w.showModule=()=>{switched=true};w.document.getElementById('displayStartAndRegister').click();assert.equal(switched,false);assert.match(w.document.getElementById('bringnessDisplayOutputStatus').textContent,/Pop-ups/);w.close();
// Removing from one screen preserves server media and triggers the live-menu fallback.
w=await browser();await w.document.querySelector('[data-remove]').onclick();assert.equal((await call(base+q)).result.displays.find(d=>d.id===first.id).playlist.length,0);assert.equal((await call(base+'/media'+q)).result.media.length,2);
w.document.querySelector('#displayMedia').value=saved.playlist[0].mediaId;await w.document.querySelector('#displayReuse').onclick();w.close();
// Permanent deletion removes all same-venue assignments atomically, retaining stable URLs.
const third=(await call(base+q,{method:'POST',body:{...payload,name:'C Schaufenster'}})).result;
let usages=(await call(base+'/media'+q)).result.media.find(m=>m.id===original.id).usedBy;assert.equal(usages.length,2);
assert.equal((await call(base+'/media/'+original.id+'?restaurantId='+id(),{method:'DELETE'})).status,404);
const normalHandler=handler;handler=createDisplays({...pool,connect:async()=>({query:async(sql,args)=>{if(sql.startsWith('DELETE FROM pos_display_media'))throw Error('Simulated storage delete failure');return query(sql,args)},release(){}})});
await assert.rejects(call(base+'/media/'+original.id+q,{method:'DELETE'}),/Simulated storage/);handler=normalHandler;
assert.equal((await call(base+q)).result.displays.find(d=>d.id===second.id).playlist[0].mediaId,original.id);
w=await browser();w.confirm=message=>{assert.match(message,/B Eingang/);assert.match(message,/C Schaufenster/);return true};w.document.querySelector('#displayMedia').value=original.id;await w.document.querySelector('#displayMediaDelete').onclick();assert.match(w.document.querySelector('#displayStatus').textContent,/vom Server gelöscht/);w.close();
for(const screen of [second,third]){const found=(await call(base+q)).result.displays.find(d=>d.id===screen.id);assert.equal(found.token,screen.token);assert.deepEqual(found.playlist,[]);assert.deepEqual((await call('/api/v1/display-player/'+screen.token,{publicCall:true})).result.playlist,[])}
assert.equal((await call('/api/v1/display-player/'+second.token+'/media/'+original.id,{publicCall:true})).status,404);
assert.equal((await call(base+'/media'+q)).result.media.length,1);
assert.equal((await call(base+'/'+second.id+q,{method:'PUT',body:payload})).status,400);
assert.equal((await call(base+'/media/'+original.id+q,{method:'DELETE'})).status,404);
// Last media removed: the actual player displays the menu rather than a blank screen.
await call(base+'/media/'+saved.playlist[0].mediaId+q,{method:'DELETE'});
const fallback=(await call('/api/v1/display-player/'+first.token,{publicCall:true})).result;assert.deepEqual(fallback.playlist,[]);
const player=new JSDOM('<div id="screen"></div><div id="connection"></div><button id="fullscreen"></button>',{url:'https://bringness.de/display/index.html#'+first.token,runScripts:'outside-only'}).window;
player.fetch=async()=>({ok:true,json:async()=>({...fallback,products:[{name:'Kaffee',price_cents:250}]})});player.setTimeout=()=>0;player.setInterval=()=>0;player.eval(fs.readFileSync(new URL('../../apps/web/public/display/player.js',import.meta.url),'utf8'));await new Promise(resolve=>setTimeout(resolve,0));assert.match(player.document.querySelector('#screen').textContent,/Kaffee/);player.close();
await db.close();console.log('Display persistence passed: database media survives restart, independent stable screen URLs, saved-media library, automatic upload assignment, replacement without changing links, browser reopen, screen-only removal, permanent deletion across screens, rollback, stale-save rejection, live menu fallback, independent live windows across actual POS module switches, window reuse and popup blocking.');
