import assert from 'node:assert/strict';import crypto from 'node:crypto';import fs from 'node:fs';import {Readable} from 'node:stream';import {PGlite} from '@electric-sql/pglite';import {JSDOM} from 'jsdom';import {createDisplays,migrateDisplays} from '../displays.js';
const db=new PGlite();await db.waitReady;
const query=async(sql,args)=>{if(args===undefined&&sql.includes(';')){await db.exec(sql);return {rows:[],rowCount:0}}const r=await db.query(sql,args);return {...r,rowCount:r.affectedRows||r.rows.length}};
const pool={query,connect:async()=>({query,release(){}})},id=()=>crypto.randomUUID(),company=id(),owner=id(),rid=id(),hash=s=>crypto.createHash('sha256').update(s).digest('hex');
await db.exec(`CREATE TABLE restaurants(id uuid PRIMARY KEY,company_id uuid,name text);CREATE TABLE users(id uuid PRIMARY KEY,company_id uuid,role text,status text,must_change_password boolean DEFAULT false);CREATE TABLE sessions(user_id uuid,token_hash text,expires_at timestamptz);CREATE TABLE personnel_unlocks(token_hash text,session_hash text,user_id uuid,expires_at timestamptz);CREATE TABLE categories(id uuid PRIMARY KEY,restaurant_id uuid,name text,sort_order int);CREATE TABLE products(id uuid PRIMARY KEY,restaurant_id uuid,name text,price_cents int,category_id uuid,active boolean,ai_stock_available boolean);`);
await query("INSERT INTO restaurants VALUES($1,$2,'Testbetrieb')",[rid,company]);await query("INSERT INTO users(id,company_id,role,status) VALUES($1,$2,'owner','active')",[owner,company]);await query("INSERT INTO sessions VALUES($1,$2,now()+interval '1 hour')",[owner,hash('owner')]);await query("INSERT INTO personnel_unlocks VALUES($1,$2,$3,now()+interval '1 hour')",[hash('unlock'),hash('owner'),owner]);
await migrateDisplays(pool);let handler=createDisplays(pool);
const png=Buffer.from('89504e470d0a1a0a00000000','hex');
async function call(path,{method='GET',body=null,mime='application/json',publicCall=false}={}){
 const req=Readable.from(body===null?[]:[Buffer.isBuffer(body)?body:Buffer.from(JSON.stringify(body))]);Object.assign(req,{url:path,method,headers:publicCall?{}:{authorization:'Bearer owner','x-personnel-unlock':'unlock','content-type':mime}});let status,headers,result;assert(await handler(req,{writeHead(s,h){status=s;headers=h},end(raw){result=headers?.['content-type']==='application/json'?JSON.parse(raw):raw}}));return {status,headers,result};
}
const base='/api/v1/displays',q='?restaurantId='+rid;
const upload=async()=>{const r=await call(base+'/media'+q,{method:'POST',mime:'image/png',body:png});assert.equal(r.status,201);return r.result};
const original=await upload(),payload={name:'A Theke',orientation:'landscape',fit:'contain',playlist:[{type:'image',mediaId:original.id,seconds:15}]};
const first=(await call(base+q,{method:'POST',body:payload})).result,second=(await call(base+q,{method:'POST',body:{...payload,name:'B Eingang'}})).result;assert.notEqual(first.token,second.token);
// Restart handlers/migrations: server content and distinct screen links survive without client storage.
await migrateDisplays(pool);handler=createDisplays(pool);
const screens=(await call(base+q)).result.displays;assert.equal(screens.find(d=>d.id===first.id).token,first.token);assert.equal(screens.find(d=>d.id===first.id).playlist[0].mediaId,original.id);
let library=(await call(base+'/media'+q)).result.media;assert.equal(library[0].id,original.id);assert.equal(library[0].content,undefined);
assert.deepEqual(Buffer.from((await call('/api/v1/display-player/'+first.token+'/media/'+original.id,{publicCall:true})).result),png);
// Browser upload saves its assignment immediately; reopening never asks for an upload.
const source=fs.readFileSync(new URL('../../apps/web/public/pos/displays.js',import.meta.url),'utf8');
async function browser(){const w=new JSDOM('<select id="restaurant"><option value="'+rid+'" selected>Betrieb</option></select><div id="moduleBody"></div>',{url:'https://bringness.de/pos/',runScripts:'outside-only'}).window;w.URL.revokeObjectURL=()=>{};w.localStorage.setItem('bringness-pos-token','owner');w.fetch=async(path,options={})=>{if(path==='/api/v1/bootstrap')return {ok:true,json:async()=>({restaurants:[{id:rid,name:'Betrieb'}],categories:[],products:[]})};const r=await call(path,{method:options.method||'GET',mime:options.headers?.['content-type']||'application/json',body:options.body?(typeof options.body==='string'?JSON.parse(options.body):png):null});return {ok:r.status<400,json:async()=>r.result}};w.eval(source);await w.renderDisplaySettings();assert(w.document.querySelector('#displaySelect'),w.document.getElementById('moduleBody').textContent);return w}
let w=await browser();assert.equal(w.document.querySelector('#displaySelect').value,first.id);const input=w.document.querySelector('#displayReplaceUpload');input.dataset.index='0';Object.defineProperty(input,'files',{value:[new w.File([png],'replacement.png',{type:'image/png'})]});await input.onchange({target:input});assert.match(w.document.querySelector('#displayStatus').textContent,/Dauerhaft auf dem Server gespeichert/);w.close();
const saved=(await call(base+q)).result.displays.find(d=>d.id===first.id);assert.equal(saved.token,first.token);assert.equal(saved.playlist.length,1);assert.notEqual(saved.playlist[0].mediaId,original.id);
w=await browser();assert.equal(w.document.querySelector('#displaySelect').value,first.id);assert.equal(w.document.querySelector('#displayLink a').hash,'#'+first.token);assert.equal(w.document.querySelector('#displayMedia').options.length,3);assert.equal(w.document.querySelectorAll('[data-replace]').length,1);w.close();
assert.equal((await call('/api/v1/display-player/'+first.token+'/media/'+original.id,{publicCall:true})).status,404);
assert.equal((await call('/api/v1/display-player/'+second.token+'/media/'+original.id,{publicCall:true})).status,200);
await db.close();console.log('Display persistence passed: database media survives restart, independent stable screen URLs, saved-media library, automatic upload assignment, replacement without changing links, browser reopen and isolation between screens.');
