import {JSDOM} from 'jsdom';import fs from 'node:fs';import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {PGlite} from '@electric-sql/pglite';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)).replace(/\/$/,'');const db=new PGlite();await db.waitReady;
async function query(sql,args){if(sql.includes('CREATE TABLE')){await db.exec(sql);return {rows:[],rowCount:0}}const r=await db.query(sql,args);return {...r,rowCount:r.rows.length||r.affectedRows||0}}
globalThis.aiTestPg={Pool:class{query(...a){return query(...a)}async connect(){return {query,release(){}}}}};
let recipeSource=fs.readFileSync(root+'/server/ai-recipes.js','utf8').replace("import {aiPool,platformPool} from './ai-database.js';","const platformPool=new globalThis.aiTestPg.Pool();const aiPool=()=>new globalThis.aiTestPg.Pool();").replace("'./ai-policy.js'",JSON.stringify('file://'+root+'/server/ai-policy.js'));
const recipeModule=await import('data:text/javascript;base64,'+Buffer.from(recipeSource).toString('base64'));globalThis.aiRecipeModule=recipeModule;
let barcodeSource=fs.readFileSync(root+'/server/ai-barcodes.js','utf8').replace("import {aiPool} from './ai-database.js';","const aiPool=()=>new globalThis.aiTestPg.Pool();").replace("'./ai-policy.js'",JSON.stringify('file://'+root+'/server/ai-policy.js')).replace("'../apps/web/public/ai-csv-parser.js'",JSON.stringify('file://'+root+'/apps/web/public/ai-csv-parser.js'));
globalThis.aiBarcodeModule=await import('data:text/javascript;base64,'+Buffer.from(barcodeSource).toString('base64'));
let source=fs.readFileSync(root+'/server/ai-platform.js','utf8').replace("import {migrateAiRecipes,recipeRoutes,apiSalesToken,ingestSale,syncPosSales} from './ai-recipes.js';","const {migrateAiRecipes,recipeRoutes,apiSalesToken,ingestSale,syncPosSales}=globalThis.aiRecipeModule;").replace("import {aiPool,platformPool,ensureAiDatabase,copyLegacyAiData} from './ai-database.js';","const platformPool=new globalThis.aiTestPg.Pool(); const aiPool=()=>new globalThis.aiTestPg.Pool(); const ensureAiDatabase=async()=>{}; const copyLegacyAiData=async()=>{};").replace("'./ai-policy.js'",JSON.stringify('file://'+root+'/server/ai-policy.js'));
source=source.replace("import {migrateAiBarcodes,barcodeRoutes} from './ai-barcodes.js';","const {migrateAiBarcodes,barcodeRoutes}=globalThis.aiBarcodeModule;");
const {handleAiPlatform,migrateAiPlatform}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const {hash,passwordHash}=await import('file://'+root+'/server/ai-policy.js');await migrateAiPlatform();
await db.exec('CREATE TABLE users(id uuid primary key,status text,must_change_password boolean);CREATE TABLE sessions(token_hash text,user_id uuid,expires_at timestamptz);CREATE TABLE platform_admins(user_id uuid,active boolean);');
const ids={buyer:crypto.randomUUID(),other:crypto.randomUUID(),supplier:crypto.randomUUID(),admin:crypto.randomUUID(),pending:crypto.randomUUID()};
for(const role of ['buyer','other','supplier','pending'])await query('INSERT INTO ai_accounts(id,email,password_hash,name,business_name,role,status,address,city) VALUES($1,$2,$3,$4,$4,$5,$6,$7,$8)',[ids[role],role+'@example.org',passwordHash('testing-password-123'),role,role==='supplier'?'wholesaler':'restaurant',role==='pending'?'pending':'active','Testweg 1','Berlin']);
await query("INSERT INTO users VALUES($1,'active',false)",[ids.admin]);await query('INSERT INTO platform_admins VALUES($1,true)',[ids.admin]);await query("INSERT INTO sessions VALUES($1,$2,now()+interval '1 day')",[hash('admin-token'),ids.admin]);
const tokens={};
async function call(path,body,token){const req=Readable.from(body?[JSON.stringify(body)]:[]);Object.assign(req,{url:'/api/ai/'+path,method:body?'POST':'GET',headers:{authorization:token?'Bearer '+token:'','content-type':'application/json'},socket:{remoteAddress:'127.0.0.1'}});let status,out;const res={writeHead(s){status=s},end(x){out=JSON.parse(x)}};assert(await handleAiPlatform(req,res));return {status,...out}}
for(const r of ['buyer','other','supplier']){const out=await call('login',{email:r+'@example.org',password:'testing-password-123'});assert.equal(out.status,200);tokens[r]=out.token}
assert.equal((await call('me',null)).status,401);assert.equal((await call('admin',null,tokens.buyer)).status,403);
const loc=(await call('locations',{name:'Testbetrieb'},tokens.buyer)).location;
assert.equal((await call('stock',{locationId:loc.id,name:'Fremde Zutat',unit:'kg',quantity:0,minimum:10},tokens.other)).status,404);
const st=(await call('stock',{locationId:loc.id,name:'Mehl',unit:'kg',quantity:2,minimum:10},tokens.buyer)).stock;
assert.equal((await call('products',{name:'Mehl',unit:'kg',packQuantity:5,priceCents:1000,minimumPacks:1},tokens.supplier)).status,201);
const offers=await call('catalog',null,tokens.buyer);assert.equal(offers.products.length,1);const product=offers.products[0];
assert.equal((await call('catalog?q=Mehl',null,tokens.buyer)).products.length,1);
const plan=await call('purchasing?days=7',null,tokens.buyer);assert.equal(plan.status,200);assert.equal(plan.items[0].shortage,8);assert.equal(plan.items[0].offers[0].packs,2);assert.equal((await call('purchasing',null,tokens.supplier)).status,403);assert.equal((await call('purchasing?days=99',null,tokens.buyer)).status,400);assert.equal((await call('purchasing',null,tokens.other)).items.length,0);
const orderBody={productId:product.id,stockId:st.id,packs:2,requestKey:crypto.randomUUID(),deliveryDate:'2026-10-02',expectedNetCents:2000,confirmed:true};
assert.equal((await call('orders',orderBody,tokens.buyer)).status,409);
assert.equal((await call('admin/launch',{onboardingEnabled:true,ordersEnabled:true},'admin-token')).status,200);
assert.equal((await call('orders',{...orderBody,expectedNetCents:1},tokens.buyer)).status,400);
assert.equal((await call('orders',orderBody,tokens.other)).status,404);
const placed=await call('orders',orderBody,tokens.buyer);assert.equal(placed.status,201);assert.equal(Number(placed.order.commission_cents),40);
const duplicate=await call('orders',orderBody,tokens.buyer);assert.equal(duplicate.order.id,placed.order.id);
assert.equal((await call('orders/'+placed.order.id+'/accept',{},tokens.buyer)).status,409);
assert.equal((await call('orders/'+placed.order.id+'/receive',{},tokens.other)).status,404);
assert.equal((await call('orders/'+placed.order.id+'/accept',{},tokens.supplier)).status,200);
assert.equal((await call('purchasing',null,tokens.buyer)).items.length,0);
assert.equal((await call('orders/'+placed.order.id+'/receive',{},tokens.buyer)).status,200);
assert.equal((await call('orders/'+placed.order.id+'/receive',{},tokens.buyer)).status,200);
const ledger=await call('commissions',null,tokens.supplier);assert.equal(Number(ledger.totals.outstanding),40);assert.equal(ledger.commissionBps,200);
assert.equal((await call('commissions',null,tokens.buyer)).status,403);
assert.equal((await call('admin/commission-payment',{orderId:placed.order.id,reference:'bank-test'},tokens.supplier)).status,403);
assert.equal((await call('admin/commission-payment',{orderId:placed.order.id,reference:''},'admin-token')).status,400);
assert.equal((await call('admin/commission-payment',{orderId:placed.order.id,reference:'bank-test'},'admin-token')).status,200);
assert.equal((await call('admin/commission-payment',{orderId:placed.order.id,reference:'bank-test'},'admin-token')).status,200);
const paid=await call('commissions',null,tokens.supplier);assert.equal(Number(paid.totals.outstanding),0);assert.equal(Number(paid.totals.paid),40);assert.equal((await query('SELECT count(*) FROM ai_commission_payments')).rows[0].count,1);
const after=await call('stock',null,tokens.buyer);assert.equal(Number(after.stock[0].quantity),12);
const moves=await call('stock-moves',null,tokens.buyer);assert.equal(moves.moves.filter(m=>m.reason==='Wareneingang').length,1);
assert.equal((await call('orders/'+placed.order.id+'/cancel',{},tokens.buyer)).status,409);
assert.equal((await call('admin/commissions',null,tokens.supplier)).status,403);
const second=(await call('orders',{...orderBody,requestKey:crypto.randomUUID()},tokens.buyer)).order;
assert.equal((await call('orders/'+second.id+'/cancel',{},tokens.supplier)).status,200);
assert.equal(Number((await call('orders',null,tokens.buyer)).orders.find(o=>o.id===second.id).commission_cents),0);
assert.equal((await call('stock-adjust',{id:st.id,quantity:5,minimum:10,reason:'Inventur'},tokens.other)).status,404);
assert.equal((await call('stock-adjust',{id:st.id,quantity:5,minimum:10,reason:'Inventur'},tokens.buyer)).status,200);

// Recipe consumption is isolated, idempotent, and reversed from saved effects.
assert.equal((await call('recipes',{locationId:loc.id,name:'Gericht',productCode:'dish-1',items:[{stockId:st.id,quantity:0.25}]},tokens.other)).status,400);
assert.equal((await call('recipes',{locationId:loc.id,name:'Gericht',productCode:'dish-1',items:[{stockId:st.id,quantity:0.25}]},tokens.buyer)).status,200);
const recipe=(await call('recipes',null,tokens.buyer)).recipes[0];const key=await call('connectors',{locationId:loc.id,name:'Testkasse'},tokens.buyer);const link=(await call('connectors',null,tokens.buyer)).connectors[0];
assert.equal((await call('import/sales',{eventId:'sale-1',items:[{productCode:'dish-1',quantity:4}]},key.token)).status,401);
await call('connector-status',{id:link.id,active:true},tokens.buyer);
const sale={eventId:'sale-1',items:[{productCode:'dish-1',quantity:4}]};assert.equal((await call('import/sales',sale,key.token)).status,200);assert.equal((await call('import/sales',sale,key.token)).duplicate,true);
assert.equal(Number((await call('stock',null,tokens.buyer)).stock[0].quantity),4);
assert.equal((await call('import/sales',{...sale,items:[{productCode:'dish-1',quantity:5}]},key.token)).status,409);
assert.equal((await call('import/sales',{eventId:'missing',items:[{productCode:'unknown',quantity:1}]},key.token)).status,400);
assert.equal(Number((await call('stock',null,tokens.buyer)).stock[0].quantity),4);
await call('recipes',{id:recipe.id,locationId:loc.id,name:'Gericht',productCode:'dish-1',items:[{stockId:st.id,quantity:2}]},tokens.buyer);
assert.equal((await call('import/sales',{eventId:'reverse-1',type:'reversal',reversesEventId:'sale-1'},key.token)).status,200);
assert.equal(Number((await call('stock',null,tokens.buyer)).stock[0].quantity),5);
assert.equal((await call('import/sales',{eventId:'reverse-2',type:'reversal',reversesEventId:'sale-1'},key.token)).status,409);
assert.equal((await call('import/sales',{eventId:'sale-2',items:[{productCode:'dish-1',quantity:10}]},key.token)).status,200);
assert.equal(Number((await call('stock',null,tokens.buyer)).stock[0].quantity),-15);
await call('connector-status',{id:link.id,active:false},tokens.buyer);assert.equal((await call('import/sales',{eventId:'blocked',items:[{productCode:'dish-1',quantity:1}]},key.token)).status,401);

// POS adapter needs a real owner authorization and imports only linked paid sales.
await db.exec('ALTER TABLE users ADD COLUMN company_id uuid;ALTER TABLE users ADD COLUMN role text;CREATE TABLE restaurants(id uuid,company_id uuid,name text);CREATE TABLE products(id uuid,restaurant_id uuid,name text,active boolean);CREATE TABLE orders(id uuid,restaurant_id uuid,status text,closed_at timestamptz,created_at timestamptz);CREATE TABLE order_items(order_id uuid,product_id uuid,quantity numeric);');
const company=crypto.randomUUID(),posOwner=crypto.randomUUID(),restaurant=crypto.randomUUID(),posProduct=crypto.randomUUID(),posOrder=crypto.randomUUID();
await query("INSERT INTO users VALUES($1,'active',false,$2,'owner')",[posOwner,company]);await query("INSERT INTO sessions VALUES($1,$2,now()+interval '1 day')",[hash('pos-owner-token'),posOwner]);await query("INSERT INTO restaurants VALUES($1,$2,'Linked restaurant')",[restaurant,company]);await query("INSERT INTO products VALUES($1,$2,'POS dish',true)",[posProduct,restaurant]);
assert.equal((await call('pos-link',{posToken:'invalid'},tokens.buyer)).status,403);
assert.equal((await call('pos-link',{posToken:'pos-owner-token'},tokens.buyer)).restaurants.length,1);
assert.equal((await call('pos-link',{posToken:'pos-owner-token',restaurantId:crypto.randomUUID(),locationId:loc.id},tokens.buyer)).status,400);
assert.equal((await call('pos-link',{posToken:'pos-owner-token',restaurantId:restaurant,locationId:loc.id},tokens.buyer)).status,200);
const posLink=(await call('connectors',null,tokens.buyer)).connectors.find(c=>c.kind==='pos');await call('connector-status',{id:posLink.id,active:true},tokens.buyer);
await query("INSERT INTO orders VALUES($1,$2,'paid',now()+interval '1 minute',now())",[posOrder,restaurant]);await query('INSERT INTO order_items VALUES($1,$2,2)',[posOrder,posProduct]);
await recipeModule.syncPosSales();assert.match((await call('connectors',null,tokens.buyer)).connectors.find(c=>c.id===posLink.id).last_error,/Rezept fehlt/);
await call('recipes',{locationId:loc.id,name:'POS dish',productCode:posProduct,items:[{stockId:st.id,quantity:0.5}]},tokens.buyer);
await recipeModule.syncPosSales();assert.equal(Number((await call('stock',null,tokens.buyer)).stock[0].quantity),-16);
await recipeModule.syncPosSales();assert.equal(Number((await call('stock',null,tokens.buyer)).stock[0].quantity),-16);
assert.equal((await call('connectors',null,tokens.buyer)).connectors.find(c=>c.id===posLink.id).last_error,null);
// Shared barcode data, CSV atomicity, moderation and tenant-private receipts.
const barcode='4006381333931',entryBody={barcode,name:'Hamburger Patties',unit:'piece',packQuantity:32};
assert.equal((await call('barcodes',entryBody)).status,401);
assert.equal((await call('barcodes',{...entryBody,barcode:'4006381333932'},tokens.buyer)).status,400);
assert.equal((await call('barcodes',{...entryBody,packQuantity:32.5},tokens.buyer)).status,400);
const barcodeEntry=(await call('barcodes',entryBody,tokens.buyer)).entries[0];
const shared=await call('barcodes?barcode='+barcode,null,tokens.other);assert.equal(shared.entries[0].id,barcodeEntry.id);assert.equal(shared.entries[0].pack_quantity,'32.000');assert(!('submitted_by' in shared.entries[0]));
assert.equal((await call('admin/barcodes/review',{id:barcodeEntry.id,action:'approve'},tokens.buyer)).status,403);
assert.equal((await call('admin/barcodes/review',{id:barcodeEntry.id,action:'approve'},'admin-token')).status,200);
const csv='barcode;name;unit;packQuantity\n4006381333931;"Patties; alternative";piece;24\n4006381333932;Invalid;piece;32';
assert.equal((await call('barcodes/csv',{csv},tokens.supplier)).status,400);
assert.equal((await call('barcodes?barcode='+barcode,null,tokens.other)).entries.length,1);
const conflicting=(await call('barcodes/csv',{csv:csv.split('\n').slice(0,2).join('\n')},tokens.supplier)).entries[0];
assert.equal((await call('barcodes?barcode='+barcode,null,tokens.other)).entries[0].id,barcodeEntry.id);
const receiptBody={entryId:barcodeEntry.id,locationId:loc.id,packs:3,requestKey:crypto.randomUUID(),confirmed:true};
assert.equal((await call('barcodes/receive',receiptBody,tokens.other)).status,404);
assert.equal((await call('barcodes/receive',{...receiptBody,stockId:st.id},tokens.buyer)).status,400);
const receipt=await call('barcodes/receive',receiptBody,tokens.buyer);assert.equal(receipt.status,200);assert.equal(Number(receipt.receipt.delta),96);
assert.equal((await call('barcodes/receive',receiptBody,tokens.buyer)).duplicate,true);
assert.equal((await call('barcodes/receive',{...receiptBody,packs:4},tokens.buyer)).status,409);
const repeatReceipt=await call('barcodes/receive',{...receiptBody,packs:1,requestKey:crypto.randomUUID()},tokens.buyer);assert.equal(repeatReceipt.receipt.stock_id,receipt.receipt.stock_id);
assert.equal(Number((await call('stock',null,tokens.buyer)).stock.find(x=>x.id===receipt.receipt.stock_id).quantity),128);
assert(!(await call('stock',null,tokens.other)).stock.some(x=>x.id===receipt.receipt.stock_id));
await call('admin/barcodes/review',{id:conflicting.id,action:'approve'},'admin-token');
assert.equal((await call('barcodes?barcode='+barcode,null,tokens.other)).entries[0].id,conflicting.id);
await call('admin/barcodes/review',{id:conflicting.id,action:'reject'},'admin-token');
assert.equal((await call('barcodes/receive',{...receiptBody,entryId:conflicting.id,requestKey:crypto.randomUUID()},tokens.buyer)).status,409);
await call('admin/barcodes/review',{id:barcodeEntry.id,action:'approve'},'admin-token');
const internationalCsv='Preis;Adet;Ürün adı;Barkod;Birim;Dil\n9,90;32;Türk köftesi;4006381333931;adet;tr';
const internationalPayload={csv:internationalCsv,mapping:{barcode:3,name:2,unit:4,packQuantity:1,language:5},language:'de'};
const beforePreview=(await query('SELECT count(*) FROM ai_barcode_entries')).rows[0].count;
const preview=await call('barcodes/csv-preview',internationalPayload,tokens.other);assert.equal(preview.status,200);assert.equal(preview.products[0].language,'tr');assert.equal(preview.products[0].packQuantity,32);
assert.equal((await query('SELECT count(*) FROM ai_barcode_entries')).rows[0].count,beforePreview);
assert.equal((await call('admin/barcodes/csv-preview',internationalPayload,'admin-token')).status,200);
const importedInternational=await call('barcodes/csv',internationalPayload,tokens.other);assert.equal(importedInternational.entries[0].language,'tr');assert.equal(importedInternational.entries[0].name,'Türk köftesi');
assert.equal((await call('barcodes/csv-preview',{...internationalPayload,csv:internationalCsv.replace(';32;',';32 x 100 g;')},tokens.other)).status,400);
assert.equal((await call('barcodes/csv-preview',{...internationalPayload,mapping:{...internationalPayload.mapping,unit:2}},tokens.other)).status,400);
const {parseCsvTable,mappedProducts}=await import('file://'+root+'/apps/web/public/ai-csv-parser.js');
const arabic=mappedProducts(parseCsvTable('\uFEFFbarcode\tname\tunit\tpackQuantity\n4006381333931\t"برغر; أصلي"\tقطع\t32'),undefined,'ar');assert.equal(arabic[0].name,'برغر; أصلي');assert.equal(arabic[0].packQuantity,32);
assert.throws(()=>mappedProducts(parseCsvTable('barcode,name,unit,packQuantity\n4006381333931,Test,piece,32'),{barcode:0,name:1,unit:2,packQuantity:3,language:9}));
const consumedPlan=await call('purchasing?days=30',null,tokens.buyer);assert(consumedPlan.items.find(x=>x.id===st.id).daily>0);await query('UPDATE ai_accounts SET minimum_order_cents=100000 WHERE id=$1',[ids.supplier]);assert((await call('purchasing',null,tokens.buyer)).items.find(x=>x.id===st.id).offers[0].packs>=100);await query('UPDATE ai_accounts SET minimum_order_cents=0 WHERE id=$1',[ids.supplier]);
console.log('Barcode API passed: shared 32-piece pack, CSV rollback, review rights/conflicts, 3 packs = 96, idempotency, saved mapping and private stock.');
assert.equal((await call('admin/account',{id:ids.pending,action:'restore'},'admin-token')).status,409);
assert.equal((await call('admin/account',{id:ids.buyer,action:'suspend'},'admin-token')).status,200);
assert.equal((await call('me',null,tokens.buyer)).status,401);
assert.equal((await call('admin',null,'admin-token')).status,200);
const verification=crypto.randomBytes(32).toString('hex');await query("INSERT INTO ai_auth_tokens VALUES($1,$2,'verify',now()+interval '1 hour',NULL)",[hash(verification),ids.pending]);assert.equal((await call('verify',{token:verification})).status,200);assert.equal((await call('verify',{token:verification})).status,400);
const reset=crypto.randomBytes(32).toString('hex');await query("INSERT INTO ai_auth_tokens VALUES($1,$2,'reset',now()+interval '1 hour',NULL)",[hash(reset),ids.supplier]);assert.equal((await call('reset',{token:reset,password:'new-testing-password'})).status,200);assert.equal((await call('me',null,tokens.supplier)).status,401);assert.equal((await call('reset',{token:reset,password:'new-testing-password'})).status,400);

const markup=fs.readFileSync(root+'/apps/web/public/ai-workspace.html','utf8'),script=fs.readFileSync(root+'/apps/web/public/ai-workspace.js','utf8');
const browser=new JSDOM(markup,{url:'https://example.org/ai-workspace.html',runScripts:'outside-only'});const w=browser.window;w.HTMLElement.prototype.scrollIntoView=function(){};
w.fetch=async(path,opt={})=>{const result=await call(path.replace('/api/ai/',''),opt.body?JSON.parse(opt.body):undefined,opt.headers?.authorization?.replace('Bearer ',''));const {status,...value}=result;return {ok:status>=200&&status<300,status,json:async()=>value}};
const csvParser=await import('file://'+root+'/apps/web/public/ai-csv-parser.js');w.csvParser=csvParser;w.eval(fs.readFileSync(root+'/apps/web/public/ai-barcodes.js','utf8').replace("import {parseCsvTable,suggestMapping} from './ai-csv-parser.js';","const {parseCsvTable,suggestMapping}=window.csvParser;"));w.eval(script);const d=w.document;
async function until(test){for(let i=0;i<150;i++){if(test())return;await new Promise(r=>setTimeout(r,10))}throw Error('UI wait timed out: '+d.getElementById('notice').textContent)}
function submit(kind,values){const form=d.querySelector('[data-form="'+kind+'"]');assert(form,'form '+kind+' exists');for(const [key,value]of Object.entries(values))form.elements.namedItem(key).value=value;form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}))}
d.querySelector('[data-eye]').click();assert.equal(d.getElementById('password').type,'text');d.querySelector('[data-eye]').click();assert.equal(d.getElementById('password').type,'password');
d.querySelector('[data-auth="register"]').click();assert.equal(d.getElementById('role').options.length,4);d.querySelector('[data-auth="login"]').click();
submit('login',{email:'other@example.org',password:'testing-password-123'});await until(()=>d.querySelector('[data-view="stock"]'));
d.querySelector('[data-view="stock"]').click();await until(()=>d.querySelector('[data-form="location"]'));
submit('location',{name:'UI Teststandort',address:'UI Weg 1'});await until(()=>d.querySelector('#locationId option'));
submit('stock',{name:'UI Mehl',quantity:'0',minimum:'5'});await until(()=>d.querySelector('[data-adjust]'));
d.querySelector('[data-view="catalog"]').click();await until(()=>d.querySelector('[data-form="search"]'));
submit('search',{q:'Mehl'});await until(()=>d.querySelector('[data-buy]'));assert.equal(d.getElementById('search').value,'Mehl');
d.querySelector('[data-buy]').click();const buy=d.querySelector('[data-form="buy"]');buy.elements.namedItem('confirmed').checked=true;submit('buy',{packs:'2',deliveryDate:'2026-10-02'});await until(()=>d.querySelector('[data-cancel]'));assert.match(d.getElementById('content').textContent,/Gesendet/);
d.querySelector('[data-view="barcodes"]').click();await until(()=>d.querySelector('[data-barcode-use]'));
const barcodeSearch=d.querySelector('[data-barcode-form="search"]');barcodeSearch.elements.barcode.value=barcode;barcodeSearch.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.querySelector('[data-barcode-use]')&&!d.querySelector('[data-barcode-form="search"] [type="submit"]').disabled);
d.querySelector('[data-barcode-use]').click();const receiptForm=d.querySelector('[data-barcode-form="receive"]');receiptForm.elements.packs.value='3';receiptForm.elements.packs.dispatchEvent(new w.Event('input',{bubbles:true}));assert.match(receiptForm.textContent,/96 Stück Lagerzugang/);receiptForm.elements.confirmed.checked=true;receiptForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.getElementById('barcode-receive').textContent.includes('96 Einheiten gebucht'));
console.log('Barcode DOM passed: catalog tab, scan input lookup, stored pack size, calculated total and stock receipt.');
const csvForm=d.querySelector('[data-barcode-form="csv"]');csvForm.elements.language.value='tr';
Object.defineProperty(csvForm.elements.file,'files',{value:[{size:100,text:async()=> 'Artikelnummer;Titel;Einheit;Anzahl\n4006381333931;İstanbul Köfte;adet;32'}]});
csvForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.querySelector('[data-barcode-form="csv-map"]'));
const mapForm=d.querySelector('[data-barcode-form="csv-map"]');for(const [key,value]of Object.entries({barcode:0,name:1,unit:2,packQuantity:3}))mapForm.elements.namedItem(key).value=String(value);
mapForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.querySelector('[data-csv-import]'));assert.match(d.getElementById('csv-preview').textContent,/İstanbul Köfte/);assert.match(d.getElementById('csv-preview').textContent,/tr/);
mapForm.elements.name.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.querySelector('[data-csv-import]'),null);
mapForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.querySelector('[data-csv-import]'));d.querySelector('[data-csv-import]').click();await until(()=>d.getElementById('csv-mapping').textContent==='');
assert.equal((await call('barcodes?q='+encodeURIComponent('İstanbul Köfte'),null,tokens.other)).entries[0].language,'tr');
console.log('CSV mapping passed: reordered columns, preview without writes, Unicode product names, language metadata, invalid mapping rejection and DOM preview/import.');
w.localStorage.setItem('bringness-ai-language','de');w.eval(fs.readFileSync(root+'/apps/web/public/ai-language.js','utf8'));const language=d.getElementById('ai-language');language.value='tr';language.dispatchEvent(new w.Event('change',{bubbles:true}));await until(()=>d.querySelector('[data-view="purchasing"]').textContent==='Satın alma planlaması');assert.equal(d.documentElement.lang,'tr');assert.equal(d.querySelector('[data-view="orders"]').textContent,'Siparişler');language.value='en';language.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(d.querySelector('[data-view="orders"]').textContent,'Orders');language.value='de';language.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(d.querySelector('[data-view="orders"]').textContent,'Bestellungen');
d.querySelector('[data-view="purchasing"]').click();await until(()=>d.querySelector('[data-form="planning"]'));assert.match(d.getElementById('content').textContent,/28 Tage/);
d.querySelector('[data-action="logout"]').click();await until(()=>d.querySelector('[data-form="login"]'));submit('login',{email:'supplier@example.org',password:'new-testing-password'});await until(()=>d.querySelector('[data-view="commissions"]'));
d.querySelector('[data-view="commissions"]').click();await until(()=>d.getElementById('content').textContent.includes('bank-test'));assert.match(d.getElementById('content').textContent,/Bezahlt/);assert.equal(d.querySelector('[data-form="commission-payment"]'),null);
d.querySelector('[data-view="products"]').click();await until(()=>d.getElementById('product-filter'));const filter=d.getElementById('product-filter');filter.value='xyz';filter.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.querySelector('#content tbody tr').hidden,true);filter.value='Mehl';filter.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.querySelector('#content tbody tr').hidden,false);
language.value='tr';language.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(d.querySelector('#content tbody tr td').textContent,'Mehl');assert.equal(d.querySelector('[data-form="product"] input[name="name"]').value,'');
console.log('Expansion passed: tenant-private purchasing, pack rounding, incoming orders, 2% ledger, admin-only payment evidence and persistent language switching.');
w.close();console.log('DOM workflow passed: eye, role registration, login, location, stock, catalog search and order submission.');
console.log('Embedded PostgreSQL integration passed: migrations, tenant isolation, catalog, order locks/idempotency, stock receipt, cancellation, admin suspension, verification and reset.');await db.close();
