import {JSDOM} from 'jsdom';import fs from 'node:fs';import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {PGlite} from '@electric-sql/pglite';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)).replace(/\/$/,'');const db=new PGlite();await db.waitReady;
async function query(sql,args){if(sql.includes('pg_try_advisory_lock'))return {rows:[{locked:true}],rowCount:1};if(sql.includes('pg_advisory_unlock'))return {rows:[],rowCount:0};if(sql.includes('CREATE TABLE')){await db.exec(sql);return {rows:[],rowCount:0}}const r=await db.query(sql,args);return {...r,rowCount:r.rows.length||r.affectedRows||0}}
globalThis.aiTestPg={Pool:class{query(...a){return query(...a)}async connect(){return {query,release(){}}}}};
let invoiceSource=fs.readFileSync(root+'/server/ai-invoices.js','utf8').replace("import {aiPool} from './ai-database.js';","const aiPool=()=>new globalThis.aiTestPg.Pool();").replace("'./ai-policy.js'",JSON.stringify('file://'+root+'/server/ai-policy.js'));globalThis.aiInvoiceModule=await import('data:text/javascript;base64,'+Buffer.from(invoiceSource).toString('base64'));
let collectionSource=fs.readFileSync(root+'/server/ai-collection.js','utf8').replace("import {aiPool} from './ai-database.js';","const aiPool=()=>new globalThis.aiTestPg.Pool();").replace("'./ai-policy.js'",JSON.stringify('file://'+root+'/server/ai-policy.js'));collectionSource=collectionSource.replace("import {migrateAiInvoices,issueInvoice,invoiceRoutes,validateIssuer,invoiceHtml} from './ai-invoices.js';","const {migrateAiInvoices,issueInvoice,invoiceRoutes,validateIssuer,invoiceHtml}=globalThis.aiInvoiceModule;");globalThis.aiCollectionModule=await import('data:text/javascript;base64,'+Buffer.from(collectionSource).toString('base64'));
let recipeSource=fs.readFileSync(root+'/server/ai-recipes.js','utf8').replace("'./ai-sales-contract.js'",JSON.stringify('file://'+root+'/server/ai-sales-contract.js')).replace("import {aiPool,platformPool} from './ai-database.js';","const platformPool=new globalThis.aiTestPg.Pool();const aiPool=()=>new globalThis.aiTestPg.Pool();").replace("'./ai-policy.js'",JSON.stringify('file://'+root+'/server/ai-policy.js'));
const recipeModule=await import('data:text/javascript;base64,'+Buffer.from(recipeSource).toString('base64'));globalThis.aiRecipeModule=recipeModule;
let barcodeSource=fs.readFileSync(root+'/server/ai-barcodes.js','utf8').replace("import {aiPool} from './ai-database.js';","const aiPool=()=>new globalThis.aiTestPg.Pool();").replace("'./ai-policy.js'",JSON.stringify('file://'+root+'/server/ai-policy.js')).replace("'../apps/web/public/ai-csv-parser.js'",JSON.stringify('file://'+root+'/apps/web/public/ai-csv-parser.js'));
globalThis.aiBarcodeModule=await import('data:text/javascript;base64,'+Buffer.from(barcodeSource).toString('base64'));
let supplierSource=fs.readFileSync(root+'/server/ai-suppliers.js','utf8').replace("import {aiPool} from './ai-database.js';","const aiPool=()=>new globalThis.aiTestPg.Pool();").replace("'./ai-policy.js'",JSON.stringify('file://'+root+'/server/ai-policy.js'));supplierSource=supplierSource.replace("import {supplierMayTrade} from './ai-collection.js';","const {supplierMayTrade}=globalThis.aiCollectionModule;");globalThis.aiSupplierModule=await import('data:text/javascript;base64,'+Buffer.from(supplierSource).toString('base64'));
let adSource=fs.readFileSync(root+'/server/ai-ads.js','utf8').replace("import {aiPool} from './ai-database.js';","const aiPool=()=>new globalThis.aiTestPg.Pool();").replace("'./ai-policy.js'",JSON.stringify('file://'+root+'/server/ai-policy.js'));globalThis.aiAdModule=await import('data:text/javascript;base64,'+Buffer.from(adSource).toString('base64'));
let settlementSource=fs.readFileSync(root+'/server/ai-settlements.js','utf8').replace("import {aiPool} from './ai-database.js';","const aiPool=()=>new globalThis.aiTestPg.Pool();").replace("'./ai-policy.js'",JSON.stringify('file://'+root+'/server/ai-policy.js'));settlementSource=settlementSource.replace("import {ensureManualPaymentAllowed} from './ai-collection.js';","const {ensureManualPaymentAllowed}=globalThis.aiCollectionModule;");globalThis.aiSettlementModule=await import('data:text/javascript;base64,'+Buffer.from(settlementSource).toString('base64'));
let source=fs.readFileSync(root+'/server/ai-platform.js','utf8').replace("import {migrateAiRecipes,recipeRoutes,apiSalesToken,ingestSale,syncPosSales} from './ai-recipes.js';","const {migrateAiRecipes,recipeRoutes,apiSalesToken,ingestSale,syncPosSales}=globalThis.aiRecipeModule;").replace("import {aiPool,platformPool,ensureAiDatabase,copyLegacyAiData} from './ai-database.js';","const platformPool=new globalThis.aiTestPg.Pool(); const aiPool=()=>new globalThis.aiTestPg.Pool(); const ensureAiDatabase=async()=>{}; const copyLegacyAiData=async()=>{};").replace("'./ai-policy.js'",JSON.stringify('file://'+root+'/server/ai-policy.js'));
source=source.replace("import {migrateAiCollection,collectionRoutes,collectionTick,supplierMayTrade,ensureManualPaymentAllowed} from './ai-collection.js';","const {migrateAiCollection,collectionRoutes,collectionTick,supplierMayTrade,ensureManualPaymentAllowed}=globalThis.aiCollectionModule;");
source=source.replace("import {migrateAiSettlements,settlementRoutes} from './ai-settlements.js';","const {migrateAiSettlements,settlementRoutes}=globalThis.aiSettlementModule;");
source=source.replace("import {migrateAiAds,adRoutes} from './ai-ads.js';","const {migrateAiAds,adRoutes}=globalThis.aiAdModule;");
source=source.replace("import {migrateAiSuppliers,supplierAccountRoutes,supplierPublicRoutes} from './ai-suppliers.js';","const {migrateAiSuppliers,supplierAccountRoutes,supplierPublicRoutes}=globalThis.aiSupplierModule;");
source=source.replace("import {migrateAiBarcodes,barcodeRoutes} from './ai-barcodes.js';","const {migrateAiBarcodes,barcodeRoutes}=globalThis.aiBarcodeModule;");
const {handleAiPlatform,migrateAiPlatform}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const {hash,passwordHash}=await import('file://'+root+'/server/ai-policy.js');await migrateAiPlatform();
await db.exec('CREATE TABLE users(id uuid primary key,status text,must_change_password boolean);CREATE TABLE sessions(token_hash text,user_id uuid,expires_at timestamptz);CREATE TABLE platform_admins(user_id uuid,active boolean);');
const ids={buyer:crypto.randomUUID(),other:crypto.randomUUID(),supplier:crypto.randomUUID(),admin:crypto.randomUUID(),pending:crypto.randomUUID()};
for(const role of ['buyer','other','supplier','pending'])await query('INSERT INTO ai_accounts(id,email,password_hash,name,business_name,role,status,address,city) VALUES($1,$2,$3,$4,$4,$5,$6,$7,$8)',[ids[role],role+'@example.org',passwordHash('testing-password-123'),role,role==='supplier'?'wholesaler':'restaurant',role==='pending'?'pending':'active','Testweg 1','Berlin']);
await query("INSERT INTO users VALUES($1,'active',false)",[ids.admin]);await query('INSERT INTO platform_admins VALUES($1,true)',[ids.admin]);await query("INSERT INTO sessions VALUES($1,$2,now()+interval '1 day')",[hash('admin-token'),ids.admin]);
const tokens={};
async function call(path,body,token){const req=Readable.from(body?[JSON.stringify(body)]:[]);Object.assign(req,{url:'/api/ai/'+path,method:body?'POST':'GET',headers:{authorization:token?'Bearer '+token:'','content-type':'application/json'},socket:{remoteAddress:'127.0.0.1'}});let status,out;const res={writeHead(s){status=s},end(x){out=JSON.parse(x)}};assert(await handleAiPlatform(req,res));return {status,...out}}
for(const r of ['buyer','other','supplier']){const out=await call('login',{email:r+'@example.org',password:'testing-password-123'});assert.equal(out.status,200);tokens[r]=out.token}
assert.equal((await call('me',null)).status,401);assert.equal((await call('admin',null,tokens.buyer)).status,403);
const adBody={kind:'brand',title:'Regional einkaufen',description:'Unser Sortiment für Restaurants.'};
assert.equal((await call('admin/ads',null,tokens.supplier)).status,403);
assert.equal((await call('ads',adBody,tokens.buyer)).status,403);
const adCreated=await call('ads',{...adBody,feeCents:1,status:'active'},tokens.supplier);assert.equal(adCreated.status,200);
const adId=adCreated.id;assert.equal((await call('ads/live?placement=dashboard',null,tokens.buyer)).ads.length,0);
assert.equal((await call('ads/approve',{id:adId},tokens.supplier)).status,403);
assert.equal((await call('admin/ads/approve',{id:adId},'admin-token')).status,409);
const adQuote={id:adId,feeCents:2500,startsAt:new Date(Date.now()-60000).toISOString(),endsAt:new Date(Date.now()+86400000).toISOString(),cities:['Berlin'],postalPrefixes:[],cuisines:[],placement:'dashboard'};
assert.equal((await call('admin/ads/quote',{...adQuote,cities:[]},'admin-token')).status,400);
assert.equal((await call('admin/ads/quote',adQuote,'admin-token')).status,200);
let ad=(await call('ads',null,tokens.supplier)).ads[0];assert.equal(Number(ad.fee_cents),2500);
assert.equal((await call('ads/accept',{id:adId,version:ad.version,confirmed:false},tokens.supplier)).status,409);
assert.equal((await call('ads/accept',{id:adId,version:ad.version,confirmed:true},tokens.supplier)).status,200);
assert.equal((await call('admin/ads/approve',{id:adId},'admin-token')).status,200);
let adFeed=(await call('ads/live?placement=dashboard',null,tokens.buyer)).ads;assert.equal(adFeed.length,1);assert.equal(adFeed[0].label,'Anzeige');
assert.equal((await call('ads/live?placement=catalog',null,tokens.buyer)).ads.length,0);
await query("UPDATE ai_accounts SET city='Hamburg' WHERE id=$1",[ids.other]);assert.equal((await call('ads/live?placement=dashboard&city=Berlin',null,tokens.other)).ads.length,0);
assert.equal((await call('ads/event',{token:adFeed[0].eventToken,kind:'click'},tokens.other)).status,409);
for(let i=0;i<2;i++)assert.equal((await call('ads/event',{token:adFeed[0].eventToken,kind:'view'},tokens.buyer)).status,200);
assert.equal((await call('ads/event',{token:adFeed[0].eventToken,kind:'click'},tokens.buyer)).status,200);
ad=(await call('admin/ads',null,'admin-token')).ads[0];assert.equal(Number(ad.impressions),1);assert.equal(Number(ad.clicks),1);
assert.equal((await call('admin/ads/pause',{id:adId},'admin-token')).status,200);assert.equal((await call('ads/live?placement=dashboard',null,tokens.buyer)).ads.length,0);
assert.equal((await call('admin/ads/resume',{id:adId},'admin-token')).status,200);
assert.equal((await call('ads',{...adBody,id:adId,title:'Neue Inhalte'},tokens.supplier)).status,200);assert.equal((await call('ads/live?placement=dashboard',null,tokens.buyer)).ads.length,0);
assert.equal((await call('ads/event',{token:adFeed[0].eventToken,kind:'click'},tokens.buyer)).status,409);
await query("UPDATE ai_accounts SET city='Berlin' WHERE id=$1",[ids.other]);
console.log('Advertising API passed: superadmin-only terms and approval, explicit supplier acceptance, regional isolation, deduplicated metrics, pause and content review.');
const loc=(await call('locations',{name:'Testbetrieb'},tokens.buyer)).location;
assert.equal((await call('stock',{locationId:loc.id,name:'Fremde Zutat',unit:'kg',quantity:0,minimum:10},tokens.other)).status,404);
const st=(await call('stock',{locationId:loc.id,name:'Mehl',unit:'kg',quantity:2,minimum:10},tokens.buyer)).stock;
assert.equal((await call('products',{name:'Mehl',unit:'kg',packQuantity:5,priceCents:1000,minimumPacks:1},tokens.supplier)).status,201);
const offers=await call('catalog',null,tokens.buyer);assert.equal(offers.products.length,1);const product=offers.products[0];
assert.equal((await call('catalog?q=Mehl',null,tokens.buyer)).products.length,1);
const plan=await call('purchasing?days=7',null,tokens.buyer);assert.equal(plan.status,200);assert.equal(plan.items[0].shortage,8);assert.equal(plan.items[0].offers[0].packs,2);assert.equal((await call('purchasing',null,tokens.supplier)).status,403);assert.equal((await call('purchasing?days=99',null,tokens.buyer)).status,400);assert.equal((await call('purchasing',null,tokens.other)).items.length,0);
const productAd=(await call('ads',{kind:'offer',productId:product.id,title:'Mehl Angebot',description:'Aktuelles Mehlangebot'},tokens.supplier)).id;
assert.equal((await call('admin/ads/quote',{...adQuote,id:productAd,cuisines:['italienisch']},'admin-token')).status,200);
let productCampaign=(await call('ads',null,tokens.supplier)).ads.find(a=>a.id===productAd);
assert.equal((await call('ads/accept',{id:productAd,version:productCampaign.version,confirmed:true},tokens.supplier)).status,200);
assert.equal((await call('admin/ads/approve',{id:productAd},'admin-token')).status,200);
assert.equal((await call('ads/live?placement=dashboard',null,tokens.buyer)).ads.length,0);
await query("UPDATE ai_accounts SET cuisine_type='Italienisch' WHERE id=$1",[ids.buyer]);assert.equal((await call('ads/live?placement=dashboard',null,tokens.buyer)).ads.length,1);
await query('UPDATE ai_products SET price_cents=price_cents+1 WHERE id=$1',[product.id]);assert.equal((await call('ads/live?placement=dashboard',null,tokens.buyer)).ads.length,0);
assert.equal((await call('admin/ads/pause',{id:productAd},'admin-token')).status,200);assert.equal((await call('admin/ads/resume',{id:productAd},'admin-token')).status,409);
await query('UPDATE ai_products SET price_cents=price_cents-1 WHERE id=$1',[product.id]);
await call('admin/ads/reject',{id:productAd},'admin-token');
await call('admin/ads/quote',{...adQuote,id:adId,startsAt:new Date(Date.now()+3600000).toISOString()},'admin-token');ad=(await call('ads',null,tokens.supplier)).ads.find(a=>a.id===adId);await call('ads/accept',{id:adId,version:ad.version,confirmed:true},tokens.supplier);await call('admin/ads/approve',{id:adId},'admin-token');assert.equal((await call('ads/live?placement=dashboard',null,tokens.buyer)).ads.length,0);
assert.equal((await call('admin/ads/payment',{id:adId,reference:'bank-ad-test'},'admin-token')).status,200);assert.equal((await call('admin/ads/payment',{id:adId,reference:'forged'},tokens.supplier)).status,403);
await call('admin/ads/reject',{id:adId},'admin-token');
console.log('Advertising product checks passed: cuisine targeting, future scheduling, product snapshot invalidation and separate manual payment evidence.');
const orderBody={productId:product.id,stockId:st.id,packs:2,requestKey:crypto.randomUUID(),deliveryDate:'2026-10-02',expectedNetCents:2000,confirmed:true};
assert.equal((await call('orders',orderBody,tokens.buyer)).status,409);
assert.equal((await call('admin/launch',{onboardingEnabled:true,ordersEnabled:true},'admin-token')).status,200);
assert.equal((await call('orders',{...orderBody,expectedNetCents:1},tokens.buyer)).status,400);
assert.equal((await call('orders',orderBody,tokens.other)).status,404);
const placed=await call('orders',orderBody,tokens.buyer);assert.equal(placed.status,201);assert.equal(Number(placed.order.commission_cents),40);
const duplicate=await call('orders',orderBody,tokens.buyer);assert.equal(duplicate.order.id,placed.order.id);
assert.equal((await call('orders/'+placed.order.id+'/accept',{},tokens.buyer)).status,409);
assert.equal((await call('orders/'+placed.order.id+'/receive',{},tokens.other)).status,404);
assert.equal((await call('orders/'+placed.order.id+'/accept',{},tokens.supplier)).status,200);
assert.equal((await call('purchasing',null,tokens.buyer)).items.length,0);
assert.equal((await call('orders/'+placed.order.id+'/receive',{},tokens.buyer)).status,200);
assert.equal((await call('orders/'+placed.order.id+'/receive',{},tokens.buyer)).status,200);
const ledger=await call('commissions',null,tokens.supplier);assert.equal(Number(ledger.totals.outstanding),40);assert.equal(ledger.commissionBps,200);
assert.equal((await call('commissions',null,tokens.buyer)).status,403);
assert.equal((await call('admin/commission-payment',{orderId:placed.order.id,reference:'bank-test'},tokens.supplier)).status,403);
assert.equal((await call('admin/commission-payment',{orderId:placed.order.id,reference:''},'admin-token')).status,400);
assert.equal((await call('admin/commission-payment',{orderId:placed.order.id,reference:'bank-test'},'admin-token')).status,200);
assert.equal((await call('admin/commission-payment',{orderId:placed.order.id,reference:'bank-test'},'admin-token')).status,200);
const paid=await call('commissions',null,tokens.supplier);assert.equal(Number(paid.totals.outstanding),0);assert.equal(Number(paid.totals.paid),40);assert.equal((await query('SELECT count(*) FROM ai_commission_payments')).rows[0].count,1);
const settlementMonth=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit'}).format(new Date());
assert.equal((await call('settlements',null,tokens.buyer)).status,403);
assert.equal((await call('admin/settlements',null,tokens.supplier)).status,403);
let monthly=await call('settlements?month='+settlementMonth,null,tokens.supplier);assert.equal(monthly.status,200);assert.equal(monthly.rows.length,1);assert.equal(Number(monthly.rows[0].paid_cents),40);assert.equal(Number(monthly.rows[0].outstanding_cents),0);assert.equal(monthly.details.length,1);
assert.equal((await call('settlements?supplierId='+ids.other,null,tokens.supplier)).status,403);
assert.equal((await call('settlements?month=2026-99',null,tokens.supplier)).status,400);
assert.equal((await call('admin/settlements/deadline',{month:settlementMonth,supplierId:ids.supplier,dueDate:'2026-02-30'},'admin-token')).status,400);
assert.equal((await call('admin/settlements/deadline',{month:settlementMonth,supplierId:ids.supplier,dueDate:'2020-01-01'},'admin-token')).status,200);
assert.equal((await call('settlements/payment',{month:settlementMonth,supplierId:ids.supplier,amountCents:40,reference:'forged',confirmed:true},tokens.supplier)).status,403);
const after=await call('stock',null,tokens.buyer);assert.equal(Number(after.stock[0].quantity),12);
const moves=await call('stock-moves',null,tokens.buyer);assert.equal(moves.moves.filter(m=>m.reason==='Wareneingang').length,1);
assert.equal((await call('orders/'+placed.order.id+'/cancel',{},tokens.buyer)).status,409);
assert.equal((await call('admin/commissions',null,tokens.supplier)).status,403);
const second=(await call('orders',{...orderBody,requestKey:crypto.randomUUID()},tokens.buyer)).order;
assert.equal((await call('orders/'+second.id+'/cancel',{},tokens.supplier)).status,200);
assert.equal(Number((await call('orders',null,tokens.buyer)).orders.find(o=>o.id===second.id).commission_cents),0);
assert.equal((await call('stock-adjust',{id:st.id,quantity:5,minimum:10,reason:'Inventur'},tokens.other)).status,404);
assert.equal((await call('stock-adjust',{id:st.id,quantity:5,minimum:10,reason:'Inventur'},tokens.buyer)).status,200);

// Recipe consumption is isolated, idempotent, and reversed from saved effects.
assert.equal((await call('recipes',{locationId:loc.id,name:'Gericht',productCode:'dish-1',items:[{stockId:st.id,quantity:0.25}]},tokens.other)).status,400);
assert.equal((await call('recipes',{locationId:loc.id,name:'Gericht',productCode:'dish-1',items:[{stockId:st.id,quantity:0.25}]},tokens.buyer)).status,200);
const recipe=(await call('recipes',null,tokens.buyer)).recipes[0];const key=await call('connectors',{locationId:loc.id,name:'Testkasse'},tokens.buyer);const link=(await call('connectors',null,tokens.buyer)).connectors[0];
assert.equal((await call('import/sales',{eventId:'sale-1',items:[{productCode:'dish-1',quantity:4}]},key.token)).status,401);
await call('connector-status',{id:link.id,active:true},tokens.buyer);
assert.equal((await call('v1/status',null,key.token)).connectorId,link.id);
assert.equal((await call('v1/products',null,key.token)).products[0].productCode,'dish-1');
const beforeDry=Number((await call('stock',null,tokens.buyer)).stock[0].quantity);
const dry=await call('v1/sales/validate',{eventId:'dry-1',items:[{productCode:'dish-1',quantity:4}]},key.token);assert.equal(dry.dryRun,true);assert.equal(dry.effects[0].delta,-1);assert.equal(Number((await call('stock',null,tokens.buyer)).stock[0].quantity),beforeDry);assert.equal((await query("SELECT 1 FROM ai_sale_events WHERE external_id='dry-1'")).rowCount,0);
assert.equal((await call('v1/sales',{eventId:'bad-type',items:[{productCode:'dish-1',quantity:true}]},key.token)).status,400);
assert.equal((await call('v1/sales',{eventId:'x'.repeat(151),items:[{productCode:'dish-1',quantity:1}]},key.token)).status,400);
assert.equal((await call('v1/products',null,tokens.other)).status,401);
const sale={eventId:'sale-1',items:[{productCode:'dish-1',quantity:4}]};assert.equal((await call('import/sales',sale,key.token)).status,200);assert.equal((await call('import/sales',sale,key.token)).duplicate,true);
assert.equal(Number((await call('stock',null,tokens.buyer)).stock[0].quantity),4);
assert.equal((await call('v1/sales',sale,key.token)).duplicate,true);
const duplicateDry=await call('v1/sales/validate',sale,key.token);assert.equal(duplicateDry.dryRun,true);assert.equal(duplicateDry.duplicate,true);
assert.equal((await call('import/sales',{...sale,items:[{productCode:'dish-1',quantity:5}]},key.token)).status,409);
assert.equal((await call('import/sales',{eventId:'missing',items:[{productCode:'unknown',quantity:1}]},key.token)).status,400);
assert.equal(Number((await call('stock',null,tokens.buyer)).stock[0].quantity),4);
await call('recipes',{id:recipe.id,locationId:loc.id,name:'Gericht',productCode:'dish-1',items:[{stockId:st.id,quantity:2}]},tokens.buyer);
assert.equal((await call('import/sales',{eventId:'reverse-1',type:'reversal',reversesEventId:'sale-1'},key.token)).status,200);
assert.equal(Number((await call('stock',null,tokens.buyer)).stock[0].quantity),5);
assert.equal((await call('import/sales',{eventId:'reverse-2',type:'reversal',reversesEventId:'sale-1'},key.token)).status,409);
assert.equal((await call('import/sales',{eventId:'sale-2',items:[{productCode:'dish-1',quantity:10}]},key.token)).status,200);
assert.equal(Number((await call('stock',null,tokens.buyer)).stock[0].quantity),-15);
await call('connector-status',{id:link.id,active:false},tokens.buyer);assert.equal((await call('import/sales',{eventId:'blocked',items:[{productCode:'dish-1',quantity:1}]},key.token)).status,401);

assert.equal((await call('connector-key',{id:link.id},tokens.other)).status,404);
const rotated=await call('connector-key',{id:link.id},tokens.buyer);assert.equal(rotated.status,200);await call('connector-status',{id:link.id,active:true},tokens.buyer);assert.equal((await call('v1/status',null,key.token)).status,401);assert.equal((await call('v1/status',null,rotated.token)).status,200);await call('connector-status',{id:link.id,active:false},tokens.buyer);

// POS adapter needs a real owner authorization and imports only linked paid sales.
await db.exec('ALTER TABLE users ADD COLUMN company_id uuid;ALTER TABLE users ADD COLUMN role text;CREATE TABLE restaurants(id uuid,company_id uuid,name text);CREATE TABLE products(id uuid,restaurant_id uuid,name text,active boolean);CREATE TABLE orders(id uuid,restaurant_id uuid,status text,closed_at timestamptz,created_at timestamptz);CREATE TABLE order_items(order_id uuid,product_id uuid,quantity numeric);');
const company=crypto.randomUUID(),posOwner=crypto.randomUUID(),restaurant=crypto.randomUUID(),posProduct=crypto.randomUUID(),posOrder=crypto.randomUUID();
await query("INSERT INTO users VALUES($1,'active',false,$2,'owner')",[posOwner,company]);await query("INSERT INTO sessions VALUES($1,$2,now()+interval '1 day')",[hash('pos-owner-token'),posOwner]);await query("INSERT INTO restaurants VALUES($1,$2,'Linked restaurant')",[restaurant,company]);await query("INSERT INTO products VALUES($1,$2,'POS dish',true)",[posProduct,restaurant]);
assert.equal((await call('pos-link',{posToken:'invalid'},tokens.buyer)).status,403);
assert.equal((await call('pos-link',{posToken:'pos-owner-token'},tokens.buyer)).restaurants.length,1);
assert.equal((await call('pos-link',{posToken:'pos-owner-token',restaurantId:crypto.randomUUID(),locationId:loc.id},tokens.buyer)).status,400);
assert.equal((await call('pos-link',{posToken:'pos-owner-token',restaurantId:restaurant,locationId:loc.id},tokens.buyer)).status,200);
const posLink=(await call('connectors',null,tokens.buyer)).connectors.find(c=>c.kind==='pos');await call('connector-status',{id:posLink.id,active:true},tokens.buyer);
await query("INSERT INTO orders VALUES($1,$2,'paid',now()+interval '1 minute',now())",[posOrder,restaurant]);await query('INSERT INTO order_items VALUES($1,$2,2)',[posOrder,posProduct]);
await recipeModule.syncPosSales();assert.match((await call('connectors',null,tokens.buyer)).connectors.find(c=>c.id===posLink.id).last_error,/Rezept fehlt/);
await call('recipes',{locationId:loc.id,name:'POS dish',productCode:posProduct,items:[{stockId:st.id,quantity:0.5}]},tokens.buyer);
await recipeModule.syncPosSales();assert.equal(Number((await call('stock',null,tokens.buyer)).stock[0].quantity),-16);
await recipeModule.syncPosSales();assert.equal(Number((await call('stock',null,tokens.buyer)).stock[0].quantity),-16);
const mapping=await call('pos-products?connectorId='+posLink.id,null,tokens.buyer);assert.equal(mapping.status,200);assert.equal(mapping.unmapped,0);assert.equal(mapping.products[0].id,posProduct);assert.equal((await call('pos-products?connectorId='+posLink.id,null,tokens.other)).status,404);
await query('UPDATE users SET must_change_password=true WHERE id=$1',[posOwner]);assert.equal((await call('pos-products?connectorId='+posLink.id,null,tokens.buyer)).status,403);await recipeModule.syncPosSales();assert.match((await call('connectors',null,tokens.buyer)).connectors.find(c=>c.id===posLink.id).last_error,/freigabe/i);await query('UPDATE users SET must_change_password=false WHERE id=$1',[posOwner]);await recipeModule.syncPosSales();
assert.equal((await call('connectors',null,tokens.buyer)).connectors.find(c=>c.id===posLink.id).last_error,null);
// Shared barcode data, CSV atomicity, moderation and tenant-private receipts.
const barcode='4006381333931',entryBody={barcode,name:'Hamburger Patties',unit:'piece',packQuantity:32};
assert.equal((await call('barcodes',entryBody)).status,401);
assert.equal((await call('barcodes',{...entryBody,barcode:'4006381333932'},tokens.buyer)).status,400);
assert.equal((await call('barcodes',{...entryBody,packQuantity:32.5},tokens.buyer)).status,400);
const barcodeEntry=(await call('barcodes',entryBody,tokens.buyer)).entries[0];
const shared=await call('barcodes?barcode='+barcode,null,tokens.other);assert.equal(shared.entries[0].id,barcodeEntry.id);assert.equal(shared.entries[0].pack_quantity,'32.000');assert(!('submitted_by' in shared.entries[0]));
assert.equal((await call('admin/barcodes/review',{id:barcodeEntry.id,action:'approve'},tokens.buyer)).status,403);
assert.equal((await call('admin/barcodes/review',{id:barcodeEntry.id,action:'approve'},'admin-token')).status,200);
const csv='barcode;name;unit;packQuantity\n4006381333931;"Patties; alternative";piece;24\n4006381333932;Invalid;piece;32';
assert.equal((await call('barcodes/csv',{csv},tokens.supplier)).status,400);
assert.equal((await call('barcodes?barcode='+barcode,null,tokens.other)).entries.length,1);
const conflicting=(await call('barcodes/csv',{csv:csv.split('\n').slice(0,2).join('\n')},tokens.supplier)).entries[0];
assert.equal((await call('barcodes?barcode='+barcode,null,tokens.other)).entries[0].id,barcodeEntry.id);
const receiptBody={entryId:barcodeEntry.id,locationId:loc.id,packs:3,requestKey:crypto.randomUUID(),confirmed:true};
assert.equal((await call('barcodes/receive',receiptBody,tokens.other)).status,404);
assert.equal((await call('barcodes/receive',{...receiptBody,stockId:st.id},tokens.buyer)).status,400);
const receipt=await call('barcodes/receive',receiptBody,tokens.buyer);assert.equal(receipt.status,200);assert.equal(Number(receipt.receipt.delta),96);
assert.equal((await call('barcodes/receive',receiptBody,tokens.buyer)).duplicate,true);
assert.equal((await call('barcodes/receive',{...receiptBody,packs:4},tokens.buyer)).status,409);
const repeatReceipt=await call('barcodes/receive',{...receiptBody,packs:1,requestKey:crypto.randomUUID()},tokens.buyer);assert.equal(repeatReceipt.receipt.stock_id,receipt.receipt.stock_id);
assert.equal(Number((await call('stock',null,tokens.buyer)).stock.find(x=>x.id===receipt.receipt.stock_id).quantity),128);
assert(!(await call('stock',null,tokens.other)).stock.some(x=>x.id===receipt.receipt.stock_id));
await call('admin/barcodes/review',{id:conflicting.id,action:'approve'},'admin-token');
assert.equal((await call('barcodes?barcode='+barcode,null,tokens.other)).entries[0].id,conflicting.id);
await call('admin/barcodes/review',{id:conflicting.id,action:'reject'},'admin-token');
assert.equal((await call('barcodes/receive',{...receiptBody,entryId:conflicting.id,requestKey:crypto.randomUUID()},tokens.buyer)).status,409);
await call('admin/barcodes/review',{id:barcodeEntry.id,action:'approve'},'admin-token');
const internationalCsv='Preis;Adet;Ürün adı;Barkod;Birim;Dil\n9,90;32;Türk köftesi;4006381333931;adet;tr';
const internationalPayload={csv:internationalCsv,mapping:{barcode:3,name:2,unit:4,packQuantity:1,language:5},language:'de'};
const beforePreview=(await query('SELECT count(*) FROM ai_barcode_entries')).rows[0].count;
const preview=await call('barcodes/csv-preview',internationalPayload,tokens.other);assert.equal(preview.status,200);assert.equal(preview.products[0].language,'tr');assert.equal(preview.products[0].packQuantity,32);
assert.equal((await query('SELECT count(*) FROM ai_barcode_entries')).rows[0].count,beforePreview);
assert.equal((await call('admin/barcodes/csv-preview',internationalPayload,'admin-token')).status,200);
const importedInternational=await call('barcodes/csv',internationalPayload,tokens.other);assert.equal(importedInternational.entries[0].language,'tr');assert.equal(importedInternational.entries[0].name,'Türk köftesi');
assert.equal((await call('barcodes/csv-preview',{...internationalPayload,csv:internationalCsv.replace(';32;',';32 x 100 g;')},tokens.other)).status,400);
assert.equal((await call('barcodes/csv-preview',{...internationalPayload,mapping:{...internationalPayload.mapping,unit:2}},tokens.other)).status,400);
const {parseCsvTable,mappedProducts}=await import('file://'+root+'/apps/web/public/ai-csv-parser.js');
const arabic=mappedProducts(parseCsvTable('\uFEFFbarcode\tname\tunit\tpackQuantity\n4006381333931\t"برغر; أصلي"\tقطع\t32'),undefined,'ar');assert.equal(arabic[0].name,'برغر; أصلي');assert.equal(arabic[0].packQuantity,32);
assert.throws(()=>mappedProducts(parseCsvTable('barcode,name,unit,packQuantity\n4006381333931,Test,piece,32'),{barcode:0,name:1,unit:2,packQuantity:3,language:9}));
const consumedPlan=await call('purchasing?days=30',null,tokens.buyer);assert(consumedPlan.items.find(x=>x.id===st.id).daily>0);await query('UPDATE ai_accounts SET minimum_order_cents=100000 WHERE id=$1',[ids.supplier]);const groupedPlan=(await call('purchasing',null,tokens.buyer)).items.find(x=>x.id===st.id);assert.equal(groupedPlan.offers[0].packs,Math.max(Number(groupedPlan.offers[0].minimum_packs),Math.ceil(groupedPlan.shortage/Number(groupedPlan.offers[0].pack_quantity))));await query('UPDATE ai_accounts SET minimum_order_cents=0 WHERE id=$1',[ids.supplier]);
console.log('Barcode API passed: shared 32-piece pack, CSV rollback, review rights/conflicts, 3 packs = 96, idempotency, saved mapping and private stock.');

// Supplier API: isolated product imports, availability, polling and immutable 2% order snapshots.
assert.equal((await call('supplier-connectors',{name:'Not supplier'},tokens.buyer)).status,403);
const supplierKey=await call('supplier-connectors',{name:'Supplier ERP'},tokens.supplier);
const supplierConnector=(await call('supplier-connectors',null,tokens.supplier)).connectors[0];
assert.equal((await call('v1/supplier/status',null,supplierKey.token)).status,401);
await call('supplier-connector-status',{id:supplierConnector.id,active:true},tokens.supplier);
assert.equal((await call('v1/supplier/status',null,supplierKey.token)).commissionBps,200);
assert.equal((await call('v1/status',null,supplierKey.token)).status,401);
assert.equal((await call('v1/supplier/status',null,tokens.supplier)).status,401);
const apiProduct={externalCode:'erp-patties-32',name:'API Patties',unit:'piece',packQuantity:32,priceCents:1000,minimumPacks:1,active:true,available:true};
const importBody={requestId:crypto.randomUUID(),products:[apiProduct]};
const imported=await call('v1/supplier/products',importBody,supplierKey.token);assert.equal(imported.status,200);assert.equal(imported.imported,1);
assert.equal((await call('v1/supplier/products',importBody,supplierKey.token)).duplicate,true);
assert.equal((await call('v1/supplier/products',{...importBody,products:[{...apiProduct,priceCents:999}]},supplierKey.token)).status,409);
const countBefore=(await query('SELECT count(*) FROM ai_products')).rows[0].count;
assert.equal((await call('v1/supplier/products',{requestId:crypto.randomUUID(),products:[{...apiProduct,externalCode:'new-valid'},{...apiProduct,externalCode:'bad',packQuantity:32.5}]},supplierKey.token)).status,400);
assert.equal((await query('SELECT count(*) FROM ai_products')).rows[0].count,countBefore);
await call('v1/supplier/products',{requestId:crypto.randomUUID(),products:[{...apiProduct,available:false}]},supplierKey.token);
assert.equal((await call('catalog?q=API%20Patties',null,tokens.buyer)).products.length,0);
assert.equal((await call('orders',{...orderBody,productId:imported.products[0].id,requestKey:crypto.randomUUID()},tokens.buyer)).status,404);
await call('v1/supplier/products',{requestId:crypto.randomUUID(),products:[{...apiProduct,priceCents:1100}]},supplierKey.token);
await call('v1/supplier/products',importBody,supplierKey.token);
const supplierProducts=(await call('v1/supplier/products',null,supplierKey.token)).products;
assert.equal(Number(supplierProducts.find(p=>p.external_code===apiProduct.externalCode).price_cents),1100);
const pattiesStock=(await call('stock',{locationId:loc.id,name:'Z Patties',unit:'piece',quantity:0,minimum:0},tokens.buyer)).stock;
const apiOrder=(await call('orders',{...orderBody,productId:imported.products[0].id,stockId:pattiesStock.id,requestKey:crypto.randomUUID(),expectedNetCents:2200,commissionBps:0},tokens.buyer)).order;
assert.equal(Number(apiOrder.commission_cents),44);assert.equal(apiOrder.commission_bps,200);
const poll=await call('v1/supplier/orders',null,supplierKey.token);assert.ok(poll.orders.some(o=>o.id===apiOrder.id));assert.ok(poll.nextCursor);
assert.equal((await call('v1/supplier/orders?cursor=invalid',null,supplierKey.token)).status,400);
assert.equal((await call('v1/supplier/orders/'+apiOrder.id+'/accept',{},supplierKey.token)).status,200);
assert.equal((await call('v1/supplier/orders/'+apiOrder.id+'/accept',{},supplierKey.token)).duplicate,true);
assert.ok((await call('v1/supplier/orders?cursor='+encodeURIComponent(poll.nextCursor),null,supplierKey.token)).orders.some(o=>o.id===apiOrder.id&&o.status==='accepted'));
assert.equal((await call('v1/supplier/orders/'+apiOrder.id+'/receive',{},supplierKey.token)).status,404);
assert.equal(Number((await query('SELECT quantity FROM ai_stock WHERE id=$1',[pattiesStock.id])).rows[0].quantity),0);
const otherSupplier=crypto.randomUUID();await query("INSERT INTO ai_accounts(id,email,password_hash,name,business_name,role,status) VALUES($1,'other-supplier@example.org',$2,'Other supplier','Other supplier','dealer','active')",[otherSupplier,passwordHash('testing-password-123')]);
const otherSupplierToken=(await call('login',{email:'other-supplier@example.org',password:'testing-password-123'})).token;
const foreignKey=await call('supplier-connectors',{name:'Other ERP'},otherSupplierToken);await call('supplier-connector-status',{id:foreignKey.connectorId,active:true},otherSupplierToken);
assert.equal((await call('v1/supplier/products',null,foreignKey.token)).products.length,0);
assert.equal((await call('v1/supplier/orders',null,foreignKey.token)).orders.length,0);
assert.equal((await call('v1/supplier/orders/'+apiOrder.id+'/accept',{},foreignKey.token)).status,404);
assert.equal((await call('supplier-connector-key',{id:supplierConnector.id},otherSupplierToken)).status,404);
assert.equal((await call('v1/supplier/orders/'+apiOrder.id+'/cancel',{},supplierKey.token)).status,200);
assert.equal((await call('v1/supplier/orders/'+apiOrder.id+'/cancel',{},supplierKey.token)).duplicate,true);
assert.equal(Number((await query('SELECT commission_cents FROM ai_orders WHERE id=$1',[apiOrder.id])).rows[0].commission_cents),0);
const newSupplierKey=await call('supplier-connector-key',{id:supplierConnector.id},tokens.supplier);
assert.equal((await call('v1/supplier/status',null,supplierKey.token)).status,401);
assert.equal((await call('v1/supplier/status',null,newSupplierKey.token)).status,200);
await call('supplier-connector-status',{id:supplierConnector.id,active:false},tokens.supplier);
assert.equal((await call('v1/supplier/status',null,newSupplierKey.token)).status,401);
const bulk=Array.from({length:101},(_,i)=>({...apiProduct,externalCode:'bulk-'+i,name:'Bulk product '+i}));
assert.equal((await call('v1/supplier/products',{requestId:crypto.randomUUID(),products:bulk.slice(0,100)},foreignKey.token)).imported,100);assert.equal((await call('v1/supplier/products',{requestId:crypto.randomUUID(),products:bulk.slice(100)},foreignKey.token)).imported,1);const firstProductPage=await call('v1/supplier/products',null,foreignKey.token);assert.equal(firstProductPage.products.length,100);const lastProductPage=await call('v1/supplier/products?after='+firstProductPage.nextAfter,null,foreignKey.token);assert.equal(lastProductPage.products.length,1);assert.equal(new Set([...firstProductPage.products,...lastProductPage.products].map(p=>p.id)).size,101);
await query("INSERT INTO ai_auth_attempts(key,count,expires_at) VALUES($1,600,now()+interval '15 minutes') ON CONFLICT(key) DO UPDATE SET count=600",[hash('supplier-api:'+foreignKey.connectorId)]);assert.equal((await call('v1/supplier/status',null,foreignKey.token)).status,429);await query('DELETE FROM ai_auth_attempts WHERE key=$1',[hash('supplier-api:'+foreignKey.connectorId)]);
await query("UPDATE ai_accounts SET status='suspended' WHERE id=$1",[otherSupplier]);assert.equal((await call('v1/supplier/status',null,foreignKey.token)).status,401);await query("UPDATE ai_accounts SET status='active' WHERE id=$1",[otherSupplier]);
console.log('Supplier API passed: atomic product validation, idempotent imports, availability gate, 2% snapshots, change cursor, isolated order actions, key rotation and pause.');
assert.equal((await call('admin/account',{id:ids.pending,action:'restore'},'admin-token')).status,409);
assert.equal((await call('admin/account',{id:ids.buyer,action:'suspend'},'admin-token')).status,200);
assert.equal((await call('me',null,tokens.buyer)).status,401);
assert.equal((await call('admin',null,'admin-token')).status,200);
const verification=crypto.randomBytes(32).toString('hex');await query("INSERT INTO ai_auth_tokens VALUES($1,$2,'verify',now()+interval '1 hour',NULL)",[hash(verification),ids.pending]);assert.equal((await call('verify',{token:verification})).status,200);assert.equal((await call('verify',{token:verification})).status,400);
const reset=crypto.randomBytes(32).toString('hex');await query("INSERT INTO ai_auth_tokens VALUES($1,$2,'reset',now()+interval '1 hour',NULL)",[hash(reset),ids.supplier]);assert.equal((await call('reset',{token:reset,password:'new-testing-password'})).status,200);assert.equal((await call('me',null,tokens.supplier)).status,401);assert.equal((await call('reset',{token:reset,password:'new-testing-password'})).status,400);

const markup=fs.readFileSync(root+'/apps/web/public/ai-workspace.html','utf8'),script=fs.readFileSync(root+'/apps/web/public/ai-workspace.js','utf8');
const browser=new JSDOM(markup,{url:'https://example.org/ai-workspace.html',runScripts:'outside-only'});const w=browser.window;w.HTMLElement.prototype.scrollIntoView=function(){};
w.fetch=async(path,opt={})=>{const result=await call(path.replace('/api/ai/',''),opt.body?JSON.parse(opt.body):undefined,opt.headers?.authorization?.replace('Bearer ',''));const {status,...value}=result;return {ok:status>=200&&status<300,status,json:async()=>value}};
tokens.supplier=(await call('login',{email:'supplier@example.org',password:'new-testing-password'})).token;
// An isolated received-order fixture tests full month payment, stale amounts and Berlin month boundaries.
const settlementOrder={id:crypto.randomUUID()};await query("INSERT INTO ai_orders(id,buyer_id,supplier_id,stock_id,product_id,product_name,unit,pack_quantity,packs,net_cents,commission_bps,commission_cents,status,request_key,delivery_date,received_at) SELECT $1,buyer_id,supplier_id,stock_id,product_id,product_name,unit,pack_quantity,packs,net_cents,commission_bps,commission_cents,'received',$2,delivery_date,now() FROM ai_orders WHERE id=$3",[settlementOrder.id,crypto.randomUUID(),placed.order.id]);
monthly=await call('admin/settlements?month='+settlementMonth+'&supplierId='+ids.supplier,null,'admin-token');assert(monthly.rows[0].overdue);const monthlyAmount=Number(monthly.rows[0].outstanding_cents);assert(monthlyAmount>0);
const monthPayment={month:settlementMonth,supplierId:ids.supplier,amountCents:monthlyAmount,reference:'bank-month',confirmed:true};assert.equal((await call('admin/settlements/payment',{...monthPayment,amountCents:monthlyAmount+1},'admin-token')).status,409);assert.equal((await call('admin/settlements/payment',monthPayment,'admin-token')).status,200);assert.equal((await call('admin/settlements/payment',monthPayment,'admin-token')).status,409);assert.equal(Number((await call('settlements?month='+settlementMonth,null,tokens.supplier)).rows[0].outstanding_cents),0);
await query("UPDATE ai_orders SET received_at='2026-09-30T22:30:00Z' WHERE id=$1",[settlementOrder.id]);assert((await call('settlements?month=2026-10',null,tokens.supplier)).details.some(o=>o.id===settlementOrder.id));assert(!(await call('settlements?month=2026-09',null,tokens.supplier)).details.some(o=>o.id===settlementOrder.id));
console.log('Monthly commission integration passed: received-only periods, Berlin boundary, tenant rights, verified full payment, stale amount rejection and audit deadlines.');
// Payment provider and notification are simulated; no real message or debit is sent.
assert.equal((await call('admin/collection',null,tokens.supplier)).status,403);assert.equal((await call('collection',null,tokens.other)).status,403);
const collectionCfg={enabled:false,requireMandate:true,issuer:{name:'Test issuer',address:'Testweg 1',postalCode:'10115',city:'Berlin',taxId:'TEST ONLY',creditorId:'TEST CREDITOR ONLY',confirmed:true}};
assert.equal((await call('admin/collection/settings',{...collectionCfg,enabled:true},'admin-token')).status,409);
assert.equal((await call('admin/collection/settings',collectionCfg,'admin-token')).status,200);assert.equal(await globalThis.aiCollectionModule.supplierMayTrade(ids.supplier),false);
assert.equal((await call('collection/consent',{confirmed:false},tokens.supplier)).status,400);assert.equal((await call('collection/consent',{confirmed:true},tokens.supplier)).status,200);assert.equal(await globalThis.aiCollectionModule.supplierMayTrade(ids.supplier),false);
const collectionOrder={id:crypto.randomUUID()};await query("INSERT INTO ai_orders(id,buyer_id,supplier_id,stock_id,product_id,product_name,unit,pack_quantity,packs,net_cents,commission_bps,commission_cents,status,request_key,delivery_date,received_at) SELECT $1,buyer_id,supplier_id,stock_id,product_id,product_name,unit,pack_quantity,packs,net_cents,commission_bps,commission_cents,'received',$2,delivery_date,'2026-09-15T12:00:00Z' FROM ai_orders WHERE id=$3",[collectionOrder.id,crypto.randomUUID(),placed.order.id]);
await call('admin/collection/prepare',{},'admin-token');await call('admin/collection/prepare',{},'admin-token');let collectionJob=(await call('admin/collection',null,'admin-token')).jobs.find(j=>j.month==='2026-09');assert(collectionJob);assert.equal((await query('SELECT count(*) FROM ai_collection_jobs WHERE month=$1',['2026-09'])).rows[0].count,1);
const oldProviderFetch=globalThis.fetch;const oldProviderEnv=Object.fromEntries(['AI_MOLLIE_API_KEY','SMTP_HOST','SMTP_USER','SMTP_PASSWORD','SMTP_FROM'].map(k=>[k,process.env[k]]));for(const k of Object.keys(oldProviderEnv))process.env[k]=k==='AI_MOLLIE_API_KEY'?'live_TEST_ONLY':'test-only';let providerPosts=0,providerPayment,providerChargeback=false;
globalThis.fetch=async(url,options={})=>{const path=new URL(url).pathname;let response;if(path.includes('/mandates/'))response={id:'mdt_mock',method:'directdebit',status:'valid'};else if(path.startsWith('/v2/customers/'))response={id:'cst_mock',email:path.endsWith('cst_wrong')?'wrong@example.org':'supplier@example.org'};else if(path==='/v2/payments'&&options.method==='POST'){providerPosts++;const b=JSON.parse(options.body);providerPayment={...b,id:'tr_mock',status:'paid'};response=providerPayment}else if(path==='/v2/payments/tr_mock')response={...providerPayment,...(providerChargeback?{amountChargedBack:{value:'0.01'}}:{})};else throw Error('Unexpected provider path '+path);return {ok:true,json:async()=>response}};
assert.equal((await call('admin/collection/verify',{supplierId:ids.supplier,customerId:'cst_wrong',mandateId:'mdt_mock'},'admin-token')).status,409);
assert.equal((await call('admin/collection/verify',{supplierId:ids.supplier,customerId:'cst_mock',mandateId:'mdt_mock'},'admin-token')).status,200);assert.equal(await globalThis.aiCollectionModule.supplierMayTrade(ids.supplier),true);
assert.equal((await call('admin/collection/settings',{...collectionCfg,enabled:true},'admin-token')).status,200);
assert.equal((await call('admin/collection/release',{id:collectionJob.id,grossCents:48,invoiceReference:'TEST-INVOICE',confirmed:true},'admin-token')).status,200);
assert.equal((await call('admin/commission-payment',{orderId:collectionOrder.id,reference:'double'},'admin-token')).status,409);
let notificationCalls=0;await globalThis.aiCollectionModule.collectionTick({sendNotice:async()=>{notificationCalls++}});assert.equal(notificationCalls,1);assert.equal(providerPosts,0);
await globalThis.aiCollectionModule.collectionTick({sendNotice:async()=>{notificationCalls++}});assert.equal(notificationCalls,1);assert.equal(providerPosts,0);
await query("UPDATE ai_collection_jobs SET due_at=now()-interval '1 day',notified_at=now()-interval '15 days' WHERE id=$1",[collectionJob.id]);await globalThis.aiCollectionModule.collectionTick({sendNotice:async()=>{}});assert.equal(providerPosts,1);await globalThis.aiCollectionModule.collectionTick({sendNotice:async()=>{}});assert.equal(providerPosts,1);assert.equal((await query('SELECT state FROM ai_collection_jobs WHERE id=$1',[collectionJob.id])).rows[0].state,'paid');assert.equal((await query('SELECT reference FROM ai_commission_payments WHERE order_id=$1',[collectionOrder.id])).rows[0].reference,'Mollie tr_mock');const stableProvider=globalThis.fetch;globalThis.fetch=async()=>({ok:false,json:async()=>({})});await globalThis.aiCollectionModule.collectionTick({sendNotice:async()=>{}});assert.equal((await query('SELECT state FROM ai_collection_jobs WHERE id=$1',[collectionJob.id])).rows[0].state,'paid');globalThis.fetch=stableProvider;
assert.equal(globalThis.aiInvoiceModule.supportsInvoiceFormat('2026-12-31',30000,'standard'),true);assert.equal(globalThis.aiInvoiceModule.supportsInvoiceFormat('2027-01-01',30000,'standard'),false);assert.equal(globalThis.aiInvoiceModule.supportsInvoiceFormat('2027-01-01',25000,'standard'),true);assert.equal(globalThis.aiInvoiceModule.supportsInvoiceFormat('2027-01-01',30000,'small'),true);
assert.deepEqual(globalThis.aiInvoiceModule.invoiceAmounts(40,'standard'),{netCents:40,taxCents:8,grossCents:48,taxRate:19});assert.equal(globalThis.aiInvoiceModule.invoiceAmounts(3,'standard').taxCents,1);assert.equal(globalThis.aiInvoiceModule.invoiceAmounts(40,'small').taxCents,0);
const autoIssuer={...collectionCfg.issuer,country:'DE',taxMode:'standard',taxConfirmed:true};assert.equal((await call('admin/collection/settings',{...collectionCfg,enabled:true,autoInvoices:true,issuer:{...autoIssuer,taxConfirmed:false}},'admin-token')).status,409);
assert.equal((await call('admin/collection/settings',{...collectionCfg,enabled:true,autoInvoices:true,issuer:autoIssuer},'admin-token')).status,200);
const autoOrderId=crypto.randomUUID();await query("INSERT INTO ai_orders(id,buyer_id,supplier_id,stock_id,product_id,product_name,unit,pack_quantity,packs,net_cents,commission_bps,commission_cents,status,request_key,delivery_date,received_at) SELECT $1,buyer_id,supplier_id,stock_id,product_id,product_name,unit,pack_quantity,packs,net_cents,commission_bps,commission_cents,'received',$2,delivery_date,'2026-08-15T12:00:00Z' FROM ai_orders WHERE id=$3",[autoOrderId,crypto.randomUUID(),placed.order.id]);
await globalThis.aiCollectionModule.collectionTick({sendNotice:async()=>{}});let autoJob=(await call('admin/collection',null,'admin-token')).jobs.find(j=>j.month==='2026-08');assert.equal(autoJob.state,'draft');assert.match(autoJob.reason,/Rechnungsprofil/);
const invoiceProfile={legalName:'Test supplier <script>alert(1)</script>',address:'Testweg 2',postalCode:'10115',city:'Berlin',country:'DE',email:'supplier@example.org',electronicConsent:true};assert.equal((await call('collection/profile',{...invoiceProfile,electronicConsent:false},tokens.supplier)).status,400);assert.equal((await call('collection/profile',{...invoiceProfile,country:'AT'},tokens.supplier)).status,400);assert.equal((await call('collection/profile',invoiceProfile,tokens.supplier)).status,200);
await globalThis.aiCollectionModule.collectionTick({sendNotice:async()=>{}});autoJob=(await call('admin/collection',null,'admin-token')).jobs.find(j=>j.id===autoJob.id);assert.equal(autoJob.state,'notified');assert.equal(Number(autoJob.gross_cents),48);assert.equal(autoJob.invoice_available,true);await assert.rejects(query("UPDATE ai_commission_invoices SET invoice_number='MODIFIED' WHERE job_id=$1",[autoJob.id]),/darf nicht verändert/);
const invoice=await call('collection/invoices/'+autoJob.id,null,tokens.supplier);assert.equal(invoice.status,200);assert.match(invoice.invoiceNumber,/^BAI-/);assert.match(invoice.html,/&lt;script&gt;/);assert(!invoice.html.includes('<script>'));assert.match(invoice.html,/2026-08-31/);assert.match(invoice.html,/Umsatzsteuer 19/);
await assert.rejects(globalThis.aiInvoiceModule.invoiceRoutes('/api/ai/collection/invoices/'+autoJob.id,'GET',{}, {id:otherSupplier},false),e=>e.status===404);
assert.equal((await call('collection/profile',{...invoiceProfile,legalName:'Changed later'},tokens.supplier)).status,200);await globalThis.aiCollectionModule.collectionTick({sendNotice:async()=>{}});assert.equal((await query('SELECT count(*) FROM ai_commission_invoices WHERE job_id=$1',[autoJob.id])).rows[0].count,1);assert.equal((await call('collection/invoices/'+autoJob.id,null,tokens.supplier)).html,invoice.html);assert.equal(providerPosts,1);
console.log('Automatic invoices passed: explicit tax/profile consent, blocked missing profile, cent rounding, unique immutable invoice snapshot, tenant isolation and safe HTML.');
providerChargeback=true;await globalThis.aiCollectionModule.collectionTick({sendNotice:async()=>{}});assert.equal((await query('SELECT state FROM ai_collection_jobs WHERE id=$1',[collectionJob.id])).rows[0].state,'exception');assert.equal(providerPosts,1);
assert.equal((await call('collection/revoke',{},tokens.supplier)).status,200);assert.equal(await globalThis.aiCollectionModule.supplierMayTrade(ids.supplier),false);
assert.equal((await call('admin/collection/settings',{enabled:false,requireMandate:false,issuer:{}},'admin-token')).status,200);globalThis.fetch=oldProviderFetch;for(const [k,v]of Object.entries(oldProviderEnv)){if(v===undefined)delete process.env[k];else process.env[k]=v}
console.log('SEPA automation passed with simulated provider: explicit consent, verified mandate, blocked setup, monthly deduplication, notification delay, single debit, verified payment booking and chargeback exception.');
// Multi-supplier cart: whole-cart validation, grouped minimums and durable replay.
const cartSupplier=crypto.randomUUID(),cartLoc=crypto.randomUUID(),cartStock=crypto.randomUUID();
await query("INSERT INTO ai_accounts(id,email,password_hash,name,business_name,role,status,address,city) VALUES($1,'cart-supplier@example.org',$2,'Cart Supplier','Cart Supplier','dealer','active','Shopweg 1','Berlin')",[cartSupplier,passwordHash('testing-password-123')]);
await query("INSERT INTO ai_locations(id,account_id,name,address) VALUES($1,$2,'Cart Site','Cartweg 2')",[cartLoc,ids.other]);await query("INSERT INTO ai_stock(id,account_id,location_id,name,unit) VALUES($1,$2,$3,'Cart Ingredient','piece')",[cartStock,ids.other,cartLoc]);
const cartProducts=[crypto.randomUUID(),crypto.randomUUID(),crypto.randomUUID()];
for(let i=0;i<3;i++)await query("INSERT INTO ai_products(id,supplier_id,name,unit,pack_quantity,price_cents,category) VALUES($1,$2,$3,'piece',32,$4,'TK')",[cartProducts[i],i===2?cartSupplier:ids.supplier,'Cart Product '+i,i===2?500:800]);
await query('UPDATE ai_accounts SET minimum_order_cents=1500 WHERE id=$1',[ids.supplier]);
const cartBody={lines:cartProducts.map(productId=>({productId,stockId:cartStock,packs:1})),deliveryDate:'2026-10-04'};
assert.equal((await call('cart/preview',cartBody,tokens.supplier)).status,403);assert.equal((await call('cart/preview',{...cartBody,lines:[{...cartBody.lines[0],stockId:st.id}]},tokens.other)).status,400);
let cartPreview=await call('cart/preview',cartBody,tokens.other);assert.equal(cartPreview.status,200);assert.equal(cartPreview.canOrder,true);assert.equal(cartPreview.quote.groups.length,2);assert.equal(cartPreview.quote.netCents,2100);assert.equal(cartPreview.quote.groups.find(g=>g.supplierId===ids.supplier).netCents,1600);assert.equal(cartPreview.quote.groups[0].lines[0].packQuantity,'32.000');
const smallPreview=await call('cart/preview',{...cartBody,lines:cartBody.lines.slice(0,1)},tokens.other);assert.equal(smallPreview.canOrder,false);assert.equal(smallPreview.warnings.length,1);
const cartCheckout={...cartBody,quote:cartPreview.quote,requestKey:crypto.randomUUID(),confirmed:true};
assert.equal((await call('cart/checkout',{...cartCheckout,confirmed:false},tokens.other)).status,400);
await query('UPDATE ai_products SET price_cents=price_cents+1 WHERE id=$1',[cartProducts[2]]);assert.equal((await call('cart/checkout',cartCheckout,tokens.other)).status,400);await query('UPDATE ai_products SET price_cents=price_cents-1 WHERE id=$1',[cartProducts[2]]);
await query("UPDATE ai_accounts SET delivery_terms='Changed' WHERE id=$1",[cartSupplier]);assert.equal((await call('cart/checkout',cartCheckout,tokens.other)).status,400);await query("UPDATE ai_accounts SET delivery_terms='' WHERE id=$1",[cartSupplier]);
await query('UPDATE ai_products SET available=false WHERE id=$1',[cartProducts[2]]);assert.equal((await call('cart/checkout',cartCheckout,tokens.other)).status,400);assert.equal(Number((await query('SELECT count(*) FROM ai_orders WHERE checkout_id=$1',[cartCheckout.requestKey])).rows[0].count),0);await query('UPDATE ai_products SET available=true WHERE id=$1',[cartProducts[2]]);
assert.equal((await call('cart/preview',{...cartBody,lines:[cartBody.lines[0],cartBody.lines[0]]},tokens.other)).status,400);
const cartPlaced=await call('cart/checkout',cartCheckout,tokens.other);assert.equal(cartPlaced.status,201);assert.equal(cartPlaced.orders.length,3);assert.equal(new Set(cartPlaced.orders.map(o=>o.supplier_order_id)).size,2);assert.equal(cartPlaced.orders.reduce((n,o)=>n+Number(o.commission_cents),0),42);assert(cartPlaced.orders.every(o=>o.commission_bps===200));
const cartReplay=await call('cart/checkout',cartCheckout,tokens.other);assert.equal(cartReplay.status,200);assert.equal(cartReplay.replayed,true);assert.deepEqual(cartReplay.orders.map(o=>o.id),cartPlaced.orders.map(o=>o.id));assert.equal((await call('cart/checkout',{...cartCheckout,deliveryDate:'2026-10-05'},tokens.other)).status,400);
assert.equal(Number((await query('SELECT count(*) FROM ai_orders WHERE checkout_id=$1',[cartCheckout.requestKey])).rows[0].count),3);
for(const o of cartPlaced.orders)assert.equal((await call('orders/'+o.id+'/cancel',{},tokens.other)).status,200);
await query('UPDATE ai_accounts SET minimum_order_cents=0 WHERE id=$1',[ids.supplier]);await query('UPDATE ai_products SET active=false WHERE id=ANY($1::uuid[])',[cartProducts]);
assert.equal((await call('products',{name:'Bad Image',unit:'piece',packQuantity:1,priceCents:1,minimumPacks:1,imageData:'data:image/svg+xml;base64,xxx'},tokens.supplier)).status,400);
const tinyPng='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jP1sAAAAASUVORK5CYII=';assert.equal((await call('products',{id:product.id,name:'Mehl',unit:'kg',packQuantity:5,priceCents:1000,minimumPacks:1,category:'Backzutaten',imageData:tinyPng},tokens.supplier)).status,200);const categoryPage=await call('catalog?category=Backzutaten',null,tokens.other);assert.equal(categoryPage.total,1);assert.equal(categoryPage.products[0].image_data,tinyPng);assert(categoryPage.categories.includes('Backzutaten'));assert.equal((await call('catalog?offset=-1',null,tokens.other)).status,400);assert.equal((await call('catalog?category=Backzutaten&offset=40',null,tokens.other)).products.length,0);
console.log('Shop/cart API passed: supplier minimum across products, tenant checks, atomic unavailable/price/terms rejection, 32-piece packs, two supplier orders, exact 2% and durable duplicate suppression.');
const csvParser=await import('file://'+root+'/apps/web/public/ai-csv-parser.js');w.csvParser=csvParser;w.eval(fs.readFileSync(root+'/apps/web/public/ai-barcodes.js','utf8').replace("import {parseCsvTable,suggestMapping} from './ai-csv-parser.js';","const {parseCsvTable,suggestMapping}=window.csvParser;"));w.eval(fs.readFileSync(root+'/apps/web/public/ai-ads.js','utf8'));w.eval(fs.readFileSync(root+'/apps/web/public/ai-settlements.js','utf8'));w.eval(fs.readFileSync(root+'/apps/web/public/ai-collection.js','utf8'));w.eval(script);const d=w.document;
async function until(test){for(let i=0;i<150;i++){if(test())return;await new Promise(r=>setTimeout(r,10))}throw Error('UI wait timed out: '+d.getElementById('notice').textContent)}
function submit(kind,values){const form=d.querySelector('[data-form="'+kind+'"]');assert(form,'form '+kind+' exists');for(const [key,value]of Object.entries(values))form.elements.namedItem(key).value=value;form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}))}
d.querySelector('[data-eye]').click();assert.equal(d.getElementById('password').type,'text');d.querySelector('[data-eye]').click();assert.equal(d.getElementById('password').type,'password');
d.querySelector('[data-auth="register"]').click();assert.equal(d.getElementById('role').options.length,4);d.querySelector('[data-auth="login"]').click();
submit('login',{email:'other@example.org',password:'testing-password-123'});await until(()=>d.querySelector('[data-view="stock"]'));
d.querySelector('[data-view="stock"]').click();await until(()=>d.querySelector('[data-form="location"]'));
submit('location',{name:'UI Teststandort',address:'UI Weg 1'});await until(()=>d.querySelector('#locationId option'));
submit('stock',{name:'UI Mehl',quantity:'0',minimum:'5'});await until(()=>d.querySelector('[data-adjust]'));
d.querySelector('[data-view="connections"]').click();await until(()=>d.querySelector('[data-form="connector"]'));
submit('connector',{name:'UI Connector'});await until(()=>d.querySelector('#connection-extra input[readonly]'));const uiKey=d.querySelector('#connection-extra input').value;
d.querySelector('[data-view="connections"]').click();await until(()=>d.querySelector('[data-key-rotate]'));w.confirm=()=>true;d.querySelector('[data-key-rotate]').click();await until(()=>d.querySelector('#connection-extra input[readonly]'));assert.notEqual(d.querySelector('#connection-extra input').value,uiKey);assert.match(d.getElementById('connection-extra').textContent,/bisherige Schlüssel/);
console.log('Connector DOM passed: key creation, visible rotation action and replacement key.');
d.querySelector('[data-view="catalog"]').click();await until(()=>d.querySelector('[data-form="search"]'));
submit('search',{q:'Mehl'});await until(()=>d.querySelector('[data-buy]'));assert.equal(d.getElementById('search').value,'Mehl');
d.querySelector('[data-buy]').click();submit('buy',{packs:'2'});await until(()=>d.querySelector('[data-form="cart-preview"]'));assert.match(d.getElementById('content').textContent,/Dein Warenkorb/);submit('cart-preview',{deliveryDate:'2026-10-02'});await until(()=>d.querySelector('[data-form="cart-checkout"]'));d.querySelector('[data-form="cart-checkout"] input[name="confirmed"]').checked=true;submit('cart-checkout',{});await until(()=>d.querySelector('[data-cancel]'));assert.match(d.getElementById('content').textContent,/Gesendet/);
const uiStock=(await call('stock',null,tokens.other)).stock.find(x=>x.name==='UI Mehl');await query("UPDATE ai_stock SET name='Mehl',quantity=0,minimum=5 WHERE id=$1",[uiStock.id]);const beforePlanning=Number((await query('SELECT count(*) FROM ai_orders')).rows[0].count);d.querySelector('[data-view="purchasing"]').click();await until(()=>d.querySelector('[data-form="planning-cart"] select option[value="'+product.id+'"]'));const planningSelect=d.querySelector('[data-form="planning-cart"] select');planningSelect.value=product.id;submit('planning-cart',{});await until(()=>d.querySelector('[data-form="cart-preview"]'));assert.equal(d.querySelector('[name="packs-0"]').value,'1');assert.equal(Number((await query('SELECT count(*) FROM ai_orders')).rows[0].count),beforePlanning);d.querySelector('[data-cart-remove]').click();await until(()=>d.getElementById('content').textContent.includes('Dein Warenkorb ist leer'));console.log('Cart DOM passed: review and explicit checkout; purchasing import rounds packs and sends no order.');
d.querySelector('[data-view="barcodes"]').click();await until(()=>d.querySelector('[data-barcode-use]'));
const barcodeSearch=d.querySelector('[data-barcode-form="search"]');barcodeSearch.elements.barcode.value=barcode;barcodeSearch.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.querySelector('[data-barcode-use]')&&!d.querySelector('[data-barcode-form="search"] [type="submit"]').disabled);
d.querySelector('[data-barcode-use]').click();const receiptForm=d.querySelector('[data-barcode-form="receive"]');receiptForm.elements.packs.value='3';receiptForm.elements.packs.dispatchEvent(new w.Event('input',{bubbles:true}));assert.match(receiptForm.textContent,/96 Stück Lagerzugang/);receiptForm.elements.confirmed.checked=true;receiptForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.getElementById('barcode-receive').textContent.includes('96 Einheiten gebucht'));
console.log('Barcode DOM passed: catalog tab, scan input lookup, stored pack size, calculated total and stock receipt.');
const csvForm=d.querySelector('[data-barcode-form="csv"]');csvForm.elements.language.value='tr';
Object.defineProperty(csvForm.elements.file,'files',{value:[{size:100,text:async()=> 'Artikelnummer;Titel;Einheit;Anzahl\n4006381333931;İstanbul Köfte;adet;32'}]});
csvForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.querySelector('[data-barcode-form="csv-map"]'));
const mapForm=d.querySelector('[data-barcode-form="csv-map"]');for(const [key,value]of Object.entries({barcode:0,name:1,unit:2,packQuantity:3}))mapForm.elements.namedItem(key).value=String(value);
mapForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.querySelector('[data-csv-import]'));assert.match(d.getElementById('csv-preview').textContent,/İstanbul Köfte/);assert.match(d.getElementById('csv-preview').textContent,/tr/);
mapForm.elements.name.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.querySelector('[data-csv-import]'),null);
mapForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.querySelector('[data-csv-import]'));d.querySelector('[data-csv-import]').click();await until(()=>d.getElementById('csv-mapping').textContent==='');
assert.equal((await call('barcodes?q='+encodeURIComponent('İstanbul Köfte'),null,tokens.other)).entries[0].language,'tr');
console.log('CSV mapping passed: reordered columns, preview without writes, Unicode product names, language metadata, invalid mapping rejection and DOM preview/import.');
w.localStorage.setItem('bringness-ai-language','de');w.eval(fs.readFileSync(root+'/apps/web/public/ai-language.js','utf8'));const language=d.getElementById('ai-language');language.value='tr';language.dispatchEvent(new w.Event('change',{bubbles:true}));await until(()=>d.querySelector('[data-view="purchasing"]').textContent==='Satın alma planlaması');assert.equal(d.documentElement.lang,'tr');assert.equal(d.querySelector('[data-view="orders"]').textContent,'Siparişler');language.value='en';language.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(d.querySelector('[data-view="orders"]').textContent,'Orders');language.value='de';language.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(d.querySelector('[data-view="orders"]').textContent,'Bestellungen');
d.querySelector('[data-view="purchasing"]').click();await until(()=>d.querySelector('[data-form="planning"]'));assert.match(d.getElementById('content').textContent,/28 Tage/);
d.querySelector('[data-action="logout"]').click();await until(()=>d.querySelector('[data-form="login"]'));submit('login',{email:'supplier@example.org',password:'new-testing-password'});await until(()=>d.querySelector('[data-view="commissions"]'));
d.querySelector('[data-view="supplier-api"]').click();await until(()=>d.querySelector('[data-form="supplier-connector"]'));submit('supplier-connector',{name:'UI supplier ERP'});await until(()=>d.querySelector('#supplier-api-key input'));const uiSupplierKey=d.querySelector('#supplier-api-key input').value;d.querySelector('[data-supplier-key]').click();await until(()=>d.querySelector('#supplier-api-key input')?.value!==uiSupplierKey);assert.match(d.getElementById('supplier-api-key').textContent,/bisherige Schlüssel/);d.querySelector('[data-supplier-status]').click();await until(()=>d.getElementById('notice').textContent==='Lieferanten-Verbindung aktualisiert.');console.log('Supplier DOM passed: key creation, rotation and activation.');
d.querySelector('[data-view="collection"]').click();await until(()=>d.querySelector('[data-collection="consent"]'));assert.match(d.getElementById('content').textContent,/kein SEPA-Mandat/);assert.equal(d.querySelector('[data-collection="settings"]'),null);assert(d.querySelector('[data-collection="profile"]'));assert(d.querySelector('[data-invoice-download]'));
d.querySelector('[data-view="settlements"]').click();await until(()=>d.querySelector('[data-settlement="filter"]'));assert.match(d.getElementById('content').textContent,/keine Rechnung/);assert.equal(d.querySelector('[data-settlement="payment"]'),null);
d.querySelector('[data-view="ads"]').click();await until(()=>d.querySelector('[data-ad-form="submit"]'));
const adForm=d.querySelector('[data-ad-form="submit"]');adForm.elements.kind.value='brand';adForm.elements.title.value='UI Kampagne';adForm.elements.description.value='Werbung über den Lieferantenbereich';adForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.getElementById('content').textContent.includes('UI Kampagne'));assert.match(d.getElementById('content').textContent,/Zur Prüfung/);assert.equal(d.querySelector('[data-ad-action="approve"]'),null);
await w.BringnessAds.render({api:async(path,body)=>{const r=await call(path,body,'admin-token');if(r.status!==200)throw Error(r.error);return r},admin:true,notice:()=>{}});assert(d.querySelector('[data-ad-form="quote"]'));assert(d.querySelector('[data-ad-action="reject"]'));assert.equal(d.querySelector('[data-ad-form="submit"]'),null);
console.log('Advertising DOM passed: supplier submission and restricted approval controls.');
d.querySelector('[data-view="commissions"]').click();await until(()=>d.getElementById('content').textContent.includes('bank-test'));assert.match(d.getElementById('content').textContent,/Bezahlt/);assert.equal(d.querySelector('[data-form="commission-payment"]'),null);
d.querySelector('[data-view="products"]').click();await until(()=>d.getElementById('product-filter'));const filter=d.getElementById('product-filter');filter.value='xyz';filter.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.querySelector('#content tbody tr').hidden,true);filter.value='Mehl';filter.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal([...d.querySelectorAll('#content tbody tr')].find(r=>r.cells[0].textContent==='Mehl').hidden,false);
const mehlRow=[...d.querySelectorAll('#content tbody tr')].find(r=>r.cells[0].textContent==='Mehl');mehlRow.querySelector('[data-product]').click();const productEdit=d.querySelector('[data-form="product"]');assert.equal(productEdit.elements.namedItem('available').checked,true);productEdit.elements.namedItem('available').checked=false;productEdit.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>!d.querySelector('[data-form="product"] input[name="id"]').value);assert.equal((await call('catalog?q=Mehl',null,tokens.other)).products.filter(p=>p.id===product.id).length,0);
language.value='tr';language.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal([...d.querySelectorAll('#content tbody tr')].find(r=>r.cells[0].textContent==='Mehl').cells[0].textContent,'Mehl');assert.equal(d.querySelector('[data-form="product"] input[name="name"]').value,'');
console.log('Expansion passed: tenant-private purchasing, pack rounding, incoming orders, 2% ledger, admin-only payment evidence and persistent language switching.');
w.close();console.log('DOM workflow passed: eye, role registration, login, location, stock, catalog search and order submission.');
console.log('Embedded PostgreSQL integration passed: migrations, tenant isolation, catalog, order locks/idempotency, stock receipt, cancellation, admin suspension, verification and reset.');await db.close();
