import assert from 'node:assert/strict';import crypto from 'node:crypto';import {Readable} from 'node:stream';import {PGlite} from '@electric-sql/pglite';import {JSDOM} from 'jsdom';import fs from 'node:fs';
import {createPersonnel,migratePersonnel,pinHash,pinMatches} from '../personnel.js';
import {activateStaff} from '../staff-self-activation.js';
import {migrateTransactionalMail} from '../transactional-mail.js';
Object.assign(process.env,{SMTP_HOST:'smtp.example.test',SMTP_USER:'test',SMTP_PASSWORD:'test-only',SMTP_FROM:'test@example.test'});
const db=new PGlite();await db.waitReady;const query=async(sql,args)=>{if(args===undefined&&sql.includes(';')){await db.exec(sql);return {rows:[],rowCount:0}}const r=await db.query(sql,args);return {...r,rowCount:r.affectedRows||r.rows.length}};const pool={query,connect:async()=>({query,release(){}})},id=()=>crypto.randomUUID(),hash=s=>crypto.createHash('sha256').update(s).digest('hex');
await db.exec(`CREATE TABLE companies(id uuid PRIMARY KEY);CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid,role text,status text,email text UNIQUE,display_name text,password_hash text,must_change_password boolean DEFAULT false);CREATE TABLE sessions(token_hash text PRIMARY KEY,user_id uuid,expires_at timestamptz);CREATE TABLE restaurants(id uuid PRIMARY KEY,company_id uuid,name text);CREATE TABLE staff_invitations(token_hash text PRIMARY KEY,user_id uuid,used_at timestamptz,expires_at timestamptz,self_setup boolean,created_at timestamptz DEFAULT now());CREATE TABLE employees(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),restaurant_id uuid,display_name text,role text,pin_hash text,user_id uuid,active boolean DEFAULT true);CREATE TABLE waiter_schedules(employee_id uuid,restaurant_id uuid,starts_at timestamptz,ends_at timestamptz);CREATE TABLE dining_tables(id uuid PRIMARY KEY,waiter_employee_id uuid,name text);CREATE TABLE orders(id uuid PRIMARY KEY,table_id uuid,status text);CREATE TABLE audit_log(company_id uuid,actor_user_id uuid,event_type text,entity_type text,entity_id uuid,payload jsonb);`);
await migratePersonnel(pool);await migratePersonnel(pool);await migrateTransactionalMail(pool);
const cid=id(),otherCid=id(),owner=id(),waiter=id(),other=id(),rid=id(),otherRid=id();await query('INSERT INTO companies VALUES($1),($2)',[cid,otherCid]);for(const [uid,company,role,t]of [[owner,cid,'owner','owner'],[waiter,cid,'waiter','waiter'],[other,otherCid,'owner','other']]){await query("INSERT INTO users(id,company_id,role,status,password_hash) VALUES($1,$2,$3,'active',$4)",[uid,company,role,crypto.scryptSync('AccountPass!',process.env.PASSWORD_PEPPER||'bringness-pos',64).toString('hex')]);await query("INSERT INTO sessions VALUES($1,$2,now()+interval '1 hour')",[hash(t),uid])}await query('INSERT INTO restaurants(id,company_id) VALUES($1,$2),($3,$4)',[rid,cid,otherRid,otherCid]);
const handle=createPersonnel(pool);async function call(path,b=null,t='owner',unlock='',extraHeaders={}){const req=Readable.from(b?[JSON.stringify(b)]:[]);Object.assign(req,{url:'/api/v1'+path,method:b?'POST':'GET',headers:{authorization:'Bearer '+t,'x-personnel-unlock':unlock,...extraHeaders}});let status,data;const handled=await handle(req,{writeHead(s){status=s},end(s){data=JSON.parse(s)}});return {...data,handled,status}}
assert.equal((await call('/employees',{})).status,403);assert.equal((await call('/personnel/access',null,'waiter')).canManage,false);assert.equal((await call('/personnel/setup',{password:'wrong',pin:'123456'})).status,403);
let unlocked=await call('/personnel/setup',{password:'AccountPass!',pin:'123456'});assert.equal(unlocked.status,200);const key=unlocked.unlockToken;assert.equal((await call('/employees',{},'owner',key)).handled,false);assert.equal((await call('/employees',{},'other',key)).status,403);
assert.equal((await call('/personnel/employees',{restaurantId:otherRid,name:'Fremd',role:'cashier',pin:'222222'},'owner',key)).status,404);
const employee=await call('/personnel/employees',{restaurantId:rid,name:'Küche',role:'kitchen',email:'kitchen@example.test'},'owner',key);assert.equal(employee.status,201);assert.equal(employee.emailStatus,'queued');
const invited=(await query('SELECT user_id,pin_hash FROM employees WHERE id=$1',[employee.id])).rows[0];assert.equal(invited.pin_hash,null);assert.equal((await query('SELECT status FROM users WHERE id=$1',[invited.user_id])).rows[0].status,'pending');
const setupToken='a'.repeat(64);await query("INSERT INTO staff_invitations(token_hash,user_id,expires_at,self_setup) VALUES($1,$2,now()+interval '1 hour',true)",[hash(setupToken),invited.user_id]);await activateStaff(pool,{token:setupToken,password:'Secure1!',stampPin:'222222'});
let b={restaurantId:rid,employeeId:employee.id,pin:'222222'};
assert.equal((await call('/personnel/clock',{...b,pin:'wrong'})).status,403);assert.equal((await call('/personnel/clock',b,'other')).status,404);assert.equal((await call('/personnel/clock',b)).state,'off');
assert.equal((await call('/personnel/clock',{...b,action:'pause',requestId:id()})).status,409);
const start={...b,action:'start',requestId:id()};assert.equal((await call('/personnel/clock',start)).state,'working');assert.equal((await call('/personnel/clock',start)).status,200);assert.equal((await query('SELECT count(*)::int n FROM personnel_time_entries')).rows[0].n,1);assert.equal((await call('/personnel/clock',{...b,action:'start',requestId:id()})).status,409);
for(const action of ['pause','resume','end'])assert.equal((await call('/personnel/clock',{...b,action,requestId:id()})).status,200);
let entries=await call('/personnel/entries?restaurantId='+rid,null,'owner',key);assert.equal(entries.entries.length,4);assert.equal((await call('/personnel/entries?restaurantId='+rid,null,'waiter',key)).status,403);
const entry=entries.entries[0],corrected=new Date(Date.parse(entry.effective_at)-60000).toISOString();assert.equal((await call('/personnel/correct',{restaurantId:rid,entryId:entry.id,effectiveAt:corrected,reason:'Beginn korrigiert'},'owner',key)).status,200);assert.equal((await query("SELECT count(*)::int n FROM audit_log WHERE event_type='personnel.time.corrected'")).rows[0].n,1);
assert.equal((await call('/personnel/correct',{restaurantId:rid,entryId:entry.id,effectiveAt:new Date().toISOString(),reason:'Ungültige Reihenfolge'},'owner',key)).status,400);
await query("UPDATE personnel_unlocks SET expires_at=now()-interval '1 second'");assert.equal((await call('/employees',{},'owner',key)).status,403);const again=await call('/personnel/unlock',{pin:'123456'});assert.equal(again.status,200);await call('/personnel/lock',{});assert.equal((await call('/employees',{},'owner',again.unlockToken)).status,403);
for(let i=0;i<5;i++)assert.equal((await call('/personnel/unlock',{pin:'999999'})).status,403);assert.equal((await call('/personnel/unlock',{pin:'123456'})).status,429);
assert(pinMatches('222222',pinHash('222222')));assert(!pinMatches('333333',pinHash('222222')));
assert(!JSON.stringify((await call('/personnel/people?restaurantId='+rid)).people).includes('pin_hash'));

// Phone stamping and service-account stamping are forbidden; own reports remain available.
await query('DELETE FROM personnel_attempts');
const serviceEmployee=(await query('INSERT INTO employees(restaurant_id,display_name,role,pin_hash,user_id) VALUES($1,$2,$3,$4,$5) RETURNING id',[rid,'Service','waiter',pinHash('333333'),waiter])).rows[0];
const phone={restaurantId:rid,employeeId:serviceEmployee.id,pin:'333333',action:'toggle',requestId:id()};
assert.equal((await call('/personnel/clock',{...b,action:'start',requestId:id()},'waiter')).status,403);
assert.equal((await call('/personnel/clock',phone,'waiter')).status,403);
assert.equal((await call('/personnel/clock',phone,'waiter')).status,403);
assert.equal((await query('SELECT duty_state FROM employees WHERE id=$1',[serviceEmployee.id])).rows[0].duty_state,'off');
for(const ua of ['Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)','Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/120 Mobile Safari/537.36','Windows Phone']){const blocked=await call('/personnel/clock',phone,'owner','',{'user-agent':ua});assert.equal(blocked.status,403);assert.equal(blocked.code,'CLOCK_AT_POS_ONLY');}
assert.equal((await call('/personnel/clock',phone,'owner','',{'sec-ch-ua-mobile':'?1'})).status,403);
assert.equal((await query('SELECT count(*)::int n FROM personnel_time_entries WHERE employee_id=$1',[serviceEmployee.id])).rows[0].n,0);
assert.equal((await call('/personnel/clock',phone,'owner')).state,'working');
assert.equal((await call('/personnel/clock',phone,'owner')).state,'working');
await query('INSERT INTO dining_tables VALUES($1,$2,$3)',[rid,serviceEmployee.id,'Tisch 1']);await query("INSERT INTO orders VALUES($1,$2,'open')",[id(),rid]);
const stopped=await call('/personnel/clock',{...phone,requestId:id()},'owner');assert.equal(stopped.state,'off');assert.equal(stopped.openTables[0].name,'Tisch 1');
assert.equal((await query('SELECT duty_state FROM employees WHERE id=$1',[serviceEmployee.id])).rows[0].duty_state,'off');
const ownReport=await call('/personnel/my-report?month=2026-10&employeeId='+employee.id,null,'waiter');
assert.equal(ownReport.status,200);assert.deepEqual(ownReport.totals.map(p=>p.employeeId),[serviceEmployee.id]);
assert.equal((await call('/personnel/people?restaurantId='+rid,null,'waiter')).status,403);
assert.equal((await call('/personnel/report?restaurantId='+rid,null,'waiter')).status,403);
assert.equal((await call('/personnel/my-report',null,'owner')).status,403);
await query('DELETE FROM personnel_unlocks');

// Exercise the real UI with names containing markup and separate cashier identity.
const html=fs.readFileSync(new URL('../../apps/web/public/pos/index.html',import.meta.url),'utf8'),dom=new JSDOM(html,{url:'https://pos.example/pos/',runScripts:'outside-only'}),w=dom.window;w.Headers=Headers;w.Request=Request;w.crypto.randomUUID=id;w.localStorage.setItem('bringness-pos-token','owner');w.document.getElementById('restaurant').innerHTML='<option value="'+rid+'">Restaurant</option>';w.fetch=async(url,opts={})=>{const path=String(url);if(path.includes('/bootstrap'))return {ok:true,json:async()=>({user:{name:'Inhaber'},restaurants:[{id:rid,name:'Restaurant',mode:'counter'}],products:[],categories:[],orders:[]})};if(path.includes('/billing/status'))return {ok:true,json:async()=>({features:[]})};if(path==='/health')return {ok:true,json:async()=>({status:'ok'})};if(!path.includes('/personnel/'))return {ok:true,json:async()=>({})};const headers=new Headers(opts.headers);const result=await call(String(url).replace('/api/v1',''),opts.body?JSON.parse(opts.body):null,'owner',headers.get('x-personnel-unlock')||'');return {ok:result.status<400,status:result.status,json:async()=>result}};w.AbortController=AbortController;w.alert=()=>{};w.eval(fs.readFileSync(new URL('../../apps/web/public/pos/app.js',import.meta.url),'utf8'));w.eval(fs.readFileSync(new URL('../../apps/web/public/pos/restaurant-owner.js',import.meta.url),'utf8'));w.eval(fs.readFileSync(new URL('../../apps/web/public/personnel-report.js',import.meta.url),'utf8'));w.eval(fs.readFileSync(new URL('../../apps/web/public/pos/personnel.js',import.meta.url),'utf8'));const wait=async f=>{for(let i=0;i<100;i++){if(f())return;await new Promise(r=>setTimeout(r,10))}throw Error('UI timeout: '+w.document.body.textContent)};
assert(!w.document.querySelector('#moreMenu a[href*="download"]'));assert.equal(w.document.querySelectorAll('#legalMenu [data-legal]').length,2);w.document.getElementById('personnelBtn').click();await wait(()=>w.document.querySelector('.personnel-dialog select'));w.document.querySelector('.personnel-dialog select').value=employee.id;w.document.querySelector('.personnel-dialog input').value='222222';w.document.querySelector('.personnel-dialog form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>w.document.querySelector('.personnel-dialog').textContent.includes('Bei der Arbeit'));assert.equal(w.localStorage.getItem('bringness-pos-token'),'owner');await query('DELETE FROM personnel_attempts');w.document.querySelector('[data-close]').click();const opening=w.showModule('personalmanagement');await wait(()=>w.document.querySelector('.personnel-dialog input[name=pin]'));w.document.querySelector('.personnel-dialog input[name=pin]').value='123456';w.document.querySelector('.personnel-dialog form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await opening;assert(w.document.getElementById('moduleBody').textContent.includes('Mitarbeiter & Rechte'));await w.showModule('stunden');await wait(()=>w.document.getElementById('moduleBody').textContent.includes('Drucken / PDF speichern'));assert(w.document.getElementById('moduleBody').textContent.includes('Drucken / PDF speichern'));assert(w.document.querySelector('input[type=month]'));await wait(()=>!w.document.querySelector('[data-report-print]').disabled);w.document.querySelector('[data-report-print]').click();const printFrame=w.document.querySelector('iframe[title="Druckansicht Arbeitszeiten"]');assert(printFrame.srcdoc.includes('Dienstbeginn'));assert(printFrame.srcdoc.includes('Pausenstunden'));assert(!printFrame.srcdoc.includes('222222'));printFrame.remove();await w.showModule('mitarbeiter');await wait(()=>w.document.getElementById('moduleBody').textContent.includes('Küche'));assert(w.document.getElementById('moduleBody').textContent.includes('Küche'));await w.showModule('kasse');assert.equal((await call('/employees',{},'owner',again.unlockToken)).status,403);w.close();
const mobile=new JSDOM(html,{url:'https://pos.example/pos/',runScripts:'outside-only'}).window;Object.defineProperty(mobile.navigator,'userAgent',{value:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)'});mobile.Headers=Headers;let mobileFetches=0;mobile.fetch=async()=>{mobileFetches++;return {ok:true,json:async()=>({})}};mobile.eval(fs.readFileSync(new URL('../../apps/web/public/pos/personnel.js',import.meta.url),'utf8'));assert.equal(mobile.document.getElementById('personnelBtn').disabled,true);mobile.document.getElementById('personnelBtn').click();assert.equal(mobileFetches,0);mobile.close();await db.close();console.log('Personnel passed: migration, tenant isolation, PIN setup/recovery/rate limit, session-bound unlock/expiry/lock, separate stamping, transitions, idempotency, corrections/audit and POS DOM.');

