import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {JSDOM} from 'jsdom';
import fs from 'node:fs';
const db=new PGlite();await db.waitReady;
const user='00000000-0000-4000-8000-000000000001',employee='00000000-0000-4000-8000-000000000002',restaurant='00000000-0000-4000-8000-000000000003',company='00000000-0000-4000-8000-000000000004',table='00000000-0000-4000-8000-000000000005';
await db.exec("CREATE TABLE employees(id uuid PRIMARY KEY,user_id uuid,restaurant_id uuid,active boolean,role text,duty_state text);CREATE TABLE restaurants(id uuid,company_id uuid,name text,mode text);CREATE TABLE dining_tables(id uuid PRIMARY KEY,restaurant_id uuid,waiter_employee_id uuid,name text,area text,status text,sort_order int);CREATE TABLE orders(id uuid,table_id uuid,source text,status text,created_at timestamptz,total_cents int);CREATE TABLE products(id uuid,restaurant_id uuid,name text,price_cents int,active boolean,ai_stock_available boolean);CREATE TABLE waiter_push_subscriptions(user_id uuid,endpoint text,subscription jsonb);");
await db.query("INSERT INTO employees VALUES($1,$2,$3,true,'waiter','off')",[employee,user,restaurant]);await db.query("INSERT INTO restaurants VALUES($1,$2,'Restaurant','restaurant')",[restaurant,company]);await db.query("INSERT INTO dining_tables VALUES($1,$2,$3,'Tisch 1','Saal','open',1)",[table,restaurant,employee]);await db.query("INSERT INTO orders VALUES(gen_random_uuid(),$1,'qr','open',now(),2500)",[table]);await db.query("INSERT INTO waiter_push_subscriptions VALUES($1,'https://push.example','{}')",[user]);
await db.exec("ALTER TABLE orders ALTER COLUMN id SET DEFAULT gen_random_uuid();ALTER TABLE orders ADD COLUMN restaurant_id uuid;ALTER TABLE orders ADD COLUMN closed_at timestamptz;ALTER TABLE products ADD COLUMN tax_rate numeric DEFAULT 19;CREATE TABLE order_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid,product_id uuid,product_name_snapshot text,unit_price_cents int,tax_rate_snapshot numeric,quantity int,guest_note text,correction_note text,corrected_at timestamptz,corrected_by uuid);");
await db.query('UPDATE orders SET restaurant_id=$1',[restaurant]);
await db.exec("CREATE TABLE categories(id uuid,name text,sort_order int);ALTER TABLE products ADD COLUMN category_id uuid;ALTER TABLE products ADD COLUMN description text;ALTER TABLE products ADD COLUMN image_url text;");
const product='00000000-0000-4000-8000-000000000006';await db.query("INSERT INTO products(id,restaurant_id,name,price_cents,active,ai_stock_available) VALUES($1,$2,'Waffel',1250,true,true)",[product,restaurant]);const qrOrder=(await db.query('SELECT id FROM orders')).rows[0].id;const qrItem=(await db.query("INSERT INTO order_items(order_id,product_id,product_name_snapshot,unit_price_cents,quantity) VALUES($1,$2,'Waffel',1250,2) RETURNING id",[qrOrder,product])).rows[0].id;
const pool={query:async(sql,args)=>{const r=await db.query(sql,args);return {...r,rowCount:r.affectedRows||r.rows.length}}};
pool.connect=async()=>({query:pool.query,release(){}});
const source=fs.readFileSync(new URL('../index.js',import.meta.url),'utf8'),lines=source.split('\n');
const guard=lines.find(l=>l.startsWith('if(p.startsWith("/api/v1/waiter/")&&!'));
const routes=['/api/v1/waiter/bootstrap','/api/v1/waiter/alerts','/api/v1/waiter/orders','/api/v1/waiter/orders/correct'].map(p=>lines.find(l=>l.startsWith('if(p==="'+p+'"')));
routes.push(lines.find(l=>l.startsWith('if(/^\\/api\\/v1\\/waiter\\/tables')));
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
const handler=new AsyncFunction('req','res','p','u','pool','auth','currentUser','requireFeature','json','body',guard+'\n'+routes.join('\n'));
async function request(path,b=null){const u=new URL('https://example'+path);let result;await handler({method:b?'POST':'GET'},{},u.pathname,u,pool,async()=>({id:user,company_id:company,role:'waiter',display_name:'Service'}),async()=>({id:user}),async()=>true,(_res,status,data)=>{result={...data,status}},async()=>b);return result}
const off=await request('/api/v1/waiter/bootstrap');assert.equal(off.employee.duty_state,'off');assert.equal(off.tables.length,1);assert.equal((await request('/api/v1/waiter/alerts')).orders.length,1);assert.equal((await request('/api/v1/waiter/tables/'+table)).status,200);
await db.query("UPDATE employees SET duty_state='working'");
const working=await request('/api/v1/waiter/bootstrap');assert.equal(working.tables.length,1);assert.equal((await request('/api/v1/waiter/alerts')).orders.length,1);
const pushSql=source.match(/const waiterPush=\(await c\.query\("([^"]+)"/)[1];assert.equal((await pool.query(pushSql,[table])).rowCount,1);
await db.query("UPDATE employees SET duty_state='paused'");assert.equal((await request('/api/v1/waiter/alerts')).orders.length,1);assert.equal((await pool.query(pushSql,[table])).rowCount,1);
await db.query("UPDATE employees SET duty_state='off'");assert.equal((await request('/api/v1/waiter/alerts')).dutyState,'off');assert.equal((await pool.query(pushSql,[table])).rowCount,1);assert.equal((await pool.query('SELECT id FROM orders')).rowCount,1);
// Off-duty staff can take an order and correct a QR order, only on assigned tables.
const created=await request('/api/v1/waiter/orders',{tableId:table,items:[{productId:product,qty:1}]});assert.equal(created.status,201);
assert.equal((await request('/api/v1/waiter/orders/correct',{orderId:qrOrder,itemId:qrItem,qty:1})).status,200);
assert.equal((await db.query('SELECT total_cents FROM orders WHERE id=$1',[qrOrder])).rows[0].total_cents,1250);
await db.query("UPDATE orders SET status='kitchen' WHERE id=$1",[qrOrder]);assert.equal((await request('/api/v1/waiter/orders/correct',{orderId:qrOrder,itemId:qrItem,qty:2})).status,400);
assert.equal((await request('/api/v1/waiter/orders/correct',{orderId:qrOrder,itemId:qrItem,qty:2,reason:'Gast korrigiert Menge'})).status,200);
await db.query("UPDATE orders SET status='paid' WHERE id=$1",[qrOrder]);assert.equal((await request('/api/v1/waiter/orders/correct',{orderId:qrOrder,itemId:qrItem,qty:0})).status,409);
await db.query('UPDATE dining_tables SET waiter_employee_id=NULL WHERE id=$1',[table]);assert.equal((await request('/api/v1/waiter/tables/'+table)).status,404);assert.equal((await request('/api/v1/waiter/orders',{tableId:table,items:[{productId:product,qty:1}]})).status,403);assert.equal((await request('/api/v1/waiter/orders/correct',{orderId:created.orderId,itemId:qrItem,qty:1})).status,409);
await db.query('UPDATE dining_tables SET waiter_employee_id=$1 WHERE id=$2',[employee,table]);await db.query('UPDATE employees SET active=false');assert.equal((await request('/api/v1/waiter/orders',{tableId:table,items:[{productId:product,qty:1}]})).status,403);await db.query('UPDATE employees SET active=true');
// Verify the actual phone UI shows off-duty state and provides private reporting.
const dom=new JSDOM(fs.readFileSync(new URL('../../apps/web/public/service/index.html',import.meta.url),'utf8'),{url:'https://example/service/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
w.localStorage.setItem('bringness-waiter-token','token');w.HTMLElement.prototype.scrollIntoView=()=>{};w.fetch=async url=>({ok:true,json:async()=>String(url).includes('/waiter/bootstrap')?off:String(url).includes('/waiter/alerts')?{orders:[],dutyState:'off',serverTime:new Date().toISOString()}:{month:'2026-10',totals:[],shifts:[],generatedAt:new Date().toISOString()}});
w.eval(fs.readFileSync(new URL('../../apps/web/public/personnel-report.js',import.meta.url),'utf8'));w.eval(fs.readFileSync(new URL('../../apps/web/public/service/app.js',import.meta.url),'utf8'));
await new Promise(resolve=>setTimeout(resolve,25));
assert(w.document.getElementById('dutyState').textContent.includes('Nicht eingestempelt'));assert.equal(w.document.querySelectorAll('[data-table]').length,1);assert.equal(w.document.getElementById('dutyForm'),null);assert(w.document.body.textContent.includes('am Kassengerät'));w.document.getElementById('myTimes').open=true;await new Promise(resolve=>setTimeout(resolve,25));assert(w.document.querySelector('[data-report-print]'));
const waitFor=async condition=>{for(let n=0;n<100;n++){if(condition())return;await new Promise(r=>setTimeout(r,10))}throw Error('Service UI did not finish')};
w.fetch=async(url,opts={})=>{const path=new URL(String(url),'https://example').pathname+new URL(String(url),'https://example').search;const result=path.startsWith('/api/v1/waiter/')?await request(path,opts.body?JSON.parse(opts.body):null):{month:'2026-10',totals:[],shifts:[],generatedAt:new Date().toISOString()};return {ok:!result.status||result.status<400,json:async()=>result}};
w.document.querySelector('[data-table]').click();await waitFor(()=>w.document.querySelector('[data-product]'));assert(w.document.querySelector('[data-correct]'));
w.prompt=()=> '2';w.document.querySelector('[data-correct]').click();await waitFor(()=>w.document.querySelector('[data-correct]')?.dataset.qty==='2');assert.equal((await db.query('SELECT total_cents FROM orders WHERE id=$1',[created.orderId])).rows[0].total_cents,2500);
const input=w.document.querySelector('[data-product]');input.value='1';input.dispatchEvent(new w.Event('input'));const before=(await db.query('SELECT count(*)::int n FROM orders')).rows[0].n;w.document.getElementById('send').click();w.document.getElementById('send').click();await waitFor(()=>w.document.getElementById('message').textContent==='Bestellung aufgenommen.');assert.equal((await db.query('SELECT count(*)::int n FROM orders')).rows[0].n,before+1);
// A missing Notification API must not stop incoming-order refresh.
const signalTimers=[];w.setTimeout=fn=>{signalTimers.push(fn);return signalTimers.length};let spoken='';w.SpeechSynthesisUtterance=class{constructor(text){this.text=text}};w.speechSynthesis={speak(utterance){spoken=utterance.text;assert.equal(utterance.lang,'de-DE');utterance.onend()}};
let signals=0;w.AudioContext=class{currentTime=0;destination={};resume(){return Promise.resolve()}createOscillator(){return {frequency:{},connect(){},start(){signals++},stop(){}}}createGain(){return {gain:{exponentialRampToValueAtTime(){}},connect(){}}}};
w.document.getElementById('notificationsBtn').click();await waitFor(()=>w.document.getElementById('message').textContent.includes('Bestellsignal aktiv'));assert.equal(signals,8);signalTimers.shift()();assert.equal(spoken,'');assert(w.document.getElementById('serviceMore').contains(w.document.getElementById('notificationsBtn')));assert.equal(signals,16);while(signalTimers.length)signalTimers.shift()();
await db.query("UPDATE orders SET status='open',created_at=now() WHERE id=$1",[qrOrder]);await w.checkAlerts();assert(w.document.getElementById('message').textContent.includes('Neue QR-Bestellung'));assert(signals>1);
// Category switches preserve quantities across groups, including uncategorized products.
assert.equal(w.document.getElementById('serviceMore').open,false);
w.fetch=async()=>({ok:true,json:async()=>({...off,products:[{id:'a',name:'Waffel',price_cents:500,category_id:'sweet',category:'Süß',image_url:'/waffel.jpg'},{id:'b',name:'Kaffee',price_cents:300,category_id:'drinks',category:'Getränke'},{id:'c',name:'Extra',price_cents:100}]})});await w.load();w.renderProducts();
assert.equal(w.document.querySelectorAll('[data-category]').length,3);w.document.querySelector('[data-category="sweet"]').click();assert(w.document.querySelector('.product-photo img'));
w.document.querySelector('[data-step="1"]').click();assert(w.document.getElementById('total').textContent.includes('5,00'));
w.document.querySelector('[data-category="drinks"]').click();assert.equal(w.document.querySelector('[data-product]').dataset.product,'b');w.document.querySelector('[data-step="1"]').click();assert(w.document.getElementById('total').textContent.includes('8,00'));
w.document.querySelector('[data-category="sweet"]').click();assert.equal(w.document.querySelector('[data-product]').value,'1');
w.document.querySelector('[data-category="uncategorized"]').click();assert.equal(w.document.querySelector('[data-product]').dataset.product,'c');
w.close();await db.close();
console.log('Service duty passed: actual SQL allows assigned-table service independently of duty state, retains open orders, removes phone stamping and preserves private monthly report.');
