import assert from 'node:assert/strict';import crypto from 'node:crypto';import {Readable} from 'node:stream';import {PGlite} from '@electric-sql/pglite';import {JSDOM} from 'jsdom';import fs from 'node:fs';
import {createRemoteSupport,migrateRemoteSupport,supportInput,safeDiagnostics} from '../remote-support-core.js';
const db=new PGlite();await db.waitReady;const query=async(sql,args)=>{if(args===undefined&&sql.includes(';')){await db.exec(sql);return {rows:[],rowCount:0}}const r=await db.query(sql,args);return {...r,rowCount:r.affectedRows||r.rows.length}};const pool={query,connect:async()=>({query,release(){}})};
await db.exec(`CREATE TABLE companies(id uuid PRIMARY KEY,name text);CREATE TABLE users(id uuid PRIMARY KEY,company_id uuid,role text,status text,must_change_password boolean DEFAULT false);CREATE TABLE sessions(token_hash text,user_id uuid,expires_at timestamptz);CREATE TABLE platform_admins(user_id uuid,active boolean);CREATE TABLE devices(id uuid PRIMARY KEY,company_id uuid,name text,device_key text,status text,platform text,app_version text,last_seen_at timestamptz);CREATE TABLE audit_log(company_id uuid,actor_user_id uuid,event_type text,entity_type text,entity_id uuid,payload jsonb);`);
await migrateRemoteSupport(pool);await migrateRemoteSupport(pool);
const id=()=>crypto.randomUUID(),company=id(),otherCompany=id(),admin=id(),owner=id(),other=id(),waiter=id(),device=id(),deviceKey='a'.repeat(64),foreignDeviceKey='b'.repeat(64),foreignDevice=id(),hash=s=>crypto.createHash('sha256').update(s).digest('hex');
await query("INSERT INTO companies VALUES($1,'Kunde'),($2,'Andere Firma')",[company,otherCompany]);for(const [uid,cid,role,token]of [[admin,otherCompany,'admin','platform'],[owner,company,'owner','owner'],[other,otherCompany,'owner','other'],[waiter,company,'waiter','waiter']]){await query("INSERT INTO users(id,company_id,role,status) VALUES($1,$2,$3,'active')",[uid,cid,role]);await query("INSERT INTO sessions VALUES($1,$2,now()+interval '1 hour')",[hash(token),uid])}await query('INSERT INTO platform_admins VALUES($1,true)',[admin]);await query("INSERT INTO devices VALUES($1,$2,'Kasse',$3,'active','windows','0.2.1',now()),($4,$5,'Fremde Kasse',$6,'active','windows','0.2.1',now())",[device,company,deviceKey,foreignDevice,otherCompany,foreignDeviceKey]);
const handler=createRemoteSupport(pool);async function call(path,b=null,token='platform'){const req=Readable.from(b?[JSON.stringify(b)]:[]);Object.assign(req,{url:'/api/v1/remote-support/'+path,method:b?'POST':'GET',headers:{authorization:'Bearer '+token}});let status,data;assert(await handler(req,{writeHead(s){status=s},end(s){data=JSON.parse(s)}}));return {status,...data}}
const native=(path,b={})=>call('device/'+path,{deviceKey,...b},'owner');
assert.equal((await call('devices',null,'owner')).status,403);assert.equal((await call('device/poll',{deviceKey},'waiter')).status,403);assert.equal((await call('device/poll',{deviceKey},'other')).status,403);
assert.equal((await call('start',{deviceId:device})).status,409);await native('poll',{diagnostics:{supportProtocol:1,appVersion:'0.2.1',platform:'win32',online:true,password:'secret',userData:'/private'}});let diagnostics=(await call('devices')).devices.find(d=>d.id===device).support_diagnostics;assert.equal(diagnostics.supportProtocol,1);assert(!JSON.stringify(diagnostics).includes('secret'));assert(!JSON.stringify(diagnostics).includes('/private'));
let session=await call('start',{deviceId:device});assert.equal(session.status,201);assert.equal((await call('start',{deviceId:device})).status,409);assert.equal((await native('poll')).session.state,'requested');assert.equal((await call('device/sessions/'+session.id+'/accept',{deviceKey:foreignDeviceKey,allowed:true,controlAllowed:true},'other')).status,404);
assert.equal((await native('sessions/'+session.id+'/frame',{frame:'/9j/2Q==',width:100,height:100})).status,409);
assert.equal((await native('sessions/'+session.id+'/accept',{allowed:true,controlAllowed:false})).status,200);assert.equal((await native('sessions/'+session.id+'/accept',{allowed:true,controlAllowed:true})).status,409);
assert.equal((await native('sessions/'+session.id+'/frame',{frame:'/9j/2Q==',width:100,height:100})).status,200);assert.equal((await call('sessions/'+session.id+'/input',{type:'click',x:1,y:1,frameSequence:1})).status,403);assert.equal((await call('sessions/'+session.id)).session.frameSequence,1);await native('sessions/'+session.id+'/stop');assert.equal((await call('sessions/'+session.id)).session.frame,null);
session=await call('start',{deviceId:device});await native('sessions/'+session.id+'/accept',{allowed:true,controlAllowed:true});await native('sessions/'+session.id+'/frame',{frame:'/9j/2Q==',width:100,height:100});assert.equal((await call('sessions/'+session.id+'/input',{type:'click',x:100,y:1,frameSequence:1})).status,409);assert.equal((await call('sessions/'+session.id+'/input',{type:'key',key:'Meta',frameSequence:1})).status,400);
const action=await call('sessions/'+session.id+'/input',{type:'text',text:'private entered text',frameSequence:1});assert.equal(action.status,202);assert.equal((await call('sessions/'+session.id+'/input',{type:'reload',frameSequence:1})).status,409);assert(!JSON.stringify(await call('sessions/'+session.id)).includes('private entered text'));
const poll=await native('poll');assert.equal(poll.commands.length,1);assert.equal((await native('poll')).commands.length,0);assert.equal((await native('sessions/'+session.id+'/ack',{inputId:action.id,state:'completed'})).status,200);assert.equal((await native('sessions/'+session.id+'/ack',{inputId:action.id,state:'failed'})).status,409);assert(!JSON.stringify((await query('SELECT input FROM remote_support_inputs WHERE id=$1',[action.id])).rows).includes('private entered text'));
assert.equal((await query("SELECT count(*)::int n FROM audit_log WHERE event_type='remote_support.input'")).rows[0].n,1);assert.equal((await query("SELECT count(*)::int n FROM audit_log WHERE event_type='remote_support.ack'")).rows[0].n,1);
await query("UPDATE remote_support_sessions SET expires_at=now()-interval '1 second' WHERE id=$1",[session.id]);assert.equal((await native('poll')).session,null);assert.equal((await call('sessions/'+session.id)).session.frame,null);assert.equal((await call('sessions/'+session.id+'/input',{type:'reload',frameSequence:1})).status,409);
session=await call('start',{deviceId:device});await native('sessions/'+session.id+'/accept',{allowed:true,controlAllowed:true});await native('sessions/'+session.id+'/frame',{frame:'/9j/2Q==',width:100,height:100});await query('DELETE FROM sessions WHERE user_id=$1',[owner]);assert.equal((await call('sessions/'+session.id)).session.state,'ended');assert.equal((await call('sessions/'+session.id)).session.frame,null);
await query("INSERT INTO sessions VALUES($1,$2,now()+interval '1 hour')",[hash('owner'),owner]);session=await call('start',{deviceId:device});await native('sessions/'+session.id+'/accept',{allowed:true,controlAllowed:true});await query('UPDATE platform_admins SET active=false WHERE user_id=$1',[admin]);assert.equal((await native('poll')).session,null);await query('UPDATE platform_admins SET active=true WHERE user_id=$1',[admin]);
assert.throws(()=>supportInput({type:'text',text:'a\npassword',frameSequence:1}));assert.equal(safeDiagnostics({pendingOfflineSales:-1}).pendingOfflineSales,null);
// Browser permission rendering and same-origin admin calls.
const dom=new JSDOM('<div id="dash"><div class="tabs"></div></div>',{url:'https://pos.example/admin/',runScripts:'outside-only'}),w=dom.window;w.AbortSignal=AbortSignal;w.localStorage.setItem('bringness-pos-token','platform');w.fetch=async(url,opts={})=>{const result=await call(String(url).replace('/api/v1/remote-support/',''),opts.body?JSON.parse(opts.body):null,'platform');return {ok:result.status<400,status:result.status,json:async()=>result}};w.eval(fs.readFileSync(new URL('../../apps/web/public/admin/remote-support.js',import.meta.url),'utf8'));const wait=async f=>{for(let i=0;i<100;i++){if(f())return;await new Promise(r=>setTimeout(r,10))}throw Error('Admin UI timeout')};await wait(()=>w.document.querySelector('[data-tab="remoteHelp"]'));w.document.querySelector('[data-tab="remoteHelp"]').click();await wait(()=>w.document.querySelector('[data-start-device]'));assert(w.document.getElementById('remoteDevices').textContent.includes('Client unterstützt Fernhilfe'));w.close();
await db.close();console.log('Remote support passed: platform rights, tenant/device isolation, explicit view/control consent, frame validation, at-most-once dispatch, redacted input, stop, expiry, logout/revocation, audit and admin DOM.');
