const $=id=>document.getElementById(id),money=n=>(n/100).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
let snapshot,cart=new Map(),pendingRequest,busy=false;
function message(s){$('message').textContent=s}
function showReceipt(receipt){const groups=new Map();for(const item of receipt.items)groups.set(item.taxRate,(groups.get(item.taxRate)||0)+item.lineCents);const taxes=[...groups].map(([rate,gross])=>{const net=Math.round(gross/(1+rate/100));return 'Steuer '+rate.toLocaleString('de-DE')+' % · Netto '+money(net)+' · MwSt: '+money(gross-net)});const m=receipt.merchant||{};$('receipt').textContent=[m.businessName,m.restaurantName,m.street,[m.postalCode,m.city].filter(Boolean).join(' '),m.vatId?'USt-ID: '+m.vatId:null,receipt.receiptNumber,new Date(receipt.createdAt).toLocaleString('de-DE'),...receipt.items.map(i=>i.quantity+' × '+i.name+' '+money(i.lineCents)),...taxes,'Bar: '+money(receipt.totalCents),'Fiskalisierung: ausstehend'].filter(Boolean).join('\n');$('print').disabled=false}
function draw(){const rid=$('restaurant').value;$('products').replaceChildren();for(const p of snapshot?.products.filter(p=>p.restaurantId===rid)||[]){const b=document.createElement('button');b.textContent=p.name+' · '+money(p.priceCents);b.onclick=()=>{if(pendingRequest)return;cart.set(p.id,(cart.get(p.id)||0)+1);draw()};$('products').append(b)}$('items').replaceChildren();let total=0;for(const [id,quantity]of cart){const p=snapshot.products.find(p=>p.id===id),li=document.createElement('li');total+=p.priceCents*quantity;li.textContent=quantity+' × '+p.name+' ';const b=document.createElement('button');b.textContent='−';b.onclick=()=>{if(pendingRequest)return;quantity>1?cart.set(id,quantity-1):cart.delete(id);draw()};li.append(b);$('items').append(li)}$('total').textContent=money(total);$('pay').disabled=busy||!cart.size||!snapshot||Date.now()>Date.parse(snapshot.validUntil)}
async function refresh(){const v=await offlinePOS.view();if(v.snapshot&&!pendingRequest&&(!cart.size||v.snapshot.id===snapshot?.id)){const rid=$('restaurant').value;snapshot=v.snapshot;$('restaurant').replaceChildren(...snapshot.restaurants.map(r=>{const o=document.createElement('option');o.value=r.id;o.textContent=r.name;return o}));if(snapshot.restaurants.some(r=>r.id===rid))$('restaurant').value=rid;$('lease').textContent='Offline freigegeben bis '+new Date(snapshot.validUntil).toLocaleString('de-DE')}if(!snapshot)message('Für Offline-Verkäufe zuerst online anmelden und die Download-Lizenz aktivieren.');$('sales').replaceChildren(...v.sales.map(s=>{const p=document.createElement('p');p.textContent=s.receipt.receiptNumber+' · '+new Date(s.receipt.createdAt).toLocaleString('de-DE')+' · '+money(s.receipt.totalCents)+' · '+(s.synced_at?'Übertragen':'Auf Gerät gespeichert')+(s.error?' · '+s.error:'');const b=document.createElement('button');b.textContent='Beleg anzeigen';b.onclick=()=>showReceipt(s.receipt);p.append(b);return p}));draw()}
$('restaurant').onchange=()=>{if(pendingRequest){message('Den gespeicherten Verkauf zuerst erneut bestätigen.');$('restaurant').value=pendingRequest.restaurantId;return}cart.clear();draw()};
$('pay').onclick=async()=>{if(busy)return;busy=true;draw();try{pendingRequest??={id:crypto.randomUUID(),snapshotId:snapshot.id,restaurantId:$('restaurant').value,createdAt:new Date().toISOString(),paymentMethod:'cash',items:[...cart].map(([productId,quantity])=>({productId,quantity}))};const receipt=await offlinePOS.sale(pendingRequest);showReceipt(receipt);cart.clear();pendingRequest=null;message('Barverkauf dauerhaft gespeichert. Er wird bei bestehender Online-Anmeldung übertragen.');await refresh()}catch(e){message(e.message+' · Erneut bestätigen verwendet dieselbe Verkaufskennung.')}finally{busy=false;draw()}};
$('online').onclick=()=>offlinePOS.online();$('print').onclick=()=>window.print();offlinePOS.updated(()=>refresh().catch(e=>message(e.message)));refresh().catch(e=>message(e.message));
